### ISSUE TITLE
Add support for alternative MySqlConnector

### ISSUE THREAD

**Issue by ngbrown** [nhibernate/nhibernate-core#1375]
It was suggested by @303248153 to include [MySqlConnector](https://mysql-net.github.io/MySqlConnector/) in addition to MySql.Data.  It may provide better .Net Core support (#633) and has a different license.

This would be enabled by #626.

**Comment by fredericDelaporte** [comment]
We have to settle whether we wish to have alternate drivers handled by NHibernate team or let the community publish it as an independent packages once #626 is live.

Handled by us:
- more things to maintain.
- maybe less delays in publishing up-to-date versions when a breaking change mandates it.

Handled by anyone else who wish:
- less work on NHibernate team, letting more time to focus on core features
- may left some data providers in a stale state, unusable with latest NHibernate for long, a bit like what we can witness with caches providers for NHibernate v5. (Redis and EnyimMemcache (on NuGet) still not updated the last time I have looked (and I have sent a message to Enyim NuGet owner), although at least for Redis there are people awaiting it, but apparently not involved enough to do the change themselves. Note that for abandoned package on NuGet, the delay to claim ownership is at least one month, the other solution being to publish a dup, which is not fine.)

**Comment by hazzik** [comment]
I would prefer the approach with a separate repository under the https://github.com/nhibernate/ organization. This will solve the above concerns: the core team will have less work, but will be able to release a new version if there are breaking changes. Also, this does not even require the #626 to start. Just create a new repo and that's it.

**Comment by hazzik** [comment]
Created a new repo: https://github.com/nhibernate/NHibernate.MySqlConnector

**Comment by Reltik** [comment]
Another plus is that the MySqlConnector alternative support real async operations unlike the official connector

**Comment by jemiller0** [comment]
Any word on if this will be supported sometime soon? I see the repo, but, it looks like it's just empty.

**Comment by fredericDelaporte** [comment]
It needs someone willing to contribute it. It can be you.

**Comment by razzmatazz** [comment]
Hi, I have added a PR for this https://github.com/nhibernate/NHibernate.MySqlConnector/pull/1 with the code that I am using in production however there are a couple of things I am not sure about – from PR:
 - how to build a nuget package
 - should we provide support for multiple frameworks in .csproj (as it uses .netstandard2.0 now)
 - what version of NHibernate should I reference in .csproj (now it has 5.2.1 specified)

**Comment by dennis-gr** [comment]
I've created a new [PR](https://github.com/nhibernate/NHibernate.MySqlConnector/pull/2) to get this done a couple of weeks ago, which might have gone unnoticed. It would be nice of someone could a review.

**Comment by jemiller0** [comment]
It would be great to get that in there. Oracle's driver is horrible. It would be great to be able to get rid of it.

**Comment by razzmatazz** [comment]
I have been running  mysqlconnector using glue code from PR #1 in production for almost a year already, no problems so far. So thumbs up as well for @dennis-gr if yours goes in.

**Comment by hazzik** [comment]
Thanks everyone, I've published the @dennis-gr's version.

**Comment by fredericDelaporte** [comment]
So closing as somewhat "external issue" since it has been handled through a separated project, see nhibernate/NHibernate.MySqlConnector#2, and get the NuGet [here](https://www.nuget.org/packages/NHibernate.Driver.MySqlConnector).
