### ISSUE TITLE
NHibernate's IQuery is missing AddSynchronizedQuerySpace

### ISSUE THREAD

**Issue by gliljas** [nhibernate/nhibernate-core#1381]
...and AddSynchronizedEntityName and AddSynchronizedEntityClass. This is crucial when 2nd level cache is enabled and ExecuteUpdate is performed on a native SQL query. Currently this causes a massive cache eviction, when it's often unnecessary.

**Comment by hazzik** [comment]
is it a new feature or a bug?

**Comment by gliljas** [comment]
For NHibernate it's a new feature, but it's been available in Hibernate for ages.
