### ISSUE TITLE
Add donate button into readme

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nhibernate/nhibernate-core#1383]
You are doing awesome work! Where is donate button?  There are plenty options for donation. Just search the internet. I think you will find that suits your needs.

[Last time it was 7 years ago and seems obsolete](https://groups.google.com/forum/#!searchin/nhusers/donate|sort:relevance/nhusers/vaY0mN4jngg/T_YyFLo3FEcJ).

**Comment by fredericDelaporte** [comment]
The main road-block for such a feature is: who receives the money? For doing it well, NHibernate would need something like a foundation. The NHibernate contributors community is currently a group of volunteers, without a legal formal structure.

**Comment by dzmitry-lahoda** [comment]
As possible options for consideration:

1. List most active contibutors for some period in readme with link to give some money to one of them. So I may choose the person who delivered feature I wanted most. There are many options to tip persons in the internet. Just search them.

2.  You may create virtual organization on blockchain and receive crypto coins.

3. Contact some foundations/meta organizations which do the stuff for you. If they will accept HN for governance. 

I know that there are many enterprises which use NH, but they have no ability to donate.

**Comment by ngbrown** [comment]
There is the [.NET Foundation](https://dotnetfoundation.org/) that is open for project to join.

From the [about](https://dotnetfoundation.org/about):

> The .NET Foundation is not a grant funding body but the .NET Foundation can help projects accept, invoice and process donations in-kind or earmarked donation on behalf of the individual projects. As a US tax-exempt non-profit organization (501.(c)(6)), there are some limits on what projects can do with those assets but the foundation will work with the project to ensure funds are spent appropriately. When running events such as meet-ups and conferences, the foundation can also work with projects to create ticket selling accounts, arrange contracts with venues etc. Donations typically cover activities including hosting expenses, travel expenses to attend conferences / meetups, promotional items for the project, sponsoring or organizing a conference/meet-up.

**Comment by hazzik** [comment]
There is 8+ years old [discussion](https://groups.google.com/d/msg/nhibernate-development/fPWe-jHEYRk/SnBVA5x5a5UJ) on this topic which outlines all the issues with the donations. Majors are: who gets the money, taxes, etc. 

Pledge was there for several years until it was shut down recently. This campaign raised about $0. 

The only option to make it right with money is to join/set up a foundation, but given the prior statistics, I don't think this worth it.

The most valuable donation is the people's efforts. So, send us PRs, not money.

**Comment by knuxbbs** [comment]
@hazzik What about joining .NET Foundation?

**Comment by fredericDelaporte** [comment]
Honestly I would not know what to do with money for NHibernate.

There are people willing to pay for getting some features done? I am fine with that in principle, but to have this work reasonably well, it would require us to be able to guarantee some ETA not too far away, and to have some trusted contributor for which getting this money would be enough of an incentive to do that feature and deliver it on a timely manner, while not doing it in a way detrimental to NHibernate as a whole.

I am not this person. I have a work which already consumes most of my coding time, and I do not really need to earn additional money.

Currently we may take about a year between two "minor" release of NHibernate (a lot less for patches, but patches are not here to bring new features in), which does not sound like a reasonable delivery timetable for some paid feature.

I can only second what has already said Hazzik:

> The most valuable donation is the people's efforts. So, send us PRs, not money.

(This includes also reviewing and refining proposed PR to help them get merged.)
