### ISSUE TITLE
Lack of custom logging documentation (was Serilog Tracing)

### ISSUE THREAD

**Issue by mobius127** [nhibernate/nhibernate-core#1386]
How can I configure Serilog for logging NHibernate?

**Comment by fredericDelaporte** [comment]
By default NHibernate logs with log4net, if its assembly is available.
This can be changed by specifying the full type name of a custom `NHibernate.ILoggerFactory` within an appSetting parameter named `nhibernate-logger`.

But it may not be enough for what you expect by logging with Serilog. Some works are ongoing for modernizing the logging capabilities of NHIbernate, see #1377.

**Comment by fredericDelaporte** [comment]
Documentation of `nhibernate-logger` is lacking. And maybe it is the case for some other similar "out of standard conf" parameters. (Or maybe not, the only references to `System.Configuration.ConfigurationManager.AppSettings` are done for this one.)
