### ISSUE TITLE
Performance regression in SessionIdLoggingContext

### ISSUE THREAD

**Issue by maca88** [nhibernate/nhibernate-core#1391]
By doing some profiling, I discovered that the introduction of [`AsyncLocal<>`](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Impl/SessionIdLoggingContext.cs#L8) inside the `SessionIdLoggingContext` caused a performance regression of approximately 6.5% when retrieving a bigger result set.

Here is the test that I ran, which uses the data provided by the `LinqTestCase` class.
```
[Test]
public void PerformanceTest()
{
    var list =
            db.Orders
              .FetchMany(o => o.OrderLines)
              .ThenFetch(o => o.Product)
              .ThenFetch(o => o.Category)
              .ToList();
    Assert.AreEqual(830, list.Count);
}
```
The test completed in 1557ms, where 97ms was spent inside `SessionIdLoggingContext`:
![asynclocal](https://user-images.githubusercontent.com/5311349/31735987-baa5efc4-b443-11e7-92c1-757a328b053b.png)

By replacing `AsyncLocal` with `ThreadLocal` as it was prior the async addition, the `SessionIdLoggingContext` disappears from the radar, which proves that `AsyncLocal` is way slower than `ThreadLocal` and we should use it only when necessary.

In order to avoid those penalities for consumers that don't use it, I think that we should provide a way to disable it (e.g. by adding a simple flag on the class itself).

**Comment by hazzik** [comment]
@maca88 there are some issues with the generation of async tests for that PR. Could you please take a look?

**Comment by maca88** [comment]
Upgrading to `0.6.2` will fix [the problem](https://github.com/maca88/AsyncGenerator/issues/71).

**Comment by hazzik** [comment]
Thanks
