### ISSUE TITLE
5.0.x branch?

### ISSUE THREAD

**Issue by ngbrown** [nhibernate/nhibernate-core#1396]
While 5.0.1 issues are being accumulated in the master branch, no 5.1 pull requests can be merged.  Should there be a branch to help things move along?

**Comment by oskarb** [comment]
A stable release branch is what we have typically done for last couple of
releases anyway.

2017-10-20 18:45 GMT+01:00 Nathan Brown <notifications@github.com>:

**Comment by ngbrown** [comment]
It appeared that the stable branch use fell out of favor because every single pull request merged into master had to be merged into stable as well.  A 5.0.x branch would be specifically targeted for critical bug fixes and then be merged into master from the branch.

**Comment by hazzik** [comment]
Sure, but later.

**Comment by hazzik** [comment]
@ngbrown I think this type of questions shall go to nhibernate-dev group

**Comment by fredericDelaporte** [comment]
[Posted](https://groups.google.com/forum/#!topic/nhibernate-development/_WMDxvU6J84).
