### ISSUE TITLE
Nhibernate Validator not updated to work with NH5

### ISSUE THREAD

**Issue by matteosaporiti** [nhibernate/nhibernate-core#1398]
I wasn't sure where to add the issue but I decided to open it here because NHV main repository is still Dario Quintana's (and is abandoned).  
Anyway, NHV needs to be updated to support Nhibernate 5.

Thanks.

**Comment by fredericDelaporte** [comment]
Issues for NHibernate.Validator are [here](https://nhibernate.jira.com/projects/NHV/issues/NHV-128).
There is a PR for 5.0: nhibernate/NHibernate-Validator#3
But it seems no one involved in it has currently time to review it.
