### ISSUE TITLE
DynamicComponent is null

### ISSUE THREAD

**Issue by csharpdeveloper12** [nhibernate/nhibernate-core#1407]
Hello :),

i have an issue concerning "dynamic component".

In my entity is the property as IDictionary (new HashTable()).
If i use the dynamic component feature it works perfect while the mapped columns in the dynamic component are <> "NULL".
If the content of the mapped column is "NULL" then the IDictionary in the entity is also "NULL".
If the content of the mapped columns <> "NULL" then the IDictionary has items.

Can you please check this behavior.

Thanks in advance :)

**Comment by fredericDelaporte** [comment]
Highly looks to me as "by design", because that is the same behavior for non dynamic components : they are null on entity if all their columns are null. It is up to you to instantiate them before setting their values in such case.

**Comment by gliljas** [comment]
I can confirm that it is by design. The only way for NH to distinguish between a "NULL component" and a "NON NULL component" is if all the columns are null. Handle it in your property getter.
