### ISSUE TITLE
Table counter for aliases should be stable

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#1417]
`NHibernate.Mapping.Table` has a thread static integer field `tableCounter` which is incremented at each call to `Table` constructor, and serves in SQL aliases suffixes. Those calls are triggered mainly by setting up `NHibernate.Cfg.Configuration` and secondarily by building session factories (for preparing temp tables).

In case of application building many configurations and sessions factories, this causes the SQL aliases length to grow based on the number of previous configurations/factories previously used.

This by example causes a coupling between NHibernate tests, as seen in #1415 where some tests fail based on the number of previous tests executed before them.

Ideally, this counter should be bound to configuration then session factories. But this will likely require many interface changes for by example passing along an object holding the counter value and allowing its increment. (Could be `IMapping`.)

(This trouble is in my opinion minor, because building a lot of configuration and session factories is not an usual pattern.)

Update: as noted by @bahusoid, this may also cause session factories built for the same mapping to use different queries, which may cause performance troubles on databases with execution plan caching. This counter should stay the same for session factories built for the same mapping.

**Comment by hazzik** [comment]
There was a typo in the title. It shall be either of "Table tableCounter should not *rise* endlessly" or "Table tableCounter should not *be raise* endlessly"
