### ISSUE TITLE
NHibernate.4.0.3.4000  Queryover().Skip().Take()  get wrong datas

### ISSUE THREAD

**Issue by JackLoveKaren** [nhibernate/nhibernate-core#1422]
Database: SQL 2008.
NHibernate.4.0.3.4000 using 
```
var data=QueryOver<Model>().Where(p=>p.Code=Code)
.OrderBy(p=>p.ID).Skip(pageSize*(page-1)).Take(pageSize).List()
```
when set page=1,pageSize=10 ,It's ok. But when set page=2, pageSize=10, I get nothing!

**Comment by fredericDelaporte** [comment]
There are many passing tests using paging in NHibernate tests suit, so please provide a complete failing test case. See [contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md).

**Comment by hazzik** [comment]
Please proved more details, then issue can be reopened.
