### ISSUE TITLE
Memory leak in nhibernate 5

### ISSUE THREAD

**Issue by uciprian** [nhibernate/nhibernate-core#1433]
We've recently upgraded to nhibernate 5 from nhibernate 4 and we're experiencing a memory leak due to nhibernate on one of our services
Important notes:
- we haven't change the way we open and close sessions/transactions or changed the number of these after the upgrade
- the only notable changes as part of the upgrade were:

1. changing in mapping and fixing DateTime values to ensure we use UTC 
2. remove cacheable everywhere since Nhibernate 5 has already open bugs with nhibernate redis caching which we also experienced
3. prevent throwing multi loaded bags exception

Why I'm pretty sure Nhibernate is the culprit? because based on profiler StatefulPersistenceContext object instance retains the majority of process memory till physical memory is exhausted, see attached image
![image](https://user-images.githubusercontent.com/17974897/32838052-6c974e5a-ca18-11e7-8903-a89ed48b222b.png)

For some reason when session is disposed the entities associated with session are not cleared from persistence context.

Unfortunatelly we're forced to downgrade to Nhibernate 4

**Comment by fredericDelaporte** [comment]
Would be able to write a test case showcasing the leak? It would greatly help.

Side note about:

> Nhibernate 5 has already open bugs with nhibernate redis caching 

Nothing found by searching "redis" neither here on NHibernate and NHibernate.Caches Github issues (only your comment about it here), nor on the old Jira side (two closed tickets, one quite unrelated, the other asking for including a redis cache in nh-contrib, which was not done and left as a separated independent project.) Anyway there is no redis cache handled by NHibernate team.

It seems you are referring to something handled by other people than the NHibernate team. Googling a bit around, I can only find outdated projects (most recent update in 2016), which can not be compiled with NHibernate 5.0.0. If this is just that the trouble, all it takes to adapt them should be implementing the new async methods. They may be just calls to sync methods if the targeted cache does not support async, as done in f800358435f6c051cb2596a4aa5a831df66368d7.

**Comment by uciprian** [comment]
You're right about the issue is not in Nhibernate team circle, but the fact that dependent on packages like Nhibernate.Cache.Redis have  not updated their implementation with changes in some Nhibernate core interfaces

**Comment by uciprian** [comment]
I'm sorry,  there is no bug in nhibernate, there was the client user error, where some really bad query loaded so much data from database blocking the finalizer thread on garbage collection.

I'll close this
