### ISSUE TITLE
SQLiteDialect not supported Linq function: FirstOrDefault() and Take() 

### ISSUE THREAD

**Issue by ShoshanaTzi** [nhibernate/nhibernate-core#1435]
I use NHibernate Mapping and SQLite for db. Part of linq expression works good, but the others like FirstOrDefault() or Take() doesn't work. because the Linq generated to select Top(x or 1), and SQLite works with LIMIT

**Comment by fredericDelaporte** [comment]
Had forgotten to use the adequate SQLite dialect?

**Comment by ShoshanaTzi** [comment]
No... someone added custom dialect to `SQL Server 2008` and it's overrided the `SQLite` dialect
Thanks.
