### ISSUE TITLE
 StackOverflowException  in Merge  Entity With Lazy Property   

### ISSUE THREAD

**Issue by offan** [nhibernate/nhibernate-core#1436]
When you call `Merge`, you may get a `StackOverflowException`. Test added. May be corrected by a change in the file `PocoEntityTuplizer`, in the method `HasUninitializedLazyProperties`:
```c#
if (EntityMetamodel.HasLazyProperties 
    // add this
    && !(entity is IProxy))
```
But I do not know if it is correct or not.

**Comment by offan** [comment]
****

**Comment by offan** [comment]
broken link 
![default](https://user-images.githubusercontent.com/8559841/32880677-91067e58-cabf-11e7-9b8b-812b3a4e43a4.png)
Сommit a new branch with the added test
Permission to nhibernate/nhibernate-core.git denied to offan

post here test.

class LazyPropertyFixture

                [Test]
		public void CanMergeWithLazyProperty()
		{
			using (ISession s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				var book = new Book
				{
			            Name = "some name two",
                                    Id = 2,
                                    ALotOfText = "a lot of text ..." 
				}
                                s.Merge(book);
				tx.Commit();
			}
			using (ISession s = OpenSession())
			{
				book = s.Get<Book>(2);
				Assert.That(book, Is.Not.Null);
			}
		}

**Comment by fredericDelaporte** [comment]
Thanks for the reports, readme file is now fixed.

You cannot push directly to NHibernate repository, you need to first fork it as one of your own repositories (`Fork` button is normally in upper right corner of GitHub pages), clone your own repository locally (instead of the NHibernate one), create a branch on it, commit then push to your own repository fork then PR from it.

**Comment by offan** [comment]
repo:  https://github.com/offan/nhibernate-core
branch GH1436

**Comment by fredericDelaporte** [comment]
We are working with pull requests (PR). Issue a PR from your branch toward nhibernate repository master branch.
