### ISSUE TITLE
Unable to use an entity with a `FieldInterceptor` property and a lazy loaded property

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#1442]
When an entity has a property named `FieldInterceptor` with another type than `IFieldInterceptor`, it cannot have a lazy loaded property.

Trying to combine both causes an `InvalidCastException` when loading such an entity.

**Comment by hazzik** [comment]
@fredericDelaporte since we are now in a control of how proxies are generated, we probably should allow some special implementations for such special cases.

**Comment by fredericDelaporte** [comment]
Well, maybe yes, but in fact I do not really understand what you mean here.

> since we are now in a control of how proxies are generated, we probably should allow some special implementations

Till there of course yes if you foresee a different implementation bringing some advantages, although I have no idea which.

> for such special cases.

From there, if this means having a different code path for handling cases where the entity definition may conflict with some NHibernate specific internals the user should not have any knowledge of, I would tend to think "only if we have no other choice, if there is no way to do it with an almost single code path".

I guess I do not actually get what you are referring to.

**Comment by hazzik** [comment]
What I mean is that there are several utility interfaces which are implemented by proxies: INHibernateProxy, IFieldInterceptorAccessor, IProxy, etc. INHibernateProxy and IFieldInterceptorAccessor are quite important. Unfortunately, implementation of these interfaces do go through the generic path of IInterceptor. Unfortunately, this path has a performance penalty, when it could just be implemented as simple property returning an instance field. The generic path was a necessity when we were using an all-purpose dynamic proxy libraries. But now this is an atavism which can and need to be cut.

IProxy being a utility interface of a dynamic proxy library is already taking this approach.

**Comment by hazzik** [comment]
So, typical INHibernateProxy implemented like this (not an actual code, I did not have time to decompile the generated library):

```
public virtual HibernateLazyInitializer 
{
   get   
   {
        //In most cases __interceptor is DefaultLazyInitializer
        if (__interceptor == null) return ((INHibernateProxy)base).HibernateLazyInitializer;
        return _interceptor.Intercept(new InvocationInfo(/* here is some heavy reflection */));
   }
}
```

Down the chain, DefaultLazyInitializer checks the method is "get_HibernateLazyInitializer" and returns ... `this`.

So proposal is to make a shortcut for these well known interfaces.

**Comment by fredericDelaporte** [comment]
Ok, agreed. I have not checked the details but if this implies to drop the ability to specify a `proxyfactory.factory_class`, it would then have to bump the version to 6.0. So if we do not turn 5.1 to 6 instead, then we should open an issue about that to keep track of it for 6.0.
