### ISSUE TITLE
Document IsDirty potential side effects

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#1449]
As described in #1413, `ISession.IsDirty` default implementation can have side effects with serious consequences. They should be documented.

- It will trigger pending `SaveOrUpdate` cascades.
- The triggered `Save` will generates the ids of the saved entities. Depending on the id generator, this may cause calls to the database, or even the direct insertion of the entities when using the `identity` generator.

**Comment by hazzik** [comment]
@fredericDelaporte I think that we do not need to create an issue together with a PR, eg, if you know that you'll submit a PR shortly after the issue is created.

**Comment by fredericDelaporte** [comment]
Yes, a bit "old Jira" reflex, I thought about it afterward.
