### ISSUE TITLE
nvarchar(max) problem

### ISSUE THREAD

**Issue by gkcleo1022** [nhibernate/nhibernate-core#1473]
I am new two nhibernate, but a facing nvarchar(max) problem a lot

`<property name="templateQuery" column="TemplateQuery" type="StringClob" sql-type="nvarchar(max)" />`

i write the above code like that in my mapping file , but at run time it showing error like

**The 'sql-type' attribute is not declared.**

Please give the solution

**Comment by gliljas** [comment]
1. sql-type belongs on a "column" subelement.
2. Please post such questions on https://groups.google.com/forum/#!forum/nhusers instead.

Best regards

**Comment by gkcleo1022** [comment]
Then I have small doubt for mentioning nvarchar(max) below code is enough 

<property name="templateQuery" column="TemplateQuery" type="StringClob" />
