### ISSUE TITLE
Exception when using envers with the latest logging changes

### ISSUE THREAD

**Issue by lnu** [nhibernate/nhibernate-core#1478]
We're using envers and now it fails with this error at runtime:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'NHibernate.Envers.Configuration.Store.AuditMappedByMetaDataAdder' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NHibernate.LoggerProvider.LoggerFor(Type type)
   at NHibernate.Envers.Configuration.Store.AuditMappedByMetaDataAdder..cctor()
   --- End of inner exception stack trace ---
   at NHibernate.Envers.Configuration.Store.AuditMappedByMetaDataAdder.addToEnti
tyMeta(AuditMappedByAttribute attribute, EntityMeta entityMeta, MemberInfo membe
rInfo)
```
It's the related to the new logging refactoring. I guess it will also fails with other libraries.

```
[Obsolete("Use NHibernateLogger.For() instead.")]
public static IInternalLogger LoggerFor(System.Type type)
{
    return _legacyLoggerFactory.LoggerFor(type);
}
```

it fails because the `_legacyLoggerFactory` is null

edit: I did the changes in envers to use the new logging(`NHibernateLogger.For`') and it wokrs. But in the meantime it should work with the old version wihtout any issues.

**Comment by hazzik** [comment]
@ngbrown could you take a look?

**Comment by ngbrown** [comment]
It was a mistake for me to split the global logging factory state and then try to synchronize them.  I've made a pull request that beefs up the unit tests around this and then fixes the issue.  See #1479.
