### ISSUE TITLE
asks about nunit 3 compatibility 

### ISSUE THREAD

**Issue by tfeloy** [nhibernate/nhibernate-core#1510]
Hello everyone,
I need to know if the latest version is fully compatible with nunit 3. I have problems with the tests with Spring and Nhibernet and I can not find the solution, but I have to discard some things for that.

Thank you!

**Comment by oskarb** [comment]
Hi,

This is the bug tracking system. Please instead use the user groups for general discussions:
http://nhibernate.info/groups.html

However, I don't see why NHibernate and NUnit would in any way affect each other.
