### ISSUE TITLE
NHibernate Performance issue with Azure SQL server

### ISSUE THREAD

**Issue by Chaitanya1231** [nhibernate/nhibernate-core#1522]
Hi,

I'm facing performance issues wit our production website. It takes forever to navigate through different pages. I found the following in Application Insights on Azure portal. Nhibernate is making dependency calls to SQL server and there is a lag of more than 2 seconds between each dependency call that is being made. Can any one help me with this issue? Thanks in advance.

**Comment by fredericDelaporte** [comment]
Hello,

For now your report is a bit far from being an issue: it lacks to much diagnosis information. It could be an issue actually unrelated to NHibernate.

If you do not know how to better describe the issue, collect more diagnosis information, actually allowing to ascertain NHibernate is at stake, can you please ask for support on [NHUsers group](https://groups.google.com/forum/#!forum/nhusers) instead?

> Nhibernate is making dependency calls to SQL server and there is a lag of more than 2 seconds between each dependency call that is being made. 

I do not understand to what this can refer. Are you using `SysCache2` with some cache dependencies defined in it? If you refer to this, then it is maybe a [NHibernate.Caches](https://github.com/nhibernate/NHibernate-Caches) issue (or a misuse on your application side), and it will not be handled here. Better first seek support about this on NHUsers (or stackoverflow or other resources, as you see fit).

Closing for now. You can ask to re-open it if you supply information allowing to ascertain this is a NHibernate issue.
