### ISSUE TITLE
Supporting of MS SQL 2016

### ISSUE THREAD

**Issue by sloginov** [nhibernate/nhibernate-core#1538]
Hello!
Please tell me, do you have plans to add dialect for Microsoft SQL 2016 in a future releases of NHiberante?

**Comment by fredericDelaporte** [comment]
See #956.

**Comment by oskarb** [comment]
Since there is sometimes confusion on the matter, I wanted to add that implementing new dialects is mostly about adding support for some new feature. As far as I know NHibernate already supports SQL Server 2016 by using an earlier dialect class.
