### ISSUE TITLE
Update NHibernate v3.3.3.4001

### ISSUE THREAD

**Issue by lavoyech** [nhibernate/nhibernate-core#1554]
Hi,

I have a .NET project using NHibernate to connect to a PostGreSQL database.

I will try to present my problem even if it's not clear for me.

My project is compiled with framework .NET v4 and use NHibernate v3.3.3.4001 and NHibernate.Linq.1.0.

My layer access to the database is generated with Devart EntityDeveloper.

this is how nhibernate is configured in my web.config file:

`  <hibernate-configuration xmlns="urn:nhibernate-configuration-2.2">
    <session-factory>
      <property name="connection.provider">NHibernate.Connection.DriverConnectionProvider</property>
      <property name="dialect">NHibernate.Dialect.PostgreSQLDialect</property>
      <property name="connection.driver_class">NHibernate.Driver.NpgsqlDriver</property>
      <property name="connection.connection_string_name">ApiXcatAdmin.Connexion</property>
      <property name="show_sql">true</property>
      <property name="current_session_context_class">web</property>
      <mapping assembly="MyDataAccess" />
    </session-factory>
  </hibernate-configuration>
`

I want to update both .NET framework (to v4.5.2) and NHibernate (to v5.0.3).

When i change the .NET framework to v4.5.2 and compile my project i get an error:

Custom tool error: unpossible to cast object type 'EntityDeveloper.NHibernate.HibernateModelDescriptor' to 'EntityDeveloper.ModelDescriptor'

And when i try to upgrade the NHibernate dll via "Manage NuGet packages" the install fails saying

Unpossible to install package « NHibernate 5.0.3 ». You try to install the package in project« .NETFramework,Version=v4.5.2 », but package doesn't contain any file
 or assembly reference compatible with the infrastructure (i have tried to translate literrally from french)

So my questions are:

Is NHibernate v5.0.3 compatible with .NET framework v4.5.2?

Why changing the framework from v4 to v4.5.2 give me a cast error?

**Comment by fredericDelaporte** [comment]
NHibernate V5 targets .Net framework v4.6.1. That is why NuGet cannot install it in your case. Either upgrade your framework, or upgrade to NHibernate 4.1.1.4000 at most.

> Custom tool error: unpossible to cast object type 'EntityDeveloper.NHibernate.HibernateModelDescriptor' to 'EntityDeveloper.ModelDescriptor'

It looks like a thing specific to your project and not provided by NHibernate. We cannot sort this out.

By the way, this place here is for reporting proven bugs or feature requests. Please ask for support on [nhusers group](http://groups.google.com/group/nhusers) or on some other places like StackOverflow.

**Comment by lavoyech** [comment]
Thanks for your support and sorry about the misunderstanding where i place my request.

**Comment by fredericDelaporte** [comment]
Well, your cast trouble is maybe not specific to your project but to an external tool (external from NHibernate standpoint): [Entity Developer](https://www.devart.com/entitydeveloper/). Better seek support for this on their side in such case.
