### ISSUE TITLE
Linq query with "Contains" on persistent collection fails

### ISSUE THREAD

**Issue by v-kabanov** [nhibernate/nhibernate-core#1556]
Code like
```                    var parent = session.Get<ParentEntity>(1);

                    session.Query<GrandChildEntity>()
                        .Where(e => parent.Children.Contains(e.Parent))
                        .FirstOrDefault();
```
worked in v4, but fails in v5.
Self-contained test: https://github.com/v-kabanov/Nh5Regression/blob/master/ContainsSubquery.cs

**Comment by v-kabanov** [comment]
By the way, in the test the persistent collection in that test is loaded eagerly despite being mapped as lazy.

**Comment by gliljas** [comment]
Not when I run it. It immediately lazy loads it, though.

/G

2018-01-29 2:00 GMT+01:00 v-kabanov <notifications@github.com>:

**Comment by v-kabanov** [comment]
Yes, I was wrong, lazy loading was triggered by debugger.
