### ISSUE TITLE
Questions about NHibernate 51

### ISSUE THREAD

**Issue by alexinea** [nhibernate/nhibernate-core#1564]
Hi, guy. How can I get NHibernate 5.1 (release or prerelease) ...or... when we can get NHibernate 5.1? Is there any schedule about that? 

Thx a lot.

**Comment by fredericDelaporte** [comment]
Hi,

Please ask questions on the NHibernate Google groups. There is the [User group](https://groups.google.com/forum/#!forum/nhusers) and the [Development group](https://groups.google.com/forum/#!forum/nhibernate-development).

This said, there is currently no automated pre-release, and do not plan to do a beta release.
But you can get the binaries from continuous integration. 
Go on the [master commits](https://github.com/nhibernate/nhibernate-core/commits/master), click the green mark on a commit, click on the "Details" link of the "Release" build (which may not be already there for latest commits; [latest build](https://teamcity.jetbrains.com/viewLog.html?buildId=1309490&buildTypeId=NHibernate_NHibernateReleasePackage)). TeamCIty may ask for credential, choose the anonymous option if not having an account. Then go to the [artifacts](https://teamcity.jetbrains.com/viewLog.html?buildId=1309490&buildTypeId=NHibernate_NHibernateReleasePackage&tab=artifacts) tabs. Binaries are still labeled with the latest released version number: we change that only when publishing the new version.
