### ISSUE TITLE
Is there any plan to support compile-time weaving similar to what Hibernate 5 already support?

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [nhibernate/nhibernate-core#1566]
Hi, Is there any plan to support this feature?

**Comment by fredericDelaporte** [comment]
There is an external support of it: [ProxyGenerators](https://github.com/nhibernate/NHibernate.ProxyGenerators).

Hibernate may have use for build-time weaving beyond proxies, depending on the chosen dirty check mechanism. This is not the case of NHibernate, which only supports the default dirty check mechanism. (See [here](https://vladmihalcea.com/the-anatomy-of-hibernate-dirty-checking/) if you do not know about what I am speaking.)

There is no plan to directly support compile-time weaving of proxies in the core.
