### ISSUE TITLE
NHibernateLogger.GetNhibernateLoggerClass() throws NotImplementedException

### ISSUE THREAD

**Issue by vgelmut** [nhibernate/nhibernate-core#1572]
I have .NET Core 2.0 console app project (also there is asp.net core mvc and unit tests projects with same issues).
When installing NHibernate.Core from Nuget, I got this exception when trying to construct new Nhibernate.Cfg.Configuration().

Decompiling sources showing that NHibernateLogger static constructor contains call to:

```
 private static string GetNhibernateLoggerClass()
 {
    throw new NotImplementedException();
 }
```

When reviewing the sources on Github, this method contains normal code instead.

P.S. Reproduced on different machines, so there is no decompiling or platform specific code issue.

**Comment by fredericDelaporte** [comment]
[NHibernate.Core](https://www.nuget.org/packages/NHibernate.Core/) is neither owned nor supported by the NHibernate team. Please contact the NuGet owner of the package instead.

**Comment by fredericDelaporte** [comment]
I have furthermore  sent this message to the owner:

> Hello,
>
> I am among NHibernate owners. Due to following support ticket, I discover your NHibernate.Core NuGet package.
> 
> https://github.com/nhibernate/nhibernate-core/issues/1572
> 
> I do not know if the NHibernate name is registered or not and if you have right to use its name as you have done here.
> 
> But at the very least you should change the properties of the package for making it clear this not an official .Net Core version of NHibernate.
> Please change or remove http://nhibernate.info/.
> Please modify the description/summary for stating this is a .Net Core port of your own (or derived from some other work like the pending PRs we have, if that is the case).
> 
> Regards,
> 
> Frédéric Delaporte

**Comment by vgelmut** [comment]
Thanks for the answer. I was really sure it's official.

What are the plans to move to .net core? I'm really expecting this for all my projects to upgrade to. Don't want to move to EF core

**Comment by fredericDelaporte** [comment]
There is #633 and #1523.
#633 is a PR from @ngbrown, awaiting since long but not considered valid by one owner, see its #1425 and #626 dependencies (and also [this comment here](https://github.com/nhibernate/nhibernate-core/pull/633#issuecomment-354969601); I have not checked this subject).

#1523 is a PR from @hazzik willing to provide .Net Core support with minimal changes. WIP.

There is also an issue, #954, but there is no significant activity there.

**Comment by annymsMthd** [comment]
We've been using #633 in production for a few weeks now with no issues.
