### ISSUE TITLE
Option to Create Primary Keys as NONCLUSTERED

### ISSUE THREAD

**Issue by nickdevore** [nhibernate/nhibernate-core#1575]
I promise I looked to see if this was already an issue, but it seems like I'm the first to want to create my primary keys as nonclustered?  I'm certainly willing to submit a PR for this.  At first glance I would simply create an overload on `Dialect`

    public void GetAddPrimaryKeyConstraintString(string constraintName, bool isClustered)
    {
        string createSql = " add constraint " + constraintName;
        if (!isClustered)
            createSql += " nonclustered";
        createSql += " primary key ";
        return createSql;
    }

...and pass in true for the existing method.  Then, I'd add an option to the mapping schema for the `id` element with an attribute name of `clustered` that defaults to `true`.

I'm thinking that since there isn't currently an option for this, that it must not be that popular of an idea, but I know there are certain tables I want something else besides the primary key to be the clustered index on the table.  Or at the very least, having the option to have the primary key not be the clustered index so that I can make some future index be the clustered index.

**Comment by fredericDelaporte** [comment]
> I'm thinking that since there isn't currently an option for this, that it must not be that popular of an idea

There are also many different dialects, and some for which the notion may not even exist. That is the case for Oracle, which creates tables as heap by default (no clustered index). It has an option at table creation for asking it to be ordered according to its primary key instead (so PK clustered).

This change would be dialect specific, and will be non-sens for db not handling this clustered notion.
I do not think such a db specific option should be available in mappings.

> Or at the very least, having the option to have the primary key not be the clustered index so that I can make some future index be the clustered index.

I guess those having the need currently just recreate the PK as non-clustered before adding their clustered index.

Or they override `GetAddPrimaryKeyConstraintString` in a custom dialect to switch all PK to `nonclustered`, if that suits them.

**Comment by nickdevore** [comment]
Ok, that makes sense. I think this should be closed then
