### ISSUE TITLE
Why Nhibernate <Set> cannot be mapped to c# IList

### ISSUE THREAD

**Issue by anilr945** [nhibernate/nhibernate-core#1576]
The .hbm file contains <Set> and my c# representation for it is IList. I know <Set> cannot be mapped to IList but I don't understand why is this limitation placed by NHibernate. Why .hbm <Set> cannot be mapped to IList. Please provide an explanation.

Below is the details of my .hbm file:

<?xml version="1.0"?>
  <class name="View" lazy="false">
    <id name="ViewId"/>
    <set name="ItemList" lazy="false" cascade="all" fetch="join" inverse="true">
      <key column="ref_view_id"/>
      <one-to-many class="Item"/>
    </set>
  </class>

  <class name="Item" lazy="false">
    <id name="DatabaseId" >
      <generator class="native"></generator>  
    </id>
      <property name="ItemId"/>
      <property name="ItemName"/>
    <many-to-one name="View" class="View" column="ref_view_id" cascade="all" fetch="join"/>
  </class>
</hibernate-mapping>

Please find the mapping of the c# class for it:

     public class View
    {
        public ListView()
        {
            ItemList= new List<Item>();
        }

        public IList<Item> ItemList{ get; set; }
        public string ViewId{ get; set; }
    }

**Comment by oskarb** [comment]
Hi,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

The reason is that a set and a list are mathematically two different concepts, where set provides uniqueness but not ordering, and a list does the opposite.
