### ISSUE TITLE
NHibernate 5 with Asp NET Core 2: Getting an exception when calling OpenSession

### ISSUE THREAD

**Issue by jgonte** [nhibernate/nhibernate-core#1577]
Exception:
System.TypeLoadException: 'Could not load type 'System.Runtime.Remoting.Messaging.CallContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.'

Code:

```c#
public void ConfigureServices(IServiceCollection services)
{
    var mapper = new ModelMapper();

    mapper.AddMapping<SchoolMapping>();

    var mapping = mapper.CompileMappingFor(new Type[] 
    {
        typeof(School)
    });

    services.AddSingleton<ISessionFactory>(options => 
    {
        var configuration = new Configuration().DataBaseIntegration(db => 
        {
            db.ConnectionString = Configuration.GetConnectionString("DefaultConnection");

            db.Driver<SqlClientDriver>();

            db.Dialect<MsSql2012Dialect>();
        });

        configuration.AddDeserializedMapping(mapping, "Test");

        return configuration.BuildSessionFactory();
    });

    services.AddScoped(factory => factory
        .GetServices<ISessionFactory>()
        .Single()
        .OpenSession()); // <-- Here is where the exception happens
```

... Rest of code omitted for brevity

**Comment by fredericDelaporte** [comment]
NHibernate does not support .Net Core yet.

**Comment by mazharqayyum** [comment]
@fredericDelaporte can you please point to feature request to support .net core if there is any?

**Comment by fredericDelaporte** [comment]
See #1572 where I have already write an abstract of current state of works on .Net Core.

**Comment by jgonte** [comment]
Since the issue I had was with the CallContext. I did some research and Remoting is not supported in NET Core
But looking at the code of NHibernate-Core I noticed they added
#if NETSTANDARD2_0 || NETCOREAPP2_0

So it looks that they are already supporting NET Core 2?

**Comment by fredericDelaporte** [comment]
No. There are just some places where code for supporting it has already been merged, but the master branch is far from supporting it.

**Comment by jgonte** [comment]
I have been experimenting with porting NHibernate to NET Core 2 and at least I got it to compile.
Of course it is not production ready :-)
I will continue playing with that

In case that can be of any help to somebody:
https://github.com/jgonte/nhibernate-netcore

**Comment by mazharqayyum** [comment]
@fredericDelaporte Thanks for the insights! A move to .net core is something many people will be looking forward too. I hope that nhibernate will consider it in near future :)
