### ISSUE TITLE
Boolan datatype migrating to db2 from oracle with Nibernate as ORM

### ISSUE THREAD

**Issue by rahfa** [nhibernate/nhibernate-core#1578]
0

down vote

favorite

 

I have been working on a big project using NHibernate and oracle DB and now to some reasons we are changing project DB and migrating to DB2. problem is that all query params with Boolean data type, that previously worked well with oracle, now runs with cast exception. Boolean types have been defined as number(1) in database and have 0,1 values. It seems that having this config : 
<entry key="query.substitutions" value="true 1, false 0, yes 'Y', no 'N'" />

oracle dialect for NHibernate converts Boolean param values to number(0/1) but DB2 dialect does not and in Db2 queries params with Boolean data type I see that for Boolean parameters , param value is true/false instead of 0/1 and then I'm getting following error:
Exception
SOURCE: Tosan.Framework.Persistence
INNER-EXCEPTION
MESSAGE: Specified cast is not valid.
SOURCE: IBM.Data.DB2
DATA: 
actual-sql-query: UPDATE LF1SYSPRM SET TRCVER = ?, L1007REFNUMATGN = ?, L1007STRTSEQNUM = ?, L1007ENDSEQNUM = ?, L1007VALIDSTART = ?, L1007VALIDEND = ?, L1007TYPLC = ?, L1007REVCUS = ?, L1007NEWDEBPAY = ?, TRCCRUI = ?, TRCCRTS = ?, TRCLUUID = ?, TRCLUTS = ? WHERE L1007ID = ? AND TRCVER = ?

and the running query is :
    UPDATE LF1SYSPRM SET TRCVER = ?, L1007REFNUMATGN = ?, L1007STRTSEQNU
M = ?, L1007ENDSEQNUM = ?, L1007VALIDSTART = ?, L1007VALIDEND = ?, L1007TYPLC =
?, L1007REVCUS = ?, L1007NEWDEBPAY = ?, TRCCRUI = ?, TRCCRTS = ?, TRCLUUID = ?,
TRCLUTS = ? WHERE L1007ID = ? AND TRCVER = ?;p0 = 83 [Type: Int32 (4)], p1 = 1 [
Type: Int32 (4)], p2 = 1000000 [Type: Int32 (4)], p3 = 9999999 [Type: Int32 (4)]
, p4 = 2014/02/20 04:27:00 ?.? [Type: DateTime (16)], p5 = 2025/02/20 04:27:00 ?
.? [Type: DateTime (16)], p6 = 1 [Type: Int32 (4)], **p7 = True [Type: Int16 (2)]**,
 **p8 = True [Type: Int16 (2)]**, p9 = '64' [Type: String (2)], p10 = 2016/02/21 04:
28:00 ?.? [Type: DateTime (16)], p11 = '64' [Type: String (2)], p12 = 2018/02/19
 10:47:44 ?.? [Type: DateTime (16)], p13 = 6122 [Type: Int32 (4)], p14 = 82 [Typ
e: Int32 (4)]

what is the best solution to solve this problem forcing the least changes in codes ? is there any way to just change in custom driver class or custom dialect code?

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

(It seems likely to me you need a custom type, somewhat similar to the `TrueFalse` or `YesNo` types but converting to number instead.)
