### ISSUE TITLE
Nhibernate Db2 dialect does not replace boolean true false values with 0/1 as it does in oracle dialect

### ISSUE THREAD

**Issue by rahfa** [nhibernate/nhibernate-core#1579]
Nhibernate dialect for oracle inserts 0/1 instead of true/false for Boolean parameter values having this setting:
```xml
 <entry key="query.substitutions" value="true 1, false 0, yes 'Y', no 'N',True 1, False 0" />
```
but this config does not work in Db2Dialect!and when running queries I see that for Boolean params, param type is int32 but value is true/false! and causes cast exception.  it seems that nhibernate considers Boolean params as smallint but does not replace values with 0/1 as it does for oracle queries !!

**Comment by fredericDelaporte** [comment]
The reading of a number as a boolean is a data provider feature, supported by the Oracle data provider but seemingly not by the DB2 one. It is not a NHibernate feature. Ask DB2 data provider supplier to change this if you feel like, but you likely have better to adapt your code instead, like I was suggesting in your other ticket #1578.
