### ISSUE TITLE
redundant rownum column in index 0

### ISSUE THREAD

**Issue by rahfa** [nhibernate/nhibernate-core#1580]
I have an native query and I have set the SetMaxResult property for that. I see that in generated query for DB2 NHibernate has changed my query result set columns  and there is a rownum column in index 0 !

**Comment by fredericDelaporte** [comment]
Please cease using the bug tracker system as a support system. Moreover your description is not detailed enough, anyone willing to help you would have to do a number of guesses about what is your actual trouble. (It seems likely to me your query has its own row limit logic, and then it is an error to ask NHibernate to insert an additional one. It may still be supported by some dialects, but not by all.)

For support, see http://nhibernate.info/groups.html
