### ISSUE TITLE
MsSql2012Dialect uses OFFSET & FETCH even when offset is null

### ISSUE THREAD

**Issue by gcesena** [nhibernate/nhibernate-core#1623]
From commit 171ae483a3a0052806da42655991a34b4b56b8da, MsSql2012Dialect started using OFFSET & FETCH syntax, even when no offset is defined and plain old TOP would have sufficed.

According to [https://docs.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql#best-practices](url), OFFSET & FETCH is preferred when a query paging solution is needed.

What about the scenario when we're only trying to limit the number of rows returned? That same page doesn't endorse one solution over the other.
Shouldn't the simpler syntax be preferred?
May it lead SQL Server's optimizer to do a better job?

**Comment by oskarb** [comment]
The links reads:

>
> In a SELECT statement, always use an ORDER BY clause with the TOP clause.
> This is the only way to predictably indicate which rows are affected by
> TOP.
>
> Use OFFSET and FETCH in the ORDER BY clause instead of the TOP clause to
> implement a query paging solution. A paging solution (that is, sending
> chunks or "pages" of data to the client) is easier to implement using
> OFFSET and FETCH clauses. For more information, see ORDER BY Clause
> (Transact-SQL)
> <https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql>.
>
>
> Use TOP (or OFFSET and FETCH) instead of SET ROWCOUNT to limit the number
> of rows returned. These methods are preferred over using SET ROWCOUNT for
> the following reasons:
>
>    - As a part of a SELECT statement, the query optimizer can consider
>    the value of *expression* in the TOP or FETCH clauses during query
>    optimization. Because SET ROWCOUNT is used outside a statement that
>    executes a query, its value cannot be considered in a query plan.
>
>

I'm fairly sure the primary point they make is that OFFSET+FETCH is better
than the older style of implementing the equivalent of OFFSET and that
either is better than SET ROWCOUNT.

It would seem like it should be trivial for their optimizer to handle TOP x
and OFFSET 0 FETCH x in exactly the same way, and indeed surprising if it
didn't. Compare execution plans to confirm.


/Oskar



2018-03-23 13:07 GMT+00:00 gcesena <notifications@github.com>:

**Comment by oskarb** [comment]
Oh, and this is the bug tracker. Use the mailing lists for general discussion.
