### ISSUE TITLE
.net core using nhibernate

### ISSUE THREAD

**Issue by wmowm** [nhibernate/nhibernate-core#1629]
Help me! I am a fan of NHibernate. I hope to use it in .net core. I try to copy the latest project, but it cannot be used in .net core. It depends on some assembly of .net framework 4.6. Does NHibernate 5.1 support .net core? Can I provide some help?

**Comment by fredericDelaporte** [comment]
Yes NHibernate 5.1 supports .Net Core, you can see that on its [NuGet page](https://www.nuget.org/packages/NHibernate/) (deploy dependencies). If you are trying to use the binaries from Sourceforge instead, they contain only .Net Framework binaries. The [release notes](https://github.com/nhibernate/nhibernate-core/blob/5.1.0/releasenotes.txt) state Core support is provided through NuGet. You must get it through NuGet.

Please note by the way that you have reached here the bug tracking system. Ask for support on the [NHUsers groupe](https://groups.google.com/forum/#!forum/nhusers) instead.
