### ISSUE TITLE
Create UtcTicks and UtcDbTimestamp types

### ISSUE THREAD

**Issue by zeptoZB** [nhibernate/nhibernate-core#1631]
Because of the web and internationalization of applications a UtcTicks type would be very useful.

**Comment by fredericDelaporte** [comment]
Can you elaborate? This does not look as a standard thing... So it will not help much in such case.

**Comment by zeptoZB** [comment]
When using local date and time as the version field we have a full range of types: DateTime, DateTimeNoMs, LocalDateTime, Ticks, and DbTimestamp. For Web applications the date and time must be UTC, there is no exist all types. UtcTicks and UtcDbTimestamp are missing.

**Comment by fredericDelaporte** [comment]
`UtcDateTimeType` and `UtcDateTimeNoMsType` do exist.

`TicksType` and `DbTimestampType` do not have an UTC version. So you request an UTC version of those NHibernate types.
