### ISSUE TITLE
using plinq in nhibernate

### ISSUE THREAD

**Issue by EngRajabi** [nhibernate/nhibernate-core#1634]
usine plinq(parallel programing) for performance , in nhibernate .

**Comment by oskarb** [comment]
Hi,

This is is issue tracker for bug reports.

Please direct usage questions to the support forum "nhusers" (http://nhibernate.info/groups.html).

**Comment by oskarb** [comment]
If you DO intend this as a new feature request, please elaborate on how such a thing would be possible. NHibernate does not execute LINQ - it translates it to SQL and sends it to the database server system, while PLINQ, according to documentation (https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/parallel-linq-plinq), "is a parallel implementation of LINQ to Objects.".
