### ISSUE TITLE
SQLite not supported on CoreFX

### ISSUE THREAD

**Issue by jpenniman** [nhibernate/nhibernate-core#1638]
The SQLite driver currently looks for System.Data.Sqlite to load the ADO.Net provider.  However, the current SQLite driver for CoreFX is provided by Microsoft as Microsoft.Data.Sqlite.

**Comment by fredericDelaporte** [comment]
These are two distinct providers. `SQLite20Driver` will go on using `System.Data.SQLite`, and so will wait for this provider to be Core compatible before being usable wit .Net Core. (It seems they are thinking about it, [here](https://system.data.sqlite.org/index.html/tktview/5c89cecd1b4ccb384327).)

Integrating `Microsoft.Data.Sqlite` should be done as a distinct driver, preferably even as a distinct NuGet package in a distinct GitHub repository, as I have written in #1635:

> The way built-in dialects and drivers are included directly in NHibernate core is somewhat a legacy, from times where NuGet was not a de facto standard way of distributing software. And it has drawbacks, like drivers relying on reflection for avoiding taking a hard dependency on data providers of every database system. It also has the trouble of either being untested by the CI, or complicating further the CI by adding another database to test.
>
> So instead of contributing the dialect/driver directly into NHibernate core, you may consider contributing them as a separated project within its own GitHub repository, yielding a dedicated NuGet package which could then take direct dependencies on the data provider. There is some work ongoing for splitting drivers (not yet dialects) out of NHibernate: #626. You can have a look at this PR to see in which direction the dialect/driver area is currently heading.

**Comment by jpenniman** [comment]
I created a driver [MilestoneTG.NHibernate.Driver.Sqlite.Microsoft](https://www.nuget.org/packages/MilestoneTG.NHibernate.Driver.Sqlite.Microsoft/), but it looks like the Microsoft Driver isn't fully implemented.  For example, GetSchema() fails with a NotSupportedException when using the schema exporter.

It's too bad. We use SQLite for all our unit testing.

**Comment by fredericDelaporte** [comment]
Yes I have read that this driver was incomplete, further enforcing my opinion we should not "tweak" `SQLite20Driver` for using it under .Net Core/Standard.

**Comment by hazzik** [comment]
Also the Microsoft's driver does not support nested transactions (we use them to query IDs), and I guess many more issues not yet discovered.

**Comment by MonkAlex** [comment]
Today [system.data.sqlite](https://system.data.sqlite.org/index.html/tktview/5c89cecd1b4ccb384327) bug be closed. I need only system.data.sqlite (when released) or nhibernate update too?

**Comment by fredericDelaporte** [comment]
Provided they have not changed the assembly and classes naming, there will be no need of a change in NHibernate.

**Comment by jan-schubert** [comment]
Is there a way to find out all issues of the Microsoft driver?

**Comment by fredericDelaporte** [comment]
Well, write your own NHibernate driver using it, and try running the NHibernate tests suit with it.
