### ISSUE TITLE
Async WhenAll block reader

### ISSUE THREAD

**Issue by iceoz** [nhibernate/nhibernate-core#1642]
Hi, i have two querys on same table, one to list other to make a count. 

when i call separated, they works

var x = await itensList(idParent);
var z = await itensCount(idParent);
var h = new poco(x,y);

when i call together using whenAll, some times works and some times throws random exceptions

var x = itensList(idParent);
var z =  itensCount(idParent);
await Task.WhenAll(x,z);
var h = new poco(x.result, y.result);

Errors i get
GenericAdoException  could not execute query, some times on first some times on second
DbDataReader cant convert to NDataReader, 
Some times they cant get data from MetaData
Some times they close the connection

to build the factory i`m using fluentnhibernate

SessionFactory = Fluently.Configure()
                .Database(MsSqlConfiguration.MsSql2012.ShowSql().ConnectionString(Constantes.ConnectionString))
                .Mappings(m => m.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
                .BuildSessionFactory();

Every request i call dispose on transaction and session

**Comment by fredericDelaporte** [comment]
As written in [release notes](https://github.com/nhibernate/nhibernate-core/blob/5.1.0/releasenotes.txt#L241-L242):

> IO bound methods have gained an async counterpart. Not intended for parallelism, make sure to await each call before further interacting with a session and its queries.

Sessions are still not thread safe, and will remain not thread safe. Launching many tasks on the same session without awaiting each created task before creating the next one is calling for troubles.
