### ISSUE TITLE
Provide example for a .NET Core App serializing a session.

### ISSUE THREAD

**Issue by ngbrown** [nhibernate/nhibernate-core#1652]
From the release notes on .Net Core 2.0 framework compatibility:

>Binary serialization is not supported - the user shall implement serialization surrogates for System.Type,
>FieldInfo, PropertyInfo, MethodInfo, ConstructorInfo, Delegate, etc.

This issue replaces the pull request #1425 as a direction was chosen to not provide in-the-library support for session serialization on the new frameworks.  This is probably for the best as the pull-request was fairly invasive.

Application level support using serialization surrogates will be more elegant, but an example implementation, and tests, of those surrogates would certainly help.

If your scenario actually needs this support, and you want to migrate to dotnet, then this is the issue to vote on.

**Comment by hazzik** [comment]
@jrgcubano commented [18 April 2018](https://github.com/nhibernate/nhibernate-core/pull/1425#issuecomment-382032294):

> @ngbrown Hi. I do not know if it will give you any value, but on the FluentNHibernate side we have finished using [serialization surrogates](https://github.com/FluentNHibernate/fluent-nhibernate/blob/master/src/FluentNHibernate/Infrastructure/NetStandardSerialization.cs) for our [cloner ](https://github.com/FluentNHibernate/fluent-nhibernate/blob/68b889a6ad60e6e38b31c071f2b6967af5097fa3/src/FluentNHibernate/Utils/Extensions.cs#L69)
>
> Thanks in advance for the amazing work guys!

**Comment by hazzik** [comment]
@ngbrown @fredericDelaporte I was playing with the serialization surrogates and got the resulting code very similar to the mentioned one.

I have a plan to include this code into NHibernate codebase. The temptation is to include the surrogates into the [`SerializationHelper`](https://github.com/nhibernate/nhibernate-core/blob/1545d8a4965bd20e3d746fd2a020a46423fea353/src/NHibernate/Util/SerializationHelper.cs) class. However it is not used anywhere in the core at the moment. 

Alternative option is to move `SerializationHelper` class (+surrogates) to the tests project (and update the test code to use it instead of bare `BinaryFormatter`). 

Also, there is a `SerializableType` which uses bare `BinaryFormatter`. If the surrogates end up in the main codebase, shall we use them in `SerializableType`?

**Comment by hazzik** [comment]
I don't see how it is possible to configure the `SerializableType`. Are we talking about the same? I'm talking about [that one](https://github.com/hazzik/nhibernate-core/blob/469d79f8d23b1d0ea3118b945b623a7383c7ab57/src/NHibernate/Type/SerializableType.cs).

**Comment by fredericDelaporte** [comment]
Yes, the same. (I had already updated your message with another link to it.) It would be a system wide configuration, through a static property or method for supplying either a binary formatter factory or a surrogate selector factory.

**Comment by fredericDelaporte** [comment]
#1693 adds surrogates to [`NHibernate.Util.SerializationHelper`](https://github.com/nhibernate/nhibernate-core/blob/a407afba873ef168a6808e5d4c950bc136206279/src/NHibernate/Util/SerializationHelper.Surrogates.cs#L245), when not under .Net Framework.

They are used in the test project, like here:

https://github.com/nhibernate/nhibernate-core/blob/a407afba873ef168a6808e5d4c950bc136206279/src/NHibernate.Test/CfgTest/ConfigurationSerializationTests.cs#L34-L41

In case additional surrogates are needed, it can be done like this:

https://github.com/nhibernate/nhibernate-core/blob/a407afba873ef168a6808e5d4c950bc136206279/src/NHibernate.Test/Legacy/FooBarTest.cs#L2831-L2846

**Comment by fredericDelaporte** [comment]
> I don't see how it is possible to configure the `SerializableType`.

There is not only the static solution. It can also implement [`IParameterizedType`](https://github.com/nhibernate/nhibernate-core/blob/5.1.2/src/NHibernate/UserTypes/IParameterizedType.cs), like the `DateType` (although this specific case is now obsolete and is the last in NHibernate, other cases being tests).
