### ISSUE TITLE
Future queries not executed if no support for multiple queries

### ISSUE THREAD

**Issue by StormimOn** [nhibernate/nhibernate-core#1663]
NHibernate 5.X did change a little the Future extensions methods.
This cause a regression if there is no support for multiple queries, because in some scenarios the future queries won't be called.

For example

```c#
var query = Session.QueryOver<ParentObject>()....Future<ParentObject>();
Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollection1)....Future<ParentObject>();
Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollection2)....Future<ParentObject>();
...
Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollectionN)....Future<ParentObject>();

var result = query.SingleOrDefault();
```

In this case the queries fetching childs collections won't be called. 
With NH 3.X the `.Future()` would react like a `.List()` so there was no problem.

**Comment by fredericDelaporte** [comment]
Well, this is indeed a missing breaking change in release notes. But it has been done on purpose, see [here](https://github.com/nhibernate/nhibernate-core/pull/642#discussion_r121978225).

> This also adjusts a "detail": previous implementation was causing an immediate execution of the query in case of lack of multiple query support, contrary to what do FutureValue. Now it will be delayed too, so a discarded future query will not have its query run at all when multiple queries are not supported, it will be run only if the future query is actually enumerated.

So the code above should be changed to:

```c#
var query = Session.QueryOver<ParentObject>()....Future<ParentObject>();
var childQueries = new List<IFutureEnumerable<ParentObject>>();
childQueries.Add(Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollection1)....Future<ParentObject>());
childQueries.Add(Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollection2)....Future<ParentObject>());
...
childQueries.Add(Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollectionN)....Future<ParentObject>());

// Using the IFutureEnumerable directly as an IEnumerable is deprecated.
var result = query.GetEnumerable().SingleOrDefault();

// When Future are actually supported by the data provider, this code will be no-op.
// Otherwise it is mandatory for getting the children futures actually executed.
foreach(var cq in childQueries)
{
    cq.GetEnumerable();
}
```

By the way I guess this code is not using `FutureValue` then `Value` and use `Future` then `SingleOrDefault` instead because `FutureValue` was already working that way, never being immediately executed, and ending up not executed at all in case of lack of Future support.

**Comment by StormimOn** [comment]
Thanks for the fast answer.
I  did try your code, but the children futures are not executed when only calling the `.GetEnumerable()`
I need to add a call to a method which enumerate the result, like `.GetEnumerable().Any()`

I also found a solution about making your own driver so you can create cursors (Oracle) to manage multi queries.

**Comment by fredericDelaporte** [comment]
Indeed, `GetEnumerable` is implemented as an iterator, which causes it to be no-op until the iteration starts actually... This is a bug, it contradicts its purpose.

> I also found a solution about making your own driver so you can create cursors (Oracle) to manage multi queries.

This sounds even better for your case. If the implementation works well, it could be contributed into NHibernate Oracle drivers.

**Comment by StormimOn** [comment]
This is the solution I did try and it works well in my case.
https://stackoverflow.com/questions/10046461/nhibernate-multi-query-futures-with-oracle/14175635#14175635

**Comment by fredericDelaporte** [comment]
So, as of 5.0.x and 5.1.x, this is an known behavior, closing this issue. Nonetheless, for 5.2.0, I propose some refactoring in #1666 which will remove this discrepancy in Future behavior between data providers supporting multi-queries and those not supporting them.

**Comment by bahusoid** [comment]
@fredericDelaporte It seems I'm pretty late but I found current implementation is quite unexpected.
You justified your changes here https://github.com/nhibernate/nhibernate-core/pull/642#discussion_r121978225

>This also adjusts a "detail": previous implementation was causing an immediate execution of the query in case of lack of multiple query support, contrary to what does FutureValue. Now it will be delayed too, so a discarded future query will not have its query run at all when multiple queries are not supported, it will be run only if the future query is actually enumerated.

But it is my understanding the old behavior (immediate query execution) was implemented  exactly to support "fetch only" queries - results are ignored for such quires as seen in issue example.
```
var query = Session.QueryOver<ParentObject>()....Future<ParentObject>();
Session.QueryOver<ParentObject>().Fetch(x => x.ChildCollection1)....Future<ParentObject>();
```

And it's a common practice to have such "fetch only" queries  and I believe they are used quite extensively. For instance check example in [reference documentation](http://nhibernate.info/doc/nh/en/index.html#querylinq-fetching):
```
IQueryable<Cat> oldCatsQuery =
    session.Query<Cat>()
        .Where(c => c.BirthDate.Year < 2010);
oldCatsQuery
    .Fetch(c => c.Mate)
    .FetchMany(c => c.Kittens)
    .ToFuture();
IList<Cat> oldCats =
    oldCatsQuery
        .FetchMany(c => c.AnotherCollection)
        .ToFuture()
        .GetEnumerable()
        .ToList();
```

So with "delayed execution" those queries are never executed - so you have unexpected N+1 issue after upgrade. And suggested fix with explicit enumeration IMHO looks  like a hack and makes code quite ugly (considering that fetching queries might not be scoped to single method).

**Comment by hazzik** [comment]
As I understand this will be fixed in 5.2, isn’t it?

**Comment by bahusoid** [comment]
Yeah. Indeed. Sorry for the noise - somehow I misunderstand the purpose of the changes in 5.2

**Comment by fredericDelaporte** [comment]
It may not be simple to revert, because the old behavior was implemented by breaking some expectation of the Linq provider, like returning `List<T>` where it was expecting something implementing `IDelayedValue`.

Better back-port #1666 instead.

**Comment by hazzik** [comment]
>Better back-port #1666 instead.

Not sure... it might be too much for a patch release...
