### ISSUE TITLE
Binary xor treated as pow with PostgreSQL

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#1673]
A HQL query using an exclusive binary or (`bxor` or `^`) will result in an exponentiation with PostgreSQL.

The `Dialect` class registers `bxor` as `^`, and this is not overridden in PostgreSQL dialect. But for PostgreSQL, `^` is an exponentiation, xor is `#`.

(Discovered while adding tests in #1670.)

**Comment by fredericDelaporte** [comment]
I was thinking of doing the opposite: merging the thread safety issue (#1670) in 5.1.x (or even 5.0.x) while letting this point fixed in 5.2 only. This was because this fix can be a breaking changes for those targeting only PostgreSQL and falsely believing,  due to this bug, that `^` was intended for exponentiation.

**Comment by hazzik** [comment]
Shall I revert the commit?

**Comment by hazzik** [comment]
Cherry picked the commit.

**Comment by fredericDelaporte** [comment]
I was willing to do this only once #1670 would have been merged to master, in order to re-enable the bitwise functions tests for PostgreSQL.

**Comment by hazzik** [comment]
I realised that after I've merged the commit. So... the re-enabling part has to go as a separate commit.

**Comment by fredericDelaporte** [comment]
Or why not when merging 5.1.x.
But in fact I was thinking about adding also a SQLite xor implementation based on a template, once 5.1.x would have been merged. So enabling Postgres could be done "by the way" in that upcoming PR.
