### ISSUE TITLE
Dialect.SupportsRowValueConstructorSyntax leads to error if set to true

### ISSUE THREAD

**Issue by breglerj** [nhibernate/nhibernate-core#1676]
The two test cases NH2294 and NH2394 fail if a dialect sets `SupportsRowValueConstructorSyntax` to `true`. 

The root cause of the error originates from `NHibernate.Hql.Ast.ANTLR.SqlGenerator.Out(IASTNode)`. The method assumes that the ID for back tracking is a `SimpleValue` which is not true for these tests. Hence the call to `parameterNode.HqlParameterSpecification.GetIdsForBackTrack(sessionFactory).Single()` fails with an exception.

**Comment by bahusoid** [comment]
It's been fixed in 5.3 with #2159
