### ISSUE TITLE
NHibernate 5.1 not supporting oracle11g

### ISSUE THREAD

**Issue by nsreddy1986** [nhibernate/nhibernate-core#1695]
When used in dotnet core project NHibernate5.1 is not supporting Oracle (11g). Getting below exception.
Exception:
The DbCommand and DbConnection implementation in the assembly Oracle.DataAccess could not be found. Ensure that the assembly Oracle.DataAccess is located in the application directory or in the Global Assembly Cache. If the assembly is in the GAC, use <qualifyAssembly/> element in the application configuration file to specify the full name of the assembly.
Configuration used:
Configuration.DataBaseIntegration(db =>
{
					
	db.ConnectionString = @"User Id=fcscompsys;Password=fcscompsys;Data Source=focagl";
					db.Dialect<Oracle10gDialect>();
					db.Driver<OracleDataClientDriver>();
					db.KeywordsAutoImport = Hbm2DDLKeyWords.None;
})

**Comment by hazzik** [comment]
Oracle.DataAccess provider (OracleDataClientDriver) does not support .NET core. Oracle have a managed version of the ADO.NET provider currently in beta which will support .NET Core. Please install 
[Oracle.ManagedDataAccess.Core](https://nuget.org/packages/Oracle.ManagedDataAccess.Core) nuget package and use `OracleManagedDataClientDriver`.

Alternatively you can use unofficial [System.Data.OracleClient](https://nuget.org/packages/System.Data.OracleClient) package and `OracleClientDriver`
