### ISSUE TITLE
Getting "New transaction not allowed..." using MS SQL connection using multiple threads.

### ISSUE THREAD

**Issue by quintonn** [nhibernate/nhibernate-core#1701]
I found an issue in a website of mine where if I load the site in one browser and perform some tasks that might take a while and then open my site in another browser and just load the home page (which calls a DB function), i get this error:

> New transaction is not allowed because there are other threads running in the session.

I found that this error does not occur when I use SQlite.

I created a test application to simulate this:, and it can be found [here](https://github.com/quintonn/NHibernateLockTest)

To give a bit more context, my website has code in the constructor of the controller to load some settings, hence the db access on every request. 

I'm doing it as users might change settings from time to time so i don't want to do it once off only.

I guess i should optimize this, but there is still a problem when running multiple threads on the same database using MS SQL. 

I'm hoping i need to add a property to my connection string or something simple.

**Comment by fredericDelaporte** [comment]
Your test program creates a single connection and shares it among threads. Sql Server connections are not thread safe and must not be shared among threads. Each web request must use its own connection. By the way, the error you receive comes from the connection, and is not related to NHibernate in any way.

The simplest way to solve this is to cease supplying your own connection to NHibernate and just configure NHibernate with the appropriate connection string.

**Comment by quintonn** [comment]
The connection...
Ah thanks. I've removed it and the error goes away.
Makes sense.
I'm not sure why i have that there as it's not the default when looking at NHibernate docs.

Thank you for assisting.
