### ISSUE TITLE
probable I/O race condition detected while copying memory

### ISSUE THREAD

**Issue by erezasu** [nhibernate/nhibernate-core#1715]
on my project im having this error on the event viewer, the extended error description is:
"probable I/O race condition detected while copying memory.
The i/o package is not thread safe by default. in multithreaded applications,
a stream must be accessed in a thread safe-way ..."

also i get a warning of system.IndexOutOfRangeException: probable i/o race condition detected
while copying memory...
at system.buffer.internalblockcopy...
...
...
...
at nhibernate.loader.loader.dolist...

does anyone have any ideas why it happen or any solution to this issue?

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

(Your are likely sharing a NHibernate session instance between many threads, or calling async methods without awaiting them. The session is not thread safe and must be used by a single thread.)

**Comment by pavsh** [comment]
Hi, 
why you consider it as a usage problem?

**Comment by fredericDelaporte** [comment]
Also duplicate #1194.
