### ISSUE TITLE
About .Net Core2.x configuration issues

### ISSUE THREAD

**Issue by jiaxiang8756** [nhibernate/nhibernate-core#1717]
I would like to ask,. Net core how to use Nhibernate? Must I use web.config as a configuration file?

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

But you can also find some elements of answer on a similar issue similarly closed: #1697.
