### ISSUE TITLE
DateTime + timestamptz + dynamic-update = always update the field even if the value didn't change.

### ISSUE THREAD

**Issue by MichaelBuen** [nhibernate/nhibernate-core#1721]
This is the continuation of the [problems](https://github.com/nhibernate/nhibernate-core/issues/1708) I encountered with DateTimeOffset/DateTime + timestamptz/timestamp combinations.

Saving UTC date using DateTime to a timestamptz field, it works with a work-around. However, the work-around causes UPDATE to a timestamptz field even if the value didn't change.

Is there a fix to prevent the UPDATE on unchanged property value?

# Here are the three combinations I have tried:

### TL;DR

Without work-around

|                               | Write | Read 
| ----------------------------- | ------| ---- 
| DateTimeOffset + timestamptz  |   OK  |  👎  
| DateTime + timestamptz        |   👎  |  OK  
| DateTime + timestamp          |   👎  |  👎  

With work-around*

|                               | Write | Read  | Notes                                                                                            
| ----------------------------- | ----- | ----- | -------------------------------------------------------------------------------------------------
| DateTimeOffset + timestamptz  |   OK  |  👎   | no work-around for read
| DateTime + timestamptz        |   OK* |  OK   | with dynamic-update, even if the field's value didn't change, NHibernate still updates the field 
| DateTime + timestamp          |   OK  |  OK*  | timestamp is not as convenient as timestamptz when looking at other countries' time              

### TL;Please Read the work-arounds:

**1. DateTimeOffset + timestamptz = Write fidelity OK. Read not OK, would cause cast exception error.**

**2. DateTime + timestamptz = Read fidelity OK. Write fidelity not OK.**

2018-05-04T17:37:00.000Z input is incorrectly persisted as 2018-05-04 17:37:00+08, which is equivalent to 2018-05-04 09:37:00+00, when written as Zulu format is 2018-05-04T09:37:00.000Z, which is not the same value from input anymore.

Would need this work-around for **Write***:

```c#
public class NpgsqlDriverExtended : NHibernate.Driver.NpgsqlDriver
{                
    protected override void InitializeParameter(DbParameter dbParam, string name, SqlType sqlType)
    {            
        base.InitializeParameter(dbParam, name, sqlType);
                    
        if (sqlType.DbType == System.Data.DbType.DateTime)
        {
            dbParam.DbType = System.Data.DbType.DateTimeOffset;
        }
    }
}
```

With the work-around, 2018-05-04T17:37:00.000Z input would be correctly persisted as 2018-05-05 01:37:00+08, which is equivalent to 2018-05-04 17:37:00+00, written in Zulu format 2018-05-04T17:37:00.000Z, same value as the input.

With the work-around above, DateTime + timestamptz is almost perfect. There's a problem with dynamic-update though, even if the value of a DateTime property didn't change, NHibernate would still issue an UPDATE statement on the timestamptz field. [Test code](#test-code) at the bottom of this post.

**3. DateTime + timestamp.**

2018-05-04T17:37:00.000Z input is persisted as 2018-05-04T17:37:00

And then it would be read back as 2018-05-04T17:37:00, which does not resolve to same value as input. 

For example in +08:00 timezone, 2018-05-04T17:37:00 is interpreted in NHibernate as 2018-05-04 17:37:00+08, which is equivalent to 2018-05-04 09:37:00+00, written in Zulu format 2018-05-04T09:37:00.000Z, which is not the same as the input value anymore 2018-05-04T17:37:00.000Z.

Would need this work-around for **Read***:

```c#
static void Mapper_BeforeMapProperty(
    NHibernate.Mapping.ByCode.IModelInspector modelInspector,
    NHibernate.Mapping.ByCode.PropertyPath propertyPath,
    NHibernate.Mapping.ByCode.IPropertyMapper propertyMapper
)
{
    string postgresFriendlyName = propertyPath.ToColumnName().ToLowercaseNamingConvention();

    propertyMapper.Column(postgresFriendlyName);            

        System.Type st = propertyPath.LocalMember.GetPropertyOrFieldType();

    if (st == typeof(System.DateTime) || st == typeof(System.DateTime?))
    {
        propertyMapper.Type<NHibernate.Type.UtcDateTimeType>();
        // propertyMapper.Type(NHibernate.NHibernateUtil.UtcDateTime);
    }
}
```

With the work-around above, 2018-05-04T17:37:00 timestamp would be read back as 2018-05-04T17:37:00Z, same value as the input.

<a id="test-code"></a>
# Test code

DateTime + timestamptz + with and without work-around

```c#
namespace TestNH
{
    using System;   
    using NHibernate.Cfg;

      
    class Program
    {
        // change this to true to see the unintended UPDATE 
        public static bool withWorkAround = false; problem


        static async System.Threading.Tasks.Task Main(string[] args)
        {

            var cfg = new NHibernate.Cfg.Configuration();

            cfg.DataBaseIntegration(c =>
            {                
                if (withWorkAround)
                {
                    c.Driver<NpgsqlDriverExtended>();
                }
                else 
                {
                    c.Driver<NHibernate.Driver.NpgsqlDriver>();    
                }

                c.Dialect<NHibernate.Dialect.PostgreSQLDialect>();

                c.ConnectionString = "Server=localhost; Port=5432; Database=test; User Id=postgres; Password=opensesame93";

                c.LogFormattedSql = true;
                c.LogSqlInConsole = true;
            });


            var mapper = new NHibernate.Mapping.ByCode.ModelMapper();
            mapper.AddMapping<TheTimeMapping>();

            var mapping = mapper.CompileMappingForAllExplicitlyAddedEntities();

            cfg.AddMapping(mapping);

            var sf = cfg.BuildSessionFactory();


            var utcString = "2018-05-04T17:37:00.0000000Z";

            var utc = DateTime.Parse(utcString).ToUniversalTime();

            var zuluFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'";

            var utcZuluFormat = utc.ToString(zuluFormat);


            int savedId;
            using (var session = sf.OpenSession())
            {                
                Console.WriteLine($"utc value is {utc} kind is {utc.Kind}");

                var t = new Test
                {
                    UtcString = utcZuluFormat,
                    TheTimestampTz = utc,
                    WithWorkAround = Program.withWorkAround
                };

                await session.PersistAsync(t);
                await session.FlushAsync();

                savedId = t.Id;                
            }

            DateTime readUtc;
            using (var session = sf.OpenSession())
            {
                var t = await session.GetAsync<Test>(savedId);

                readUtc = t.TheTimestampTz;

                t.UtcString = utcZuluFormat;
                t.TheTimestampTz = utc;

                await session.PersistAsync(t);
                await session.FlushAsync();                                              
            }


            var readUtcZuluFormat = readUtc.ToString(zuluFormat);


            Console.WriteLine($@"
                With work-around? {withWorkAround}. 


                {nameof(utc)} zulu:      {utcZuluFormat}
                {nameof(readUtc)} zulu:  {readUtcZuluFormat}

                Both resolves to same UTC value? {readUtcZuluFormat == utcZuluFormat} 

                {nameof(utc)}     {utc}
                {nameof(readUtc)} {readUtc}

                Both resolves to same value? {readUtc == utc} 
            ");

        }
    }

    public class Test
    {
        public virtual int Id { get; set; }

        public virtual string   UtcString { get; set; }
        public virtual DateTime TheTimestampTz { get; set; }

        public virtual bool WithWorkAround { get; set; }
    }

    public class TheTimeMapping : NHibernate.Mapping.ByCode.Conformist.ClassMapping<Test>
    {
        public TheTimeMapping()
        {
            Id(x => x.Id, id =>
            {
                id.Generator(
                    NHibernate.Mapping.ByCode.Generators.Sequence,
                    generatorMapping => generatorMapping.Params(new { sequence = "test_id_seq" })
                );
            });

            Property(p => p.UtcString, cm =>
            {
                cm.Column("utc_string");
            });

            Property(p => p.TheTimestampTz, cm =>
            {
                cm.Column("the_timestamptz");
                cm.Type<NHibernate.Type.UtcDateTimeType>();
                // cm.Type(NHibernate.NHibernateUtil.UtcDateTime); // Same as previous line?
            });

            Property(p => p.WithWorkAround, cm => cm.Column("with_work_around"));

            DynamicUpdate(true);
            SelectBeforeUpdate(true);            
        }
    }



    public class NpgsqlDriverExtended : NHibernate.Driver.NpgsqlDriver
    {
        // this gets called when an SQL is executed
        protected override void InitializeParameter(
            System.Data.Common.DbParameter dbParam, 
            string name, 
            NHibernate.SqlTypes.SqlType sqlType
        )
        {
            base.InitializeParameter(dbParam, name, sqlType);

            if (Program.withWorkAround)
            {
                // Solved this problem: 
                // https://github.com/nhibernate/nhibernate-core/issues/1708#issuecomment-392338162
                if (sqlType.DbType == System.Data.DbType.DateTime)
                {
                    dbParam.DbType = System.Data.DbType.DateTimeOffset;
                }
            }
        }
    }

}
```

Test table
```sql
-- drop table test;

create table test
(
    id serial primary key,          
    utc_string text not null,
    with_work_around boolean not null,  
    the_timestamptz timestamptz not null
);
```

Output, no work-around:
```c#
utc value is 05/04/2018 17:37:00 kind is Utc
NHibernate: 
    select
        nextval ('test_id_seq')
NHibernate: 
    INSERT 
    INTO
        Test
        (utc_string, the_timestamptz, with_work_around, Id) 
    VALUES
        (:p0, :p1, :p2, :p3);
    :p0 = '2018-05-04T17:37:00.000Z' [Type: String (0:0:0)], :p1 = 2018-05-04T17:37:00.0000000Z [Type: DateTime (0:0:0)], :p2 = False [Type: Boolean (0:0:0)], :p3 = 1 [Type: Int32 (0:0:0)]
NHibernate: 
    SELECT
        test0_.Id as id1_0_0_,
        test0_.utc_string as utc2_0_0_,
        test0_.the_timestamptz as the3_0_0_,
        test0_.with_work_around as with4_0_0_ 
    FROM
        Test test0_ 
    WHERE
        test0_.Id=:p0;
    :p0 = 1 [Type: Int32 (0:0:0)]

                With work-around? False. 


                utc zulu:      2018-05-04T17:37:00.000Z
                readUtc zulu:  2018-05-04T17:37:00.000Z

                Both resolves to same UTC value? True 

                utc     05/04/2018 17:37:00
                readUtc 05/04/2018 17:37:00

                Both resolves to same value? True 

```

Output, with work-around:
```c#
utc value is 05/04/2018 17:37:00 kind is Utc
NHibernate: 
    select
        nextval ('test_id_seq')
NHibernate: 
    INSERT 
    INTO
        Test
        (utc_string, the_timestamptz, with_work_around, Id) 
    VALUES
        (:p0, :p1, :p2, :p3);
    :p0 = '2018-05-04T17:37:00.000Z' [Type: String (0:0:0)], 
    :p1 = 2018-05-04T17:37:00.0000000Z [Type: DateTimeOffset (0:0:0)], 
    :p2 = True [Type: Boolean (0:0:0)], :p3 = 2 [Type: Int32 (0:0:0)]
NHibernate: 
    SELECT
        test0_.Id as id1_0_0_,
        test0_.utc_string as utc2_0_0_,
        test0_.the_timestamptz as the3_0_0_,
        test0_.with_work_around as with4_0_0_ 
    FROM
        Test test0_ 
    WHERE
        test0_.Id=:p0;
    :p0 = 2 [Type: Int32 (0:0:0)]
NHibernate: 
    UPDATE
        Test 
    SET
        the_timestamptz = :p0 
    WHERE
        Id = :p1;
    :p0 = 2018-05-04T17:37:00.0000000Z [Type: DateTimeOffset (0:0:0)], :p1 = 2 [Type: Int32 (0:0:0)]

                With work-around? True. 


                utc zulu:      2018-05-04T17:37:00.000Z
                readUtc zulu:  2018-05-05T01:37:00.000Z

                Both resolves to same UTC value? False 

                utc     05/04/2018 17:37:00
                readUtc 05/05/2018 01:37:00

                Both resolves to same value? False 

```

Output, database:
```sql
test=# select id, utc_string, with_work_around, the_timestamptz, the_timestamptz at time zone 'UTC' as at_utc from test;
-[ RECORD 1 ]----+-------------------------
id               | 1
utc_string       | 2018-05-04T17:37:00.000Z
with_work_around | f
the_timestamptz  | 2018-05-04 17:37:00+08
at_utc           | 2018-05-04 09:37:00
-[ RECORD 2 ]----+-------------------------
id               | 2
utc_string       | 2018-05-04T17:37:00.000Z
with_work_around | t
the_timestamptz  | 2018-05-05 01:37:00+08
at_utc           | 2018-05-04 17:37:00

```

**Comment by fredericDelaporte** [comment]
Just some quick notes: 

- What happens with "DateTimeOffset + timestamptz" was already discussed in #1708 and is due to this db type being read as a .Net `DateTime` by the data provider.
- What happens with "DateTime + timestamp" is expected behavior. What you call a workaround is indeed a fix of your mappings. They should maps it as an `utcdatetime` for it to be returned with `Kind` UTC. This is because the NHibernate `datetime` type semantic is to make no assumption on the received date kind and leave it untouched, as returned by the data provider.
- What happens with "DateTime + timestamptz" was, for most of it, also already discussed in #1708 and is due to the db type special semantic. Now the "ghost update" occurring on it is due to another reason.

This report has a bit too much information. It should focus on only one subject. 

About the "ghost update", why are you calling `Persist` on an already persisted entity? This causes your test to be semantically invalid.
But anyway, the trouble is that the test re-assign a value which is not identical to the read one: the read one is in local time, due to `timestamptz` special semantic, while the assigned one is in utc. That causes the two values to be considered different, even if they represent the same time from your point of view. (That depends on an assumption about the time zone.)
NHibernate should not ever try to compare utc and local `DateTime` for equality, because in time zones having "daylight saving" time shifts, some cases cannot be resolved.

**Comment by MichaelBuen** [comment]
Sorry about the too much information. Just wanted to itemized all the possible and not possible options when handling UTC in NHibernate + Postgres

> About the "ghost update", why are you calling Persist on an already persisted entity?

I forgot to remove the Persist in copy-pasted test code. On an actual code, this is how UPDATE is made, there's no Persist.

```c#
[HttpPut("{id}")]
public async Task Put(int id, [FromBody] JobFormDto dto)
{
    using (var session = sessionFactory.OpenSession())
    using (var tx = session.BeginTransaction())
    {
        var job = await session.GetAsync<Ddd.JobDomain.Job>(id);                

        job.UpdateJobPost(session, this.UserId, dto);

        await tx.CommitAsync();
    }
}

public void UpdateJobPost(ISession session, int loggedUserId, JobFormDto dto)
{                          
    this.Position        = dto.Position;
    this.Description     = dto.Description;
        
    this.Schedule        = dto.Schedule;
    this.Duration        = dto.Duration;
    this.DurationType    = session.Load<DurationType>(dto.DurationTypeFk);

    this.Pay             = dto.Pay;
    this.IsPayNet        = dto.IsPayNet;

    ...
}

```

Is there no chance to use DateTime + timestamptz without causing "ghost update"? It looks like that it is so limiting that DateTime + timestamp is the only option when it comes to NHibernate + Postgres UTC handling.

**Comment by fredericDelaporte** [comment]
Your test code still does change the value from a Local one to an UTC one. This is the root cause of the ghost update. Do not do that change for avoiding the update. So either setup your solution for reading the date in UTC too, or do not rewrite it in UTC when the value is the "same" from your point of view.

**Comment by MichaelBuen** [comment]
I'm not sure if my test code approximates what happens during serialization/deserialization of UTC by ASP.NET Core and NHibernate. So in terms of sameness of value, I'm not sure if my test code writing/reading mimics what happens with ASP.NET Core and NHibernate combo.

On actual code, I don't change the value of UTC I received from deserialized DateTime. As much as possible I avoid messing with what the frameworks (e.g., NHibernate, ASP.NET Core) provides out-of-the-box for the dev. The datetime picker component sends its date as UTC value, then ASP.NET Core deserialize it to a DTO with with a DateTime property. Then I just persist it to timestamptz using NHibernate, I didn't even make any adjustments/rewrite of the DateTime value I received from ASP.NET Core and sent to NHibernate, but alas, the persisted value is not the same as the UTC value sent by the datepicker, even if I set the Postgres' timezone to UTC. The work-around fixes the UTC persistence inconsistency of DateTime + timestamptz, unfortunately it cannot prevent the "ghost update" problem.

If not for "ghost update", DateTime + timestamptz + work-around is the perfect way to persist UTC date.

> So either setup your solution for reading the date in UTC too, or do not rewrite it in UTC when the value is the "same" from your point of view.

I'm leaning on the first option. I really want to find out how to avoid the "ghost update" problem of DateTime + timestamptz while saving the UTC as-is. Are there any documentations in NHibernate that documents/solves this problem? Any help would be appreciated, thanks :)

**Comment by MichaelBuen** [comment]
I think I should stop looking at NHibernate for the problem. Looks like I need to find a hook/API in ASP.NET Core to make it deserialize UTC value to DateTime as UTC kind, not local.

```c#
   [HttpGet]
   public ActionResult<string> Get([FromQuery] DateTime theDt)
   {
      return $"{theDt} kind: {theDt.Kind}";
    }
```

![image](https://user-images.githubusercontent.com/1811636/40802683-ec0f61d8-6548-11e8-8589-9eb698127b13.png)

**Comment by MichaelBuen** [comment]
Ah for POST, it deserializes as kind Utc. I'll just continue tomorrow, 3AM already

**Comment by fredericDelaporte** [comment]
The root of the trouble is still the usage of `timestamptz` for storing a UTC date, while it yields it back as local.

This is not a NHibernate issue, so please do not add activity here.
