### ISSUE TITLE
Query cache always missed in session having altered the entities

### ISSUE THREAD

**Issue by igitur** [nhibernate/nhibernate-core#1730]
Refer to https://hibernate.atlassian.net/browse/HHH-5210

When using a query which is marked as cacheable, NHibernate caches both the query with the session timestamp, and its last invalidation timestamp (due to an update or save). When retrieving a query from the cache, it first compares the timestamp of the cached query with the last invalidation timestamp (`UpdateTimestampsCache.IsUpToDate()`):

```c#
if ((long) lastUpdate >= timestamp)
{
	return false;
}
```

The problem is that the timestamp for the current session, used for caching query, is always lower than invalidation's timestamp if the entities were altered in the session, even prior to caching the query and in a dedicated transaction. This causes the result of the method to be always `false`, discarding the cache results and hitting the database forever with that session.

**Comment by fredericDelaporte** [comment]
Analyzing a bit more the issue, it looks to me it happens only if the entities are modified/persisted in the same session in a dedicated transaction prior to querying them still in the same session. Am I wrong?

**Comment by igitur** [comment]
Yes, that's how I understand it too.

**Comment by fredericDelaporte** [comment]
I have updated your description for describing more accurately the trouble. (But it is now perhaps a bit less straightforward to understand.)

**Comment by igitur** [comment]
No problem. I grabbed the title and body of the top post directly from https://hibernate.atlassian.net/browse/HHH-5210
