### ISSUE TITLE
Set IUserType by convention

### ISSUE THREAD

**Issue by EamonHetherton** [nhibernate/nhibernate-core#1735]
I am using a custom type in my code to store small base 10 decimal values without the memory overhead of System.Decimal (4 bytes vs 16 bytes).
```
public struct SmallDecimal : IEquatable<SmallDecimal>, IEquatable<decimal>, IComparable, IComparable<SmallDecimal>
    {...}
```
I also have a custom IUserType that maps this type.

I am using ConventionModelMapper to set up a number of conventions including one that inspects the property type and sets the appropriate IUserType
```
mapper.BeforeMapProperty += (mi, propertyPath, map) =>
{
    var propertyType = propertyPath.LocalMember.GetPropertyOrFieldType();
    if (propertyType.Equals(typeof(SmallDecimal)) || propertyType.Equals(typeof(SmallDecimal?)))
    {
        map.Type(typeof(SmallDecimalUserType), null);
    }
};
```
This works correctly as long as I explicitly map every property that is SmallDecimal, but what I want is to be able to set up some kind of convention such that any property of type SmallDecimal is automatically mapped as a property with a type SmallDecimalUserType without the explicit mapping. (I have a lot of properties across a lot of classes that are currently automatically mapped as decimal here that I want to change to SmallDecimal) 

At the moment, any property I do not explicitly map that has a type of SmallDecimal ends up mapped as a component.

I've never used fluent NHibernate but it appears that I could achieve the above with their UserTypeConvention.  

I'd rather stick with the native mapping-by-code Is there a parallel in mapping by code?

**Comment by EamonHetherton** [comment]
Ok, so as best I can infer what I need to do is to change the behavior of the `IsProperty(MemberInfo member)` method on the `IModelInspector` used in `ConventionModelMapper`.  

Two imediate problems here
1) `ConventionModelMapper` does not contain a constructor that takes an `IModelInspector` instead it always creates a new `SimpleModelInspector`
2) `SimpleModelInspector` implements `IModelInspector.IsProperty(MemberInfo member)` explicitly so I cannot derive from it to change this behavior, I would need to wrap it in a proxy class.

It doesn't seem controversial to change 1) but i'll continue to investigate how best to proceed to solve 2)

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

From your second comment it seems you also ask for some changes in NHibernate, but that is not clear.

Note that with #702 (NH v5.1) you can register/override default mappings from .Net types to NHibernate types.

Call `NHibernate.Type.TypeFactory.RegisterType` before building your configuration. It takes an `IType`, not an `IUserType`, so wrap it into `NHibernate.Type.CustomType`.

```c#
TypeFactory.RegisterType(
    typeof(SmallDecimal),
    new CustomType(typeof(YourUserType), parameters),
    TypeFactory.EmptyAliases);
```
(`parameters` should be null or empty if your type is not also an `IParameterizedType`.)

If you actually need changes to mapping by code, feel free to submit a PR.

**Comment by EamonHetherton** [comment]
Hi, thanks for the pointer for registering default type mappings, I've had a look and while it will help somewhat reduce the amount of code I put into the `mapper.BeforeMapProperty += (mi, propertyPath, map) =>` handler, it does not seem to work correctly for the string type if the mapped property has a length; I'm sure I'm probably doing something wrong but can't afford to spend the time to dig a lot deeper when I have a working solution using the `mapper.BeforeMapProperty += (mi, propertyPath, map) =>` handler.

This however does not help with the real issue which is that any non-system type that is not explicitly mapped is automatically mapped as a component.

```c#
public class TestEntity
{
	public int Id { get; set; }
	public SmallDecimal ImplicitMapping { get; set; }
	public SmallDecimal ExplicitMapping { get; set; }
}

public void TestMapping()
{
	TypeFactory.RegisterType(typeof(MappingTest.SmallDecimal), new CustomType(typeof(SmallDecimalUserType), null), TypeFactory.EmptyAliases);
	
	var mapper = new NH.Mapping.ByCode.ConventionModelMapper();
	mapper.Class<MappingTest.TestEntity>(map =>
	{
		map.Id(m => m.Id);
		map.Property(m => m.ExplicitMapping);
	});

	var mapping = mapper.CompileMappingForAllExplicitlyAddedEntities();

	var xml = mapping.AsString();

	Console.WriteLine(xml);
}
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<hibernate-mapping xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" namespace="MappingTest" assembly="MappingTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" xmlns="urn:nhibernate-mapping-2.2">
  <class name="TestEntity">
    <id name="Id" type="Int32" />
    <component class="SmallDecimal" name="ImplicitMapping" />
    <property name="ExplicitMapping" />
  </class>
</hibernate-mapping>
```

Ideally the code above should be able to produce the following mapping:
```xml
<?xml version="1.0" encoding="utf-8"?>
<hibernate-mapping xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" namespace="MappingTest" assembly="MappingTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" xmlns="urn:nhibernate-mapping-2.2">
  <class name="TestEntity">
    <id name="Id" type="Int32" />
    <property name="ImplicitMapping" />
    <property name="ExplicitMapping" />
  </class>
</hibernate-mapping>
```

**Comment by fredericDelaporte** [comment]
>  it does not seem to work correctly for the string type if the mapped property has a length

Yes, this is meant only for default mapping of a .Net type. As soon as you start specifying any type characteristic, it will not apply.

> any non-system type that is not explicitly mapped is automatically mapped as a component

I am not familiar with this part of NHibernate (auto-mapping by code), but in fact this looks to me as quite a sensible default behavior. Maybe there is a way to specify to the auto-mapper how to choose between mapping a class property as a mapping property or as a component, but I do not know. Anyway, this is not the right place to discuss this, please ask on [groups](http://nhibernate.info/groups.html) instead.
