### ISSUE TITLE
Question: how to query the Change tracker?

### ISSUE THREAD

**Issue by vdecristofaro** [nhibernate/nhibernate-core#1757]
I am really new to nhibernate. I am sorry if the Question seems Dumb.

In EF I can make a query like this one to ask the change tracker to give me all the modified or added entities in current transaction:
```
var domainEntities = ctx.ChangeTracker
                .Entries<Entity>()
                .Where(x => x.Entity.DomainEvents != null && x.Entity.DomainEvents.Any());
```
Is there any way to make the same query in Nhibernate? Is there any reference to study to improve my knowledge?

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage questions to the user groups:
http://nhibernate.info/groups.html

(Spoiler: there are no change trackers in NHibernate. There is instead a dirty checking mechanism which compares the state the entity was having at load time with the state it currently has. Each entity has an entry in session holding that state, or telling if it has been added/deleted. This is reachable through `ISession.GetSessionImplementation().PersistenceContext.EntityEntries`, which values are of type `NHibernate.Engine.EntityEntry` (no generic typing there, that part dates back to net10). But for loaded entities, you will be stuck: the dirty checking mechanism is not exposed, that would be up to you to compare the loaded state with the entity current state for knowing if they are dirty.)

**Comment by fredericDelaporte** [comment]
And the [NHibernate reference](http://nhibernate.info/doc/nhibernate-reference/index.html). (Reachable from [here](http://nhibernate.info/doc/index.html), where previous versions are also available.)
