### ISSUE TITLE
Index column gets ignored for inverse list

### ISSUE THREAD

**Issue by fubar-coder** [nhibernate/nhibernate-core#1766]
NHibernate creates the INSERT statements, but "forgets" to update the index column. I'll provide a PR for a unit test shortly.

**Comment by fredericDelaporte** [comment]
As seen on #1768, a collection mapped as `inverse` does not maintain anything: neither what it contains, nor the index of what it contains. Both are to be handled on the non-inverse side. For a many-to-one, it may be better to map it with `update="false"` and `insert="false"`, which would allow to keep the collection as non `inverse`.
