### ISSUE TITLE
Table mapping for UniqueColumn uses unstable GetHashCode() method

### ISSUE THREAD

**Issue by Scooletz** [nhibernate/nhibernate-core#1769]
The snippet below presents the way how `Table` class generates `UniqueColumn` name. This value is used in several code paths, like `CreateForeignKey` and/or generating an unique column name itself. 

https://github.com/nhibernate/nhibernate-core/blob/c4fb3dc25f90d2370ca26eaaf4e5cb07bddce431/src/NHibernate/Mapping/Table.cs#L859-L872

`string.GetHashCode` is not a stable hashing function, according to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.string.gethashcode?view=netcore-2.1#System_String_GetHashCode)

> The hash code itself is not guaranteed to be stable. Hash codes for identical strings can differ across versions of the .NET Framework and across platforms (such as 32-bit and 64-bit) for a single version of the .NET Framework. In some cases, they can even differ by application domain. This implies two subsequent runs of the same program may return different hash codes. 

Creating the script then, can have a different outcome when run in two different environments, like `.NET Core 2.1` and `net461` or even across 32/64 bits.

**Comment by fredericDelaporte** [comment]
Anyway using an hashcode for attempting getting something unique is a bug on its own, since hashcodes are never guaranteed unique. An other naming algorithm has to be put in place.

**Comment by ramonsmits** [comment]
Alternatively use something like https://github.com/LogosBible/Logos.Utility/blob/master/src/Logos.Utility/GuidUtility.cs to generate a cross platform stable uuid

**Comment by maca88** [comment]
Hibernate fixed this problem by [postponing the generation](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/mapping/Table.java#L730) until the reference table is known, after that they [generate the name](https://github.com/hibernate/hibernate-orm/blob/b8674563d27611c09ed50086b2b4534031f07204/hibernate-core/src/main/java/org/hibernate/mapping/Constraint.java#L53) by concatenating the table and the columns names and hashing the result with the MD5 algorithm in order to avoid too long names.

**Comment by fredericDelaporte** [comment]
We should likely do the postponing. But then, the hashing part can be troublesome, since collisions may occur, even if it is quite unlikely. Moreover it guarantees a name only shorter than thirty characters, while we have dialects having `MaxAliasLength` as small as eighteen.

**Comment by fredericDelaporte** [comment]
Worse for the .Net Core case, as written in #1791, the generated names change at each run under .Net Core. So .Net Core is in the following case:

> In some cases, they can even differ by application domain. This implies two subsequent runs of the same program may return different hash codes.
