### ISSUE TITLE
Delete extension - handling more complex cases?

### ISSUE THREAD

**Issue by dziedrius** [nhibernate/nhibernate-core#1779]
Hey,
I've noticed, that in version 5+ NHibernate started to support modifying entities inside the database when using LINQ and that is one of the greatest things new things in NHibernate in my opinion.

I'm trying to work with Delete extension method currently and for simple cases it works fine.
I have a problem though to make it work for following:
```
session.Query<Child>().Where(x => x.Parent.Id == parentId).Delete()
```
or other way arround:
```
session.Query<Parent>().SelectMany(x => x.Children).Delete()
```

So, mentioned Where/SelectMany statements works fine for selecting items, but they fail with Delete extension, wondering if there is some different way to write LINQ queries to achieve what I need.

**Comment by fredericDelaporte** [comment]
There are many tests with `Delete` covering more complex looking cases than your first query. See [here](https://github.com/nhibernate/nhibernate-core/blob/5.1.3/src/NHibernate.Test/LinqBulkManipulation/Fixture.cs#L969).

Either your case is a known limitation (maybe even documented [here](http://nhibernate.info/doc/nhibernate-reference/querylinq.html#querylinq-modifying) or [here](http://nhibernate.info/doc/nhibernate-reference/batch.html#batch-direct)), or you are in a bug case.

I cannot tell from the few information you supply. Among limitations, bear in mind the action takes place directly in the database and does neither handle mapped cascades nor dependent tables like collection of elements tables and many-to-many tables. It does not handle ordering of deletes too (which may be an issue for some databases when the table has a foreign key on itself).

**Comment by dziedrius** [comment]
@fredericDelaporte  - thanks a lot, your reference to the unit test helped me dig further and I must say my initial issue description was wrong. I've tried to reproduce my issue using NHibernate unit tests entities so've modified test DeleteWithSubquery to do following:
```
var count = s.Query<SimpleAssociatedEntity>().Where(x => x.Owner.Id == 1).Delete()
```
and it worked fine. Then I came back to my case and noticed, that I'm going one level deeper, so I've wrote following in unit test:
```
var count = s.Query<Animal>().Where(x => x.Zoo.Address.City == "New York").Delete();
```
and it failed with similar error I was getting:

> NHibernate.Hql.Ast.ANTLR.InvalidPathException : Invalid join: x.Zoo [DELETE .Where[NHibernate.Test.LinqBulkManipulation.Domain.Animal, NHibernate.Test, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null](NHibernate.Linq.NhQueryable`1[NHibernate.Test.LinqBulkManipulation.Domain.Animal], Quote((x, ) => (String.op_Equality(x.Zoo.Address.City, p1))), )]

Anyway, I reviewed other bulk delete tests and it looks like following is working, even if that is not the shortest/clearest way to describe and it uses temporary table:
```
var count = s.Query<Animal>()
	.Where(x => s.Query<Zoo>().Where(a => a.Address.City == "New York").Contains(x.Zoo))
	.Delete();
```

Given that, still wondering if that is a known limitation or a bug. And if that is known limitation, what is the best way to workaround it.

**Comment by fredericDelaporte** [comment]
That is a known limitation, as explained [here](http://nhibernate.info/doc/nhibernate-reference/batch.html#batch-direct):

> No [joins](http://nhibernate.info/doc/nhibernate-reference/queryhql.html#queryhql-joins) (either implicit or explicit) can be specified in a bulk HQL query. Sub-queries may be used in the where-clause; the sub-queries, themselves, may contain joins.

So the workaround is to use sub-queries.

**Comment by fredericDelaporte** [comment]
Not that `x.Parent.Id` could appear as an implicit join but is not actually one in most cases, which allow it to be supported in `update` and `delete`: the resulting query will just do the test on the foreign key contained in x, it will not join the parent to test on its primary key. (Of course, if mapped with a property reference, then the join will then likely be done and cause the query to be unsupported for an `update` or `delete`.)
