### ISSUE TITLE
AliasToBean is trying to find and set auto-generated column to the property

### ISSUE THREAD

**Issue by osoykan** [nhibernate/nhibernate-core#1784]
Hi,

We encounter with this error time to time in our message queues. What do you advise on that? Is there any place do I need to check? I guess, it is a runtime problem rather than an implementation problem.

NHibernate: 5.1.3
NetCore 2.1 on Docker - linux
MsSqlServer 2014 as db

> **Could not find a setter for property** '**id1_1_**' in class 'CampaignPriceContext.Domain.Prices.Enrichment.ProductForPriceImportResult'
> at NHibernate.Transform.AliasToBeanResultTransformer.SetProperty(String alias, Object value, Object resultObj)at NHibernate.Transform.AliasToBeanResultTransformer.TransformTuple(Object[] tuple, String[] aliases)at NHibernate.Loader.Custom.CustomLoader.GetResultList(IList results, IResultTransformer resultTransformer)at NHibernate.Loader.Loader.ListIgnoreQueryCacheAsync(ISessionImplementor session, QueryParameters queryParameters, CancellationToken cancellationToken)at NHibernate.Impl.StatelessSessionImpl.ListCustomQueryAsync(ICustomQuery customQuery, QueryParameters queryParameters, IList results, CancellationToken cancellationToken)at NHibernate.Impl.StatelessSessionImpl.ListCustomQueryAsync(ICustomQuery customQuery, QueryParameters queryParameters, IList results, CancellationToken cancellationToken)at NHibernate.Impl.AbstractSessionImpl.ListAsync(NativeSQLQuerySpecification spec, QueryParameters queryParameters, IList results, CancellationToken cancellationToken)at NHibernate.Impl.AbstractSessionImpl.ListAsync(NativeSQLQuerySpecification spec, QueryParameters queryParameters, CancellationToken cancellationToken)at NHibernate.Impl.SqlQueryImpl.ListAsync(CancellationToken cancellationToken)at NHibernate.Impl.AbstractQueryImpl.UniqueResultAsync(CancellationToken cancellationToken)at NHibernate.Impl.AbstractQueryImpl.UniqueResultAsync[T](CancellationToken cancellationToken)at 
>

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage and support questions to the user groups:
http://nhibernate.info/groups.html

If you think it is a NHibernate bug, can you elaborate a test case please? (See [Contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md).)

With the information provided, I tend to think it is an application bug occurring on some infrequently run queries, where the query resultset columns would have incorrect aliases (or lack of aliases) specified in the query.

**Comment by osoykan** [comment]
Thanks for your response @fredericDelaporte.

I will try with a test case. For now, I'm gonna close this one until it is tested.
