### ISSUE TITLE
SchemaUpdate  does not handle foreign key contraints correctly on MariaDb/MySQL

### ISSUE THREAD

**Issue by robertoldaker** [nhibernate/nhibernate-core#1791]
I have recently upgraded my web app from using NHibernate 3.3 (on .NET framework) to v5.1.3 (.NET standard) and I am using it with MariaDb (using the MySQL configuration) and have found an issue using SchemaUpdate.

I have found that SchemaUpdate is not updating my database correctly. The problem is that SchemaUpdate will continually try to create new foreign key constraints even though they already exist. 

I think the problem is the way the foreign key names are generated. It seems to create a new random name for a foreign key which is different to the one it generated when the database was created, hence it thinks it needs to create a new one.

In NHibernate 3.3, each time you run SchemaExport it would generate the same random names for the foreign key constraints, hence SchemaUpdate would know not to recreate them since, I assume, it would create the same random names  as SchemaExport.

In version 5.1.3, SchemaExport appears to create new random names for the FK contraints each time you run it. This means that SchemaUpdate thinks it needs to create new foreign keys since (I assume) it is creating new names as well.

Hopefully I have made myself understood but please feel free to contact me if is not clear. This is a fairly important issue for me as it is stopping me from upgrading my web app to .NET Core.

btw. I think NHibernate is a fantastic and very useful piece of software!

**Comment by fredericDelaporte** [comment]
I think you encounter #1769 instead: the names change when the runtime change. Can you check that you always run with the same runtime, or that you sometimes run with .Net Framework, other times with .Net Core?

**Comment by robertoldaker** [comment]
Hi Frederic,

This happens when run on the same runtime (.NET Core). 

If I use SchemaCreate to continually re-create a database schema it will generate *different*  FK constraint names each time. 

When using NHibernate 3.3 it would generate *the same* FK constraint names each time.

Also, shouldn't SchemaUpdate use the raw information about the database (i.e. column, referenced table and referenced column) instead of a  name which isn't guaranteed to be generated the same between different runtimes?

**Comment by robertoldaker** [comment]
I have discovered a little bit more about this behaviour.

If you keep the program running then NHibernate 5.1.3 will generate the same names for the FK constraints.

If you exit the program and restart it will then generate different names for the same FK contstraints.

In NHibernate 3.3 the same names were used whether you exited the program or not.

**Comment by fredericDelaporte** [comment]
This really is the same than #1769, closing as duplicate.
