### ISSUE TITLE
Change another entities in OnFlushDirty event (or anywhere in transaction)

### ISSUE THREAD

**Issue by MonkAlex** [nhibernate/nhibernate-core#1801]
Has entity "setting", with path to files.
Has another entities, who use setting for join setting path.

Want to find and refresh another entities on setting path change. How try do it:

1. Create `Interceptor` and override `OnFlushDirty`, where find this change:

        var folderIndex = propertyNames.ToList().IndexOf(nameof(Folder));
        if (folderIndex > -1 && previousState != null)
        {
          var previous = previousState[folderIndex] as string;
          var current = currentState[folderIndex] as string;
          if (previous != current)
          {
            var someEntities = session.Query<ISomeEntity>().Where(m => m.Setting == this).ToList();
            foreach (var someEntit in someEntities)
            {
              someEntity.RefreshFolder();
              session.SaveOrUpdate(someEntity)
            }
          }
        }

someEntity change not saved in transaction

2. Change setting do in transaction:

        using (var tranc = session.OpenTransaction())
        {
          try
          {
            session.SaveOrUpdate(setting);
            tranc.Commit();
          }
          catch (System.Exception)
          {
            tranc.Rollback();
            throw;
          }
        }

3. Used `session.FlushMode = FlushMode.Commit`

How to do setting (and some other entities) changes transactional?

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage and support questions to the user groups:
http://nhibernate.info/groups.html
