### ISSUE TITLE
Document lazy="no-proxy"

### ISSUE THREAD

**Issue by cremor** [nhibernate/nhibernate-core#1804]
Seems like the "no-proxy" value is not mentioned in the documentation at all.

I don't know if it would need a long documentation. But at least it should be mentioned that the option is there. And maybe extract a short documentation from https://ayende.com/blog/4378/nhibernate-new-feature-no-proxy-associations

**Comment by fredericDelaporte** [comment]
Have you seen #1761? It is already done in this merged PR.

**Comment by cremor** [comment]
@fredericDelaporte No I didn't see this PR before. Thanks for linking (and writing) it, looks very good!

But is there any reason to hold back publishing the updated documentation? Does it contain something that was not yet released?

**Comment by fredericDelaporte** [comment]
I have documented the master state, and yes, there are many points which are 5.2 specific. Especially since while documenting, a number of issues were spotted and fixed in dedicated PRs.
