### ISSUE TITLE
Allow using ICompositeUserType for collection element mappings in Mapping By Code

### ISSUE THREAD

**Issue by martin-the-geek** [nhibernate/nhibernate-core#1821]
Attempting to map a collection of a composite user-type with mapping by code is currently rejected with an exception "Expected type implementing IUserType or IType."

The composite user type is allowed when mapping by xml.

It should be allowed with mapping by code too.

**Comment by fredericDelaporte** [comment]
Also done for map-key and key-property, see #1896.
