### ISSUE TITLE
Setting the "Default Schema" for database objects using loquacious configuration

### ISSUE THREAD

**Issue by albertodall** [nhibernate/nhibernate-core#1822]
Trying to configure my Session Factory using Loquacious Configuration, it seems that it's not possible to set the default schema for database objects. I looked at the [IDbIntegrationConfigurationProperties](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Cfg/Loquacious/IDbIntegrationConfigurationProperties.cs) interface, and I didn't find the property to set. Is it missing or I'm looking in the wrong place?

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage and support questions to the user groups:
http://nhibernate.info/groups.html

(The settings you are asking for are [mappings](https://github.com/nhibernate/nhibernate-core/blob/5.1.3/src/NHibernate/Cfg/Loquacious/IMappingsConfiguration.cs) settings.)
