### ISSUE TITLE
create migration tool with versions as EF Core Migrations

### ISSUE THREAD

**Issue by megafetis** [nhibernate/nhibernate-core#1825]
Pleace create a migration tool for Nhibernate as in EF Core migrations.
I found old lib [https://github.com/jeffreyabecker/FluentMigrator.NHibernate](https://github.com/jeffreyabecker/FluentMigrator.NHibernate).

**Comment by fredericDelaporte** [comment]
NHibernate has [`SchemaUpdate`](https://github.com/nhibernate/nhibernate-core/blob/5.1.x/src/NHibernate/Tool/hbm2ddl/SchemaUpdate.cs).

It has to be instantiated with the current NHibernate configuration for the application, and it will generate (or execute if you wish) SQL DDL update scripts by inspecting the current state of the database.

If you need something else, please elaborate.
