### ISSUE TITLE
using IPostInsertEventListener - OnPostInsertAsync not called

### ISSUE THREAD

**Issue by Nazgaul** [nhibernate/nhibernate-core#1826]
Hi.
I'm trying to implement Event bus using nhibernate event system. I implemented IPostInsertEventListener and added functionality on OnPostInsertAsync. and OnPostInsert didn't do anything.

My entire flow with nhibernate is with async operation (commitAsync, AddAsync,LoadAsync etc)
I put a breakpoint on my system and saw that OnPostInsert function was selection and not the async.
Added nhibernate reference to my code in order to see what is the bug. this is my callstack

![image](https://user-images.githubusercontent.com/3366179/44308281-1a48f180-a3bb-11e8-9e1b-407f430630d0.png)

I saw that in AfterTransactionCompletionAsync the sync method of AfterTransactionCompletion is called and not the async version. why is that?

**Comment by fredericDelaporte** [comment]
This is a limitation of the current async code generator. The transaction completion action queue fires delegates which in turn call these events. But the async code generator does not handle delegates, leaving these calls synchronous.

So in such cases, the synchronous events are raised instead.

**Comment by Nazgaul** [comment]
I see - so no way around this. thanks. too bad :) thanks for letting me know.

**Comment by hazzik** [comment]
Duplicate of #1452
