### ISSUE TITLE
linq query not count(*) but count(1)

### ISSUE THREAD

**Issue by JasonCSharpCoder** [nhibernate/nhibernate-core#1835]
Hi when use the linq query for database , is it possible to generate the count(1) not count(*) query, so that improve the performance .

**Comment by gliljas** [comment]
That doesn't improve performance. SELECT * FROM and SELECT COUNT(*) FROM are very different things.

**Comment by fredericDelaporte** [comment]
In fact, without query engine optimizations, `count(1)` is worst than `count(*)`, because the later (`count(*)`) really means "count every row" while the former (`count(1)`) means "count every row where 1 is not null".
