### ISSUE TITLE
Cannot add HqlJoin to HqlFrom

### ISSUE THREAD

**Issue by fubar-coder** [nhibernate/nhibernate-core#1838]
The function `HqlTreeBuilder.From` only accepts `HqlRange`, but not `HqlJoin` in addition to `HqlRange`, but it seems that JOINs must be part of the FROM AST.

**Comment by hazzik** [comment]
I don't think that HQL supports that. From what I've seen (I could be wrong) in the grammar: the join requires to be wrapped into range.

**Comment by fubar-coder** [comment]
I might misremembering this, but I used the HQL parser and the AST (IIRC) showed that the JOIN node was a child node of FROM. Currently, I use reflection to modify the child collection and the output query is exactly what I expected it to be.
