### ISSUE TITLE
Is it possible to mix XML mapping and C# fluent mapping?

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [nhibernate/nhibernate-core#1843]
Hi,
Our product contains hundreds of XML mappings, now we'd like to migrate to C# based mapping which provides more flexibility. However we could not migrate all in one go, as it's too time consuming.

Is there any way to mix XML and C# mappings? If that's possible, we can do migration incrementally.

**Comment by oskarb** [comment]
This system is meant for handling bugs in NHibernate. Please use the nhusers mailing list for further usage questions.

However, to anwser your question:  Yes, just add them both. For example:

    FluentConfiguration configuration = Fluently.Configure()
        .Database(MsSqlConfiguration.MsSql2008.ConnectionString(connectionString))
        .Mappings(m =>
        {
            m.HbmMappings.AddFromAssemblyOf<...>();
            m.FluentMappings.Conventions.AddFromAssemblyOf<...>();
            m.FluentMappings.AddFromAssemblyOf<...>();
        });

**Comment by Doan-Van-Tuan** [comment]
Thank you.
