### ISSUE TITLE
System.Data.SQLite.Core and ICU support

### ISSUE THREAD

**Issue by megafetis** [nhibernate/nhibernate-core#1845]
@hazzik I am using your lib: Hazzik.System.Data.SQLite.Core. 
Pleace create this lib with ICU support for .net Core

Спасибо еще раз. Фанат nhibernate

**Comment by hazzik** [comment]
Hi, this was just a repackage to check if it works on Linux. I have not built it myself. And, to be fair, I do not know how to build it.

**Comment by megafetis** [comment]
@hazzik That's too bad. I just want, that sqlite be support insensitive search (InsensitiveLike) with net core and nhibernate
