### ISSUE TITLE
My async method in nhibernate version 5.0.0 does not work

### ISSUE THREAD

**Issue by danghuynhdaty** [nhibernate/nhibernate-core#1847]
i have just upgraded my NHibernate to version 5.0.0.0 and installed NHibernateX to use async method. But i got some troubles. That method is not run, it still wait and doesnt return any results. Any helps please? Here is my code.

```
 public async Task<List<Folder>> ListFolders()
       {
        var folders = new List<Folder>();
        var hashtableFolders = (await 
           ContextPerRequest.Session.CreateCriteria(typeof(Folder).Name)                                                            
           .Add(Restrictions.Eq("State", (int) State.Active))                                                            
           .ListAsync<Hashtable>()).ToList();

        foreach (var hashtableFolder in hashtableFolders)
        {
            var folder = _hashtableAdapter.HashtableToObject<Folder>(hashtableFolder);
            folders.Add(folder);
        }

        return folders;
    }
```

**Comment by fredericDelaporte** [comment]
Hello,

You have reached the NHibernate bug tracker. Please direct usage and support questions to the user groups:
http://nhibernate.info/groups.html

By the way I do know neither about what is NHIbernateX nor why anything additional would be required for async support, which is built-in since NHibernate v5.0.

**Comment by danghuynhdaty** [comment]
thanks  fredericDelaporte. I read some answer in Stack over flow and i saw that there is a package named NHibernateX. So that i think i should install it to run async method. But it still doesnt work. I will put my question to group.

**Comment by danghuynhdaty** [comment]
Can you suggest me some directions use Async methods in NHibernate 5?

**Comment by gliljas** [comment]
Please use the Google group instead.
https://groups.google.com/forum/#!forum/nhusers
