### ISSUE TITLE
LINQ Coalesce and Conditional on Properties

### ISSUE THREAD

**Issue by PleasantD** [nhibernate/nhibernate-core#1879]
Some basic cases
```
session.Query<Entity>().Where(x => (x.OptionA ?? x.OptionB).Value == value);
session.Query<Entity>().Where(x => (x.UseA ? x.OptionA : x.OptionB).Value = value);
session.Query<Entity>().Where(x => (x.UseA ? x.ListA : x.ListB).Count() > 2);
```

In each of these cases (and a few more) the expression can be easily re-written to correctly express the logic desired.

```
session.Query<Entity>().Where(x => (x.OptionA != null ? x.OptionA.Value : x.OptionB.Value) == value);
session.Query<Entity>().Where(x => (x.UseA ? x.OptionA.Value : x.OptionB.Value) = value);
session.Query<Entity>().Where(x => (x.UseA ? x.ListA.Count() : x.ListB.Count()) > 2);
```

**Notes**
* Coalesce needs to be re-written as a conditional so that a null value at `x.OptionA.Value` is used as expected
* The third example actually places the conditional in the `FROM` clause of the sub-query, which means the single sub-query needs to be re-written to be a conditional with multiple (near identical) sub-queries inside it

**Comment by PleasantD** [comment]
PR will be coming soon :-)

**Comment by PleasantD** [comment]
*For posterity*
My initial thought was actually to re-write the `JOIN` to contain the coalesce or conditional, but this turned out to be impossible without significant changes to the way HQL is translated to SQL. The current `HqlSqlWalker` grammar simply doesn't support joins that are defined as anything other than property access. 

This also would not work for the conditional subquery case.

**Comment by fredericDelaporte** [comment]
PR are treated as issues, so when you intend to contribute the fix shortly, you can just open a PR holding all the details.
