### ISSUE TITLE
SerializationException when serialize configuration to file

### ISSUE THREAD

**Issue by megafetis** [nhibernate/nhibernate-core#1897]
When I want to serialize my instance of Configuraton class:
Done as in Cookbook book in Article "Improving performance":

> SerializationException: Type 'System.Type' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.

Database postgresql, works well, configured by FluentNhibernate.
Configuration is trivial
.Net Core

**Comment by hazzik** [comment]
In current released version on .NET Core:

> Binary serialization is not supported - the user shall implement serialization surrogates for System.Type,
        FieldInfo, PropertyInfo, MethodInfo, ConstructorInfo, Delegate, etc.
      

In 5.2 there will be a surrogate helper available that can be plugged in BinaryFormatter.

**Comment by hazzik** [comment]
See #1693 for insights how to implement a surrogate helper.
