### ISSUE TITLE
Garbled when I insert entity data with chinese characters

### ISSUE THREAD

**Issue by Gerrey** [nhibernate/nhibernate-core#1902]
these day ,i tried insert chinese characters  to table of mysql through Entities of NHibernate ,but when i  open  that inserted table,discover inside all chinese characters  is become  question mark(like: values(???)) , i doubt not mysql encode problem, but NHibernate inside encode deal with problem. the NHibernate version at that time is 4.0.1.400.

**Comment by fredericDelaporte** [comment]
NHibernate has a test for this, and it [succeeds](https://teamcity.jetbrains.com/viewLog.html?currentGroup=test&scope=NHibernate.Test.dll%23teamcity%23NHibernate.Test.TypesTest%23teamcity%23StringTypeFixture&pager.currentPage=1&order=DURATION_DESC&recordsPerPage=20&filterText=InsertUnicodeValue&status=&buildTypeId=bt868&buildId=1752629&tab=testsInfo). (Guest login available.)

https://github.com/nhibernate/nhibernate-core/blob/9de4aaa3fb8e1fe01cf4316d126a378050ccecdf/src/NHibernate.Test/TypesTest/StringTypeFixture.cs#L43-L59

This test has been added in 5.1 only, but no changes were required for having it succeed with MySQL.

If you can reproduce the trouble with a test case (see [contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md)) on master, please re-open the issue and submit the test case.
