### ISSUE TITLE
Sample Application Support Required

### ISSUE THREAD

**Issue by AshwinKamathB** [nhibernate/nhibernate-core#1903]
We want to create a .Net Core (SQLite) application using NHIbernate-Core which can run on Linux system.
Can you guys please share one sample application with output which can be directly ran on Linux system.

libSqlite.Interop.os we have built and put in the bin directory . Every time application fails.

**Comment by oskarb** [comment]
Fails? I suppose you have an error message then?

**Comment by fredericDelaporte** [comment]
There is a sample web application supporting both .Net Core and .Net Framework in the repository, [here](https://github.com/nhibernate/nhibernate-core/tree/master/src/NHibernate.Example.Web).

Moreover, the [test suite](https://github.com/nhibernate/nhibernate-core/tree/master/src/NHibernate.Test) is also run under Linux with Travis.

By the way, you have reached the NHibernate bug tracker. Please direct usage and support questions to the user groups:
http://nhibernate.info/groups.html

**Comment by fredericDelaporte** [comment]
This moreover does not look bound to NHibernate. It is very likely that your project would also fail using SQLite directly. Try first to get it working when using directly SQLite for some basic tasks, and ask support for this on SQLite side.

**Comment by AshwinKamathB** [comment]
Yes.Thank you for the information.I resolved it.Basically you need libSqlite.Interop.dll in the bin directory,

I had libSQLite.Inteop.so file.I renamed to libSQLite.Interop.dll and put it in bin
