### ISSUE TITLE
Control over BeginTransaction in AdoTransaction

### ISSUE THREAD

**Issue by greenlight2k** [nhibernate/nhibernate-core#1908]
It should be possible to control how the DbTransaction is created for generic Database Drivers.

Firebird for example implements its own `DbConnection`: `FbConnection`.
In this class, there is a Firebird specific overload for the `BeginTransaction` Method that lets you use specific Firebird `FbTransactionOptions`.

Of course, there is no way for NHibernate to consider such generic implementations.

I have a suggestion for giving the User an optional control over this matter:

Inside [AdoTransaction](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Transaction/AdoTransaction.cs#L149) on the Method `Begin(IsolationLevel isolationLevel)` there is the following code where the `DbTransaction` is created:

```C#
if (isolationLevel == IsolationLevel.Unspecified)
{
  trans = session.Connection.BeginTransaction();
}
else
{
  trans = session.Connection.BeginTransaction(isolationLevel);
}
```

How about moving that code to a protected virtual Method like this:

```C#
protected virtual DbTransaction BeginTransaction(IsolationLevel isolationLevel, ISessionImplementor sessionImplementor)
{
    if (isolationLevel == IsolationLevel.Unspecified)
    {
        return sessionImplementor.Connection.BeginTransaction();
    }
    else
    {
        return sessionImplementor.Connection.BeginTransaction(isolationLevel);
    }
}
```

And changing the mentioned code above using that Method:

```C#
trans = BeginTransaction(isolationLevel, session);
```

This way, i can derive from `AdoTransaction` and override my own specific implementation.
For example with the specific Firebird `Wait` Option:

```C#
public class FirebirdAdoTransaction : AdoTransaction
{
    public FirebirdAdoTransaction(ISessionImplementor session) : base(session)
    {
    }

    protected override DbTransaction BeginTransaction(IsolationLevel isolationLevel, ISessionImplementor sessionImplementor)
    {
        if (sessionImplementor.Connection is FbConnection firebird)
        {
            var transactionOptions = new FbTransactionOptions
            {
                TransactionBehavior = FbTransactionBehavior.Wait
            };

            if (isolationLevel == IsolationLevel.ReadCommitted)
            {
                transactionOptions.TransactionBehavior |= FbTransactionBehavior.ReadCommitted;
            }

            return firebird.BeginTransaction(transactionOptions);
        }
        else
        {
            return base.BeginTransaction(isolationLevel, sessionImplementor);
        }
    }
}
```

Then, i only have to create my own `TransactionFactory`, using the `FirebirdAdoTransaction` and change my NHibernate Settings `"transaction.factory_class"` to this Factory:

```C#
public class FirebirdTransactionFactory : AdoNetWithSystemTransactionFactory
{
    public override ITransaction CreateTransaction(ISessionImplementor session)
    {
        return new FirebirdAdoTransaction(session);
    }
}
```

I think this is a good addition in general, since you never know what generic implementation of `DbConnection` is used by the Database driver and this `protected virtual` method gives the user full control over driver related transaction options.

Also: No breaking change.

EDIT:
Changed the name of the `protected virtual` method to `BeginTransaction` like suggested by **hazzik**

**Comment by hazzik** [comment]
Sounds good.

**Comment by hazzik** [comment]
Let's name this protected virtual method as BeginTransaction to be consistent with the ADO.

**Comment by fredericDelaporte** [comment]
@greenlight2k, would you contribute this `BeginTransaction` with a PR? It is likely it could then be merged soon.

**Comment by fredericDelaporte** [comment]
The overridable method has been put in the `DriverBase` class. It will be added to the `IDriver` interface in NHibernate 6.0.

So in NHibernate v5.2, the feature is available when using a driver deriving from `DriverBase`. Override the `DriverBase.BeginTransaction` method.

Drivers are meant to handle the data provider specificities, and so they are the right place to handle the need as expressed here. (Maybe the Firebird example here is even something that should be put in current NHibernate Firebird driver.)
