### ISSUE TITLE
JoinAlias on JoinQueryOver fails

### ISSUE THREAD

**Issue by ondravondra** [nhibernate/nhibernate-core#1928]
I have a query like this:

```c#
using (var ses = sessionFactory.OpenSession())
{
  Z aliasZ = null;
  ses.QueryOver<X>()
    .Inner.JoinQueryOver(x => x.PropertyY)
    .Inner.JoinAlias(y => y.PropertyZ, () => aliasZ)
    .Select(Projections.Entity(() => aliasZ))
    .SingleOrDefault<Z>();
}
```
Names of the classes are replaced with X, Y, Z because they are part of closed source software I work on as an employee.

After upgrading to NH 5.2.0, the query fais:
```
NHibernate.Exceptions.GenericADOException : could not execute query
...
42P01: missing FROM-clause entry for table "aliasz2_"
```

The generated sql does contain join table Z. I am using `NHibernate.Dialect.PostgreSQL82Dialect`.

If I remove `.Select(Projections.Entity(() => aliasZ))` and replace Z with X in `SingleOrDefault` the query runs without errors.

**Comment by fredericDelaporte** [comment]
Yes it is a regression of #287. It was failing to resolve aliases done from a property of a non-aliased criteria.

**Comment by fredericDelaporte** [comment]
I have shortened the title.
