### ISSUE TITLE
OracleManagedDataClientDriver and Oracle.ManagedDataAccess.Core

### ISSUE THREAD

**Issue by jScope** [nhibernate/nhibernate-core#1937]
Hi,

I've got a question which is related to your package so maybe you can help me.

You have OracleManagedDataClientDriver support for Oracle.ManagedDataAccess and nHibernate itself is now compatible to .Net Standard and .Net Core as far as I know.

Now I would like to use the .Net standard oracle managed driver:
https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.12.0-beta2

I know it's still beta. Is this already possible or is it even planned to support this driver?

I tried to initialize the OracleManagedDataClientDriver from my hibernate.cfg.xml without success.

Thank you for your help.

**Comment by fredericDelaporte** [comment]
Hello,

You have reach the issue, tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).

The `OracleManagedDataClientDriver` is compatible with the `Oracle.ManagedDataAccess.Core`. And I have checked it by running under .Net Core a part of the NHibernate.Test test suite, with an additional package reference to `Oracle.ManagedDataAccess.Core`, and with an Oracle Managed configuration identical to the one used for testing the .Net Framework. I have checked this will the three versions of `Oracle.ManagedDataAccess.Core` currently available.

By the way, I do not think it will ever cease to be beta for the Oracle 12 series: they have released a non-beta 2.18.3 version, for Oracle 18. For the few cases I have tested, it works for accessing a 12c database.
