### ISSUE TITLE
Caching of Property Dialect in class Configuration.Mapping

### ISSUE THREAD

**Issue by ValResnick** [nhibernate/nhibernate-core#1950]
This Property should be cached, because the creation of Dialect can be expensive. 

This is our scenario: We have a base class with a lot of subclasses (over 400).

The class `UnionSubclassEntityPersister` creates for our base class  a very long (over 20 Million characters) SubQuery in `GenerateSubquery`. 

```c#
// from UnionSubclassEntityPersister
subquery = GenerateSubquery(persistentClass, mapping);
```

Everytime `GetSqlTypeCode` is called for an instance of `NullableType` the Dialect will be created again.

```c#

// from UnionSubclassEntityPersister.GenerateSubquery
var sqlType = col.GetSqlTypeCode(mapping);

```
```c#
// from NullableType
static SqlType OverrideSqlType(IMapping mapping, SqlType type)
{
   return mapping != null ? mapping.Dialect.OverrideSqlType(type) : type;
}
```

This is a possible solution for the problem.

```c#
[Serializable]
private class Mapping : IMapping
{
   private readonly Configuration configuration;

   [NonSerialized]
   private readonly Lazy<Dialect.Dialect> _lazyDialect;

   public Mapping(Configuration configuration)
   {
      this.configuration = configuration;
				
      _lazyDialect = new Lazy<Dialect.Dialect>(() => NHibernate.Dialect.Dialect.GetDialect(this.configuration.Properties));
   }
   
   ...

   public Dialect.Dialect Dialect => _lazyDialect.Value;
}
```

**Comment by fredericDelaporte** [comment]
Have you checked there is still the issue with NHibernate v5.2? There have been some changes done on that precise subject. See #1703.

**Comment by ValResnick** [comment]
Today i tried to upgrade our project to V5.2.1. That's the reason i have created this issue :-)

**Comment by fredericDelaporte** [comment]
Ok, it is already lazy in [`Mappings`](https://github.com/nhibernate/nhibernate-core/blob/ce73fc08719d5f8494d9755d94e0ef88f1de3ece/src/NHibernate/Cfg/Mappings.cs#L92), but the trouble is in [`Mapping`](https://github.com/nhibernate/nhibernate-core/blob/ce73fc08719d5f8494d9755d94e0ef88f1de3ece/src/NHibernate/Cfg/Configuration.cs#L187).

This dates back to 1464f48, #703, v5.0.

**Comment by fredericDelaporte** [comment]
In this case, switching to lazy will cause bugs if someone build a session factory from a configuration, then change the configuration's dialect (and connection string, obviously) and build a new session factory from it. (Or use other methods depending on that `Mapping` class.) Something else would have to be done.

**Comment by ValResnick** [comment]
My solution is not (fully) correct. When the mapping was deserialized, the Property throws a Nullpointer Exception.

**Comment by ValResnick** [comment]
Can i avoid the creation the big subQuery instead?
I assume a query with 20 Million characters makes no sense for the framework ?

**Comment by fredericDelaporte** [comment]
> Can i avoid the creation the big subQuery instead?

This is another subject. I think the dialect many instantiations in `Mapping` should anyway be fixed, so let the issue here stay on this dialect subject.

About the big sub-query trouble, it is likely a subject to be discussed first on the [user groups](https://nhibernate.info/groups.html) ([nhusers](http://groups.google.com/group/nhusers)). It seems it is useless in your case (and likely not working if trying to execute it), so it should be checked if it can be avoided. That is a support subject, whereas the NHibernate GitHub issues are used for bug reports or feature requests. (It may conclude there would be a need for changes in NHibernate, in which case another issue will have to be opened, but it has first to be checked.)
