### ISSUE TITLE
Dialect NHibernate.Dialect.MsSql2012Dialect raises "Dialect does not support DbType.UInt64"

### ISSUE THREAD

**Issue by jmroyb** [nhibernate/nhibernate-core#1958]
Hi,

DbType.UInt64 is not supported in 5.2.1.

Do you plan support it soon?

Thanks

**Comment by fredericDelaporte** [comment]
No one works on this as far as I know. Anyway, SQL-Server does not seem to have a matching [type](https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-2017#exact-numerics) for it, or am I wrong?

**Comment by oskarb** [comment]
I think you need to map ulong to a NUMERICAL column.
https://blog.sqlauthority.com/2013/06/21/sql-server-storing-64-bit-unsigned-integer-value-in-database/
