### ISSUE TITLE
Investigate licenseUrl deprecation

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#1973]
Pushing the Nuget package yields a warning about `licenseUrl` being deprecated.
See [here](https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl), we should use `license` instead. These are Nuget properties. We currently specify the .csproj property `PackageLicenseUrl`.

What should be done should be investigated.

**Comment by bahusoid** [comment]
Related [docs](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties).
Seems we have two options for replacement `PackageLicenseExpression` or `PackageLicenseFile`

And here is example for [PackageLicenseFile](https://github.com/nkolev92/docs.microsoft.com-nuget/blob/0c3a25afd2c87abd434996a9ca86820de3799cea/docs/reference/errors-and-warnings/NU5030.md)
