### ISSUE TITLE
System.InvalidCastException when merge collenction with LazyProperty

### ISSUE THREAD

**Issue by offan** [nhibernate/nhibernate-core#1993]
System.InvalidCastException: "NHibernate.Intercept.UnfetchedLazyProperty" in "System.Byte[]"."
when merge collenction entity with LazyProperty.

add test   CanMergeTransientWithLazyPropertyInCollenction()
repo: https://github.com/offan/nhibernate-core
branch  NHTest

**Comment by maca88** [comment]
The issue lies in the `TypeHelper.Replace` which was [fixed](https://github.com/hibernate/hibernate-orm/commit/1af878166fe0883ceb3d9130afa2790850492624) in Hibernate [HHH-12555](https://hibernate.atlassian.net/browse/HHH-12555). I will update your PR by porting the fix.
