### ISSUE TITLE
The column 'Contract' has already been added in this SQL builder when upgrading to NH 5.2.3

### ISSUE THREAD

**Issue by Heisenberg74** [nhibernate/nhibernate-core#2001]
Hi,

Thank you for your help !

Since i tried to upgrade NuGet package of NHibernate from 5.1.4 to 5.2.3 I have the following error message when session is created:

The column 'Contract' has already been added in this SQL builder

Below, mapping and models of my two entities:

	public class WorkCenterDepartmentMap : ClassMap<WorkCenterDepartment>
	{
		public WorkCenterDepartmentMap()
		{
			Table("WORK_CENTER_DEPARTMENT");

			CompositeId().KeyProperty(x => x.Contract, "CONTRACT")
						 .KeyProperty(x => x.DepartmentNo, "DEPARTMENT_NO");

			Map(x => x.Description);
		}
	}

	public class WorkCenterMap : ClassMap<WorkCenter>
	{
		public WorkCenterMap()
		{
			Table("WORK_CENTER");

			CompositeId().KeyProperty(x => x.Contract, "CONTRACT")
						 .KeyProperty(x => x.WorkCenterNo, "WORK_CENTER_NO");

			Map(x => x.Description);
			Map(x => x.QueueTime).Column("QUEUE_TIME");
			References(x => x.WorkCenterDepartment).Columns("CONTRACT", "DEPARTMENT_NO");
		}
	}

	public class WorkCenter
	{
		public virtual Site Site { get; set; }
		public virtual string Contract { get; set; }
		public virtual string WorkCenterNo { get; set; }
		public virtual string Description { get; set; }
		public virtual string FullDescription
		{
			get
			{
				return $"{WorkCenterNo} - {Description}";
			}
		}
		public virtual double QueueTime { get; set; }
		public virtual WorkCenterDepartment WorkCenterDepartment { get; set; }
		public virtual ProductionLine ProductionLine { get; set; }
		public override bool Equals(object obj)
		{
			if (obj == null)
				return false;
			WorkCenter id;
			id = (WorkCenter)obj;
			if (id == null)
				return false;
			if (Contract == id.Contract && WorkCenterNo == id.WorkCenterNo)
				return true;
			return false;
		}
		public override int GetHashCode()
		{
			return (Contract + "|" + WorkCenterNo).GetHashCode();
		}
	}

	public class WorkCenterDepartment
	{
		public virtual Site Site { get; set; }
		public virtual string DepartmentNo { get; set; }
		public virtual string Contract { get; set; }
		public virtual string Description { get; set; }
		public virtual string FullDescription
		{
			get
			{
				return $"{DepartmentNo} - {Description}";
			}
		}
		public override bool Equals(object obj)
		{
			if (obj == null)
				return false;
			WorkCenterDepartment id;
			id = (WorkCenterDepartment)obj;
			if (id == null)
				return false;
			if (Contract == id.Contract && DepartmentNo == id.DepartmentNo)
				return true;
			return false;
		}
		public override int GetHashCode()
		{
			return (Contract + "|" + DepartmentNo).GetHashCode();
		}
	}

**Comment by fredericDelaporte** [comment]
This error indicates a duplicated writable column in your mapping. Duplicated column must be read-only, if there are some, as explained [here](https://github.com/nhibernate/nhibernate-core/pull/1875#issuecomment-444056599) and in [release notes](https://github.com/nhibernate/nhibernate-core/blob/5.2.3/releasenotes.txt#L57).

So you should set your `References` mapping as read-only (update false and insert false).

By the way, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).

**Comment by Heisenberg74** [comment]
Thank you very much. I though it was a bug because it worked on previous version.
Sorry for the incovenience !

**Comment by MarcinSasin** [comment]
Hi,

I know I should post on nhusers group and I did. No response so far so I am posting here. Hopefully someone will be able to help me.

I have the same problem as described above. We updated references as read only but we also use **joined-subclass**. The problem is there is no insert property to be set as false for KEY property of joined-subclass. So we still get the error: 
NHibernate.MappingException: 'Unable to build the insert statement for class 'abc'; a failure occured when adding the Id of the class.
The column 'column_name' has already been added in this SQL builder

It worked fine before migration to NH 5.2.3, Appreciate any idea how to handle this ?

**Comment by gupswa** [comment]
How to fix the same issue in case of one-to-many relationship where Parent and Child both have composite keys with same column names eg: ID, Name.
I tried using inverse="true" attribute in <bag> but it is causing Concurrency issue:
NHibernateStaleObjectState: "Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect):"

Here are the mappings done:
**Parent** :
![image](https://github.com/nhibernate/nhibernate-core/assets/155950278/691b420f-2a67-409d-b1c6-ec9d01dccc0a)

**Child**:
![image](https://github.com/nhibernate/nhibernate-core/assets/155950278/3dd11a86-e03c-467e-bef9-b0ee75158d33)
