### ISSUE TITLE
LINQ not translating Min(), Max() to SQL in VB.Net

### ISSUE THREAD

**Issue by The-Bytemaster** [nhibernate/nhibernate-core#2008]
I am not sure if this is nHibernate problem, or a compiler issue.  I was using LINQPad with show_sql on to diagnose this issue.

If using VB.Net and the Max function on a DateTime property, everything works correctly.  If you use the Max function on an Integer or nullable integer property, it translates it to retrieve all of the records from the database and then apply the Max operator to the results.

On closer inspection of the IL, it the case of integer it is compiling the call to  System.Linq.Enumerable.Max<DomainObject> instead of System.Linq.Queryable.Max<DomainObject, Int> or similar.  Again, this works fine if the type is DateTime.

**Comment by hazzik** [comment]
Can you show the code?

**Comment by The-Bytemaster** [comment]
Here is a couple of examples that work for DateTime, but not for Integer:

```
Dim activeSession = _sessionFactory.OpenSession()
Dim myVar = activeSession.Query(Of Product).Max(Function(n) n.Id)
return myVar
```

or long form

```
Dim activeSession = _sessionFactory.OpenSession()
Dim myVar = Aggregate row In activeSession.Query(Of Product)
					Into Max(row.Id)
return myVar
```

**Comment by bahusoid** [comment]
Hm... Indeed. You can see it right inside Visual Studio  via "Go To Definition".
Max on `DateTime` type leads correctly to queryable extension:
```
Public Shared Function Max(Of TSource, TResult)(source As IQueryable(Of TSource), selector As Expression(Of Func(Of TSource, TResult))) As TResult
```

But for `Integer` it's enumerable extension:
```
Public Shared Function Max(Of TSource)(source As IEnumerable(Of TSource), selector As Func(Of TSource, Integer)) As Integer
```

It's some VB.NET quirk.

As a temp fix I think you can use direct proper extension call though not sure if it's possible  in VB.NET. In C# it's something like:
```C#
var myVar = Queryable.Max(session.Query<Product>(), e => e.Id);
```

**Comment by bahusoid** [comment]
Or simply use different override without selector:
`Dim myVar = (From p In session.Query(Of Product) Select p.Id).Max()`

Anyway it's not NHibernate issue.

**Comment by hazzik** [comment]
I don't think that we can do anything here.
