### ISSUE TITLE
Combining an implicit JOIN with a LEFT JOIN which requires a WITH clause triggers an exception.

### ISSUE THREAD

**Issue by bahusoid** [nhibernate/nhibernate-core#2031]
Original problematic query from hibenate [issue](https://hibernate.atlassian.net/browse/HHH-7321) looks like:
```SQL
SELECT s.studentId, q.questionId, sa.answer
FROM Student s, Question q
LEFT JOIN s.studentAnswerList AS sa WITH sa.question.questionId = q.questionId
```
Test simulating such query was added here:
https://github.com/nhibernate/nhibernate-core/blob/11bc49d412fda5630a6ac576d6bdd9d940220975/src/NHibernate.Test/Hql/EntityJoinHqlTest.cs#L124-L138

NHibernate currently generates joins in wrong order 
```SQL
FROM fromTable
LEFT JOIN leftJoin ON leftJoin.someId = thetaJoin.someId
,  thetaJoin
```

**Comment by bahusoid** [comment]
I understood the root of the issue. Parser converts flat list of joins to parent-child tree:
1 fromTable -> 2 thetaJoin -> 3 leftJoin

is transformed to:
1 fromTable -> 1.1 leftJoin (as leftJoin is mapped association for fromTable)
1.2 thetaJoin

And final join list is constructed by flattening this tree: fromTable -> leftJoin -> thetaJoin

That means that this issue affects entity join too if it's referenced in association:
```SQL
FROM  fromTable
INNER JOIN entityJoin  ...
LEFT JOIN  association WITH entityJoin.SomeID =  association.SomeID
```

It seem some kind of topological sorting is required here. Or at least user defined order of joins shouldn't be affected .

**Comment by hazzik** [comment]
Is it this one? https://hibernate.atlassian.net/browse/HHH-1969

**Comment by bahusoid** [comment]
Looking for provided SQL - very likely. But this issue was closed as duplicate of https://hibernate.atlassian.net/browse/HHH-1480 without much investigations. So I can't be sure.

**Comment by hazzik** [comment]
Based on a discussion in #2037 here should be "CROSS JOIN". Otherwise it would not be possible to re-order the joins in any way which will allow the query to execute.

**Comment by bahusoid** [comment]
>  should be "CROSS JOIN". Otherwise it would not be possible to re-order the joins in any way which will allow the query to execute.

So to me now it looks like 2 issues:
1) Invalid query - as this query can't be written correctly in SQL with implicit joins.
I don't like the path hibernate took on this - by simply replacing implicit joins with cross joins. It's not the same thing and such fix looks wrong to me.
So invalid generated SQL is correct behavior to me - NHibernate should not try to fix invalid user queries.
To me much better way would be adding support for cross join type (only for entity joins) in hql. And linq should generate cross joins instead of implicit joins.

2) Invalid join orders in generated SQL (this issue affects also entity joins )
Something that needs to be investigated.

@hazzik  What do you think on 1? If you agree I can try to implement support for cross joins for entity joins

**Comment by hazzik** [comment]
Is it the same as #1060?

**Comment by bahusoid** [comment]
Yes that's it. But as we've seen it's not SQL Server specific and implicit join != cross join (though I'm not anymore convinced that we should really care about it)

**Comment by bahusoid** [comment]
Closing it as problematic hql query is actually wrong and can't be expressed in valid SQL. I will probably create a separate issue for invalid join orders with valid query.
TODO: Replace `ImplicitJoinAndWithClause` with proper test
