### ISSUE TITLE
Dml Style Update fails with static where sql in mapping

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#2053]
Below query was working until 5.2.3. But with current master NH code it is no more working.
Fluent Mapping files includes a `Where("STATUS = 1")` filter. Normally NH adds the table alias name at the beginning of the filter, but in this case there is no alias added in the query, so it just adds the `.` character.

```c#
ISession.Query<TxnCycle>()
                .Where(x => x.StmtDate == null && accountNo.Contains(x.StmtAccountNo))
                .Update(u => new TxnCycle() { StmtDate = eodDate });
```
Output Sql:
```
NHibernate.SQL|
update OCN_ISS.TXN_CYCLE set STMT_DATE=:p0
  where ( .STATUS = 1) and (STMT_DATE is null)
    and (STMT_ACCOUNT_NO in (:p1));
:p0 = 20190310 [Type: Int32 (0:0:0)], :p1 = '1283' [Type: String (0:0:0)]
```

**Comment by maca88** [comment]
I tried to reproduce the issue, but without success. [Here](https://github.com/maca88/nhibernate-core/commit/c1e14f4eec3318c34d58c6ec297a6ac581a193c9) is the test case that I tried and it works on Sql Server. Can you provide the mappings for `TxnCycle` or create a the test case that fails?

**Comment by gokhanabatay** [comment]
Hi maca88,
With 5.2.4 it is succeded without static filter in sql statement, but if you could build master code of Nhibernate and put it in the bin folder then you will get the exception that i mentioned.

```c#

 [TestCase(1), Order(3)]
        public void UpdateDmlStyle_TxnCycle_Fail(short mbrId)
        {
            CurrentSession.MbrId = mbrId;
            //Sets Current Session
            using (ISession session = SessionProvider.ISessionFactory
                                        .WithOptions()
                                        .Interceptor(new ContextInterceptor())
                                        .OpenSession())
            {
                using (ITransaction transaction = session.BeginTransaction())
                {
                    string[] descriptions = new string[] { "DESCRIPTION" };
                    

                    Assert.Throws<Exception>(() => session.Query<TxnCycle>()
                    .Where(x => descriptions.Contains(x.Description))
                    .Update(x => new TxnCycle() { Description = "DESCRIPTION_UPDATED" }));

                }
            }
        }

```
Sql
```sql
update TXN_CYCLE set DESCRIPTION=:p0 where DESCRIPTION in (:p1)
```

[StaticFilterConditionTest ](https://github.com/gokhanabatay/NHibernateBugTest)

**Comment by fredericDelaporte** [comment]
And thanks for the early report, it is great to have regressions spotted before release.

**Comment by gokhanabatay** [comment]
Your welcome, thank you for quick response.
