### ISSUE TITLE
Sending int criterion value to a nvarchar field

### ISSUE THREAD

**Issue by HakanKaraoglu** [nhibernate/nhibernate-core#2057]
Hi,
With NHibernate mapping I have defined a field in the table with a value of nvarchar (50). Then I sent a select query to this table with a set of parameters. When I look at it with nHProfil, it has sent int value to the nvarchar field, which causes an extra cost of convert and may cause my queries to slow down.

`Map(x => x.TerminalCode).Nullable(); (This field is string)`

Select query NHibernate Profiler output 

`and endofday0_.TerminalCode = 10430001 /* @p3 */` 

string value seems to be gone as int

**Comment by gliljas** [comment]
Are you sure it's not just how NHProf displays it?

Den tors 14 mars 2019 kl 22:34 skrev Hakan KARAOĞLU <
notifications@github.com>:

**Comment by HakanKaraoglu** [comment]
@gliljas You're right. The NHProfiler shows the int value, but the query is seen as nvarchar in SQL Profiler.  I didn't check SQL Profiler :)
