### ISSUE TITLE
LINQ - Equality Operator Comparison Customization

### ISSUE THREAD

**Issue by BrunoJuchli** [nhibernate/nhibernate-core#2059]
Hello
Given

    public class AbstractEntity {
        public Guid Id { get; set; }
        // also contains ==, != and Equals implementations which basically just compare the Id property.
    }

    public class Bar : Entity { }

    public class Foo : IEntity {
        public Bar Bar { get; set; }
    }

I would like to write a query like

    var bar = new BarEntity { Id = Guid.NewGuid };
    session.Query<FooEntity>().SingleOrDefault(x => x.Bar == bar);

but have it perform the same SQL as:

        var bar = new BarEntity { Id = Guid.NewGuid };
        session.Query<FooEntity>().SingleOrDefault(x => x.Bar.Id == bar.Id);

---------

They both work and give the same result, it's just that the first query will load all `FooEntity`s in memory and then perform the `Where` in memory, while as the second will perform `SELECT * FROM Foo WHERE Foo.BarId == {bar.Id}`, thus being much faster.
Now instead of remembering to correctly implement this I would like to configure / extend NHibernate to tell it:

translate `AbstractEntity == AbstractEntity ` to `AbstractEntity .Id == AbstractEntity .Id`.

-----------------

I've already digged into the NHibernate Code a bit. I first thought I could create a `BaseHqlGeneratorForMethod` like `EqualsGenerator`, but debugging - stepping through the code - i found that `==` will not perform a lookup for a method generator. Instead, `HqlGeneratorExpressionVisitor.VisitExpression` will go to `HqlGeneratorExpressionVisitor.TranslateEqualityComparison` which in turn will

    return _hqlTreeBuilder.Equality(
        VisitExpression(expression.Left).ToArithmeticExpression(),
        VisitExpression(expression.Right).ToArithmeticExpression());

(note: not an exact copy of the code).

Given my very limited knowledge this seems like a dead end. Is there another extensibility point further up or down the call chain to implement what I want?

Thanks a lot!

**Comment by bahusoid** [comment]
What about:
```C#
session.Query<FooEntity>().Where(x => x.Bar == bar).SingleOrDefault();
```
It should work exactly as you want.

**Comment by BrunoJuchli** [comment]
@bahusoid 
Thanks for taking the time and your reply.

It seems you're right. Actually, my original premise seems to be wrong, even 

    session.Query<FooEntity>().SingleOrDefault(x => x.Bar == bar);

results in an SQL with a WHERE on the Id.
I'm sorry for wasting your time.
