### ISSUE TITLE
One-to-one properties not appearing in Select() projection result set

### ISSUE THREAD

**Issue by jhinder** [nhibernate/nhibernate-core#2064]
**Version:** 5.2.4

We're having an issue with creating projections (with Linq's `Select()`) of entities where one of the properties is a one-to-one map.

I've created a [repro](https://gist.github.com/jhinder/6c8ce3faf49b212ea7a514940ebe2fc5).

**Expected result:** `Results` is not null in both cases.

**Actual result:** `Results` is null in the first case (with the Select() projection), but in the second case (plain query) it's a correct, non-null object.

(We're using FluentNHibernate to generate the mappings, but the `<one-to-one />` mapping lines look fine in the generated XML.)

----

So far I've found out that `NHibernate.Type.OneToOneType.Hydrate()` is called twice each time, and the `owner` parameter has these values:

* First example (Select()):
  * First call: a `Results` object
  * Second call: `null`
* Second example (plain query):
  * First call: an `Owner` object
  * Second call: a `Results` object

Might a part of issue be that `owner` is null at one point, and thus `Hydrate`'s return value is null as well, leading a method further down the call stack to believe the object to be null?

**Comment by jhinder** [comment]
The general loading behaviour seems to be very different.

Case 1: Loader.GetRowFromResultSet -> OneToOneType -> back to Loader.GRFR -> OneToOneType (with owner=null).
The call stack for the last OneToOneType.Hydrate call is very different from all other call stacks (it goes through NHibernate.Type.EntityType.NullSafeGet for some reason).
Yet it seems like NHibernate is able to load the dependent object (it has the object at some point, and the second table is included in the generated SQL).

Case 2: Loader.GRFR -> OTOT -> GRFR, once for the Owner object, once for the Results object. This leads to the correct object tree.

**Comment by bahusoid** [comment]
Indeed  hql currently can't return one-to-one associations mixed with scalar properties as the code below doesn't provide owner required for one-to-one association:
https://github.com/nhibernate/nhibernate-core/blob/7ae2b5d040e62db356485f26d2e9ce2e31f299fa/src/NHibernate/Loader/Hql/QueryLoader.cs#L371-L379

Required one-to-one entity is prepared and ready to be used from provided `row` parameter. But it's unclear how to connect it to given ResultType.
