### ISSUE TITLE
Wrong proxy built for base class with interfaced sub-classes

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#2067]
When a proxy for a base class is built (without mapping the proxy as an interface), a wrong proxy is built if the base class has sub-classes mapping their proxy as an interface.

The built proxy for the base class does not inherits from the base class. It should.

This causes a type cast exception when attempting a `Load<BaseClass>(id)`.

(This is extracted out of #2052, which suspect this bug as being the cause of the trouble in  #2052 (interface access causing a proxy load since v5.1). But the built proxy for the base class was also wrong in 4.x/5.0.x, it was also not inheriting from the base class. So I consider we need to handle separately the proxy building issue from the proxy loading one.)

**Comment by hazzik** [comment]
I'm struggling to decipher the bug description :-(

**Comment by hazzik** [comment]
Are you working on fixing it?

**Comment by hazzik** [comment]
The subclasses are not necessary to reproduce the issue. It could be just simplified to a class with an interface as a proxy.

**Comment by hazzik** [comment]
Actually, this is just a bug in the documentation which has been introduced when we blindly replaced Loads with static strongly typed versions.

**Comment by hazzik** [comment]
>But the built proxy for the base class was also wrong in 4.x/5.0.x, it was also not inheriting from the base class.

As far as I can tell this was always implemented like this (since at least 3.2)

**Comment by hazzik** [comment]
I've made a pull request. But I think it can be wrong. And instead of "fixing" the code it would be better to fix the documentation.

The reasons why there is a thing as "proxy interface" is to provide an ability to use proxies for two types of classes:

- sealed classes with interface
- classes with non-virtual properties.

While the fix in the PR will work for sealed classes (as it would not allow to use generic version of the `Load` method with the sealed class and throw `InvalidCastException`), it will lead for incorrect behavior for classes with non-virtual properties:

consider following:
```csharp
interface Cat 
{
   int Id { get; set; }
   string Name { get;set; }
}

/// <class name="Cat" proxy="ICat" >
class Cat {
   public int Id { get; set; } // Intentionally non virtual !!!
   public string Name { get;set; } // Intentionally non virtual !!!
}

// Correct
ICat cat = session.Load<ICat>(id);

// Was throwing exception but now will load correctly but will lead to incorrect behavior.
Cat cat = session.Load<Cat>(id); 

// Correct
ICat cat = (ICat)session.Load(typeof(Cat), id);
```

**Comment by bahusoid** [comment]
>classes with non-virtual properties.
IMHO this is not a valid case. Our proxy validator will throw for such class.  Non virtual valid case is explicit interface implementation.

**Comment by bahusoid** [comment]
> The subclasses are not necessary to reproduce the issue. It could be just simplified to a class with an interface as a proxy.

I think it's two different cases. If user explicitly specifies that he wants interface as a proxy - it's OK that load throws on cast to object. As we do what was requested - proxy is based on interface and not class.

**Comment by bahusoid** [comment]
JFYI I've updated my previous comments as it seems we've been talking about different cases

**Comment by hazzik** [comment]
> IMHO this is not a valid case. Our proxy validator will throw for such class. Non virtual valid case is explicit interface implementation.

Perfectly valid case. Validator does not check classes themself if they have `proxy="..."` set in the mapping.

> I think it's two different cases.

Yes, they are semantically different. I realized the difference later, but it is really subtle.

**Comment by bahusoid** [comment]
>Perfectly valid case.
>I realized the difference later, but they are really subtle.

Yeah I updated my comments - I realized you were talking specifically about explicit mapping proxy as interface. But described problem is different - proxy was not specified for base class mapping.  See this case [here](https://github.com/nhibernate/nhibernate-core/pull/2066/files#diff-13f1ccc903de107ccbdb352b04bdc820R93)

**Comment by hazzik** [comment]
So basically the fix would be to correctly set `IsClassProxy` based on the mapping instead of vague logic of number of collected interfaces for the `ProxyFactoryFactory`.

**Comment by bahusoid** [comment]
I think in your example [here ](https://github.com/nhibernate/nhibernate-core/issues/2067#issuecomment-474189391) (and proxy is mapped as interface) cast exception is still needs to be thrown. But your test case in PR is valid one - as proxy for base class is not specified proxy should be based on `Cat` class.

But maybe I don't understand something. Could you please clarify expected proxy hierarchy.
For instance consider the following hierarchy in format EntityClass [ProvidedProxyClass]:
Base [Base] -> Derived1 [IDerived1] -> Derived2 [IDerived2]

I expect proxy for Base as:
`class BaseProxy : Base` <- cast to Base is allowed

for Derived1
`class Derived1Proxy: BaseProxy, IDerived1` <- cast to Derived1 is not allowed

for Derived2 
`Derived2Proxy : Derived1Proxy, IDerived2` <- cast to Derived2 is not allowed

**Comment by bahusoid** [comment]
Well my logic works nicely only with base class proxy.  I don't quite sure how hierarchy should look like without interface proxies:
Base [Base] -> Derived1 [Derived1] -> Derived2 [Derived2]

**Comment by bahusoid** [comment]
Nevermind.. I got it..  Base classes should be based on entities not on proxies..

**Comment by bahusoid** [comment]
> the fix would be to correctly set `IsClassProxy` based on the mapping

I'm not sure I understand how `IsClassProxy`  can help. If my last edit of expected hierarchy is correct it seems single bool property is not enough:
Derived2Proxy should be based on base Base class and implement both IDerived1 and IDerived2 interfaces that we have in hierarchy chain.

**Comment by hazzik** [comment]
I'm not sure I understand how `IsClassProxy` can help.

<details>
<summary>PocoEntityTuplizer collects proxy interfaces from all subclasses</summary>

https://github.com/nhibernate/nhibernate-core/blob/21846c017658e89af6c2d720b78624abf9acc064/src/NHibernate/Tuple/Entity/PocoEntityTuplizer.cs#L123-L151
</details>

So, with current logic (`ProxyInterfaces.Length == 1`) the `Cat` becomes an interface proxy. So, we need to say that it's interface _only_ if the interface proxy is declared in mapping.

**Comment by bahusoid** [comment]
> interface only if the interface proxy is declared in mapping.

But class or interface is not the only options - it can be both. For instance in my [example](https://github.com/nhibernate/nhibernate-core/issues/2067#issuecomment-474217299) `Derived2` class.  
It's mapped as interface `IDerived2`. But proxy should be based on `Base`. Are you sure it's handled in you latest changes?

**Comment by micmerchant** [comment]
Hi, 

I've added some testfixtures with base/subclass/lookup mappings, in the hope to be able to help a bit. These fixtures contain only one test and should target the various proxy combinations I can imagine. Short note, our schema is much more complicated than that, there is no mapping which implements only one interface. 

Anyway here is the list of combinations:
Base Class: No proxy contract; Sub Class: No proxy contract => doesn't fail
**Base Class: No proxy contract; Sub Class: Interface proxy contract => fails**
Base Class: Interface proxy contract; Sub Class: No proxy contract => doesn't fail
Base Class: Interface proxy contract; Sub Class: Interface proxy contract => doesn't fail

[BaseClassLookup.zip](https://github.com/nhibernate/nhibernate-core/files/2982802/BaseClassLookup.zip)

**Comment by bahusoid** [comment]
@micmerchant All your tests are passed with this PR applied #2070

**Comment by fredericDelaporte** [comment]
> Are you working on fixing it?

Not yet, but I was intending too, without knowing when.

> The subclasses are not necessary to reproduce the issue. It could be just simplified to a class with an interface as a proxy.

I have hidden the comments which seems to be some initial misunderstanding of the issue.

 > So basically the fix would be to correctly set `IsClassProxy` based on the mapping instead of vague logic of number of collected interfaces for the `ProxyFactoryFactory`.

Yes, that is the root of the bug.

**Comment by fredericDelaporte** [comment]
> > interface only if the interface proxy is declared in mapping.
>
>But class or interface is not the only options - it can be both. For instance in my [example](https://github.com/nhibernate/nhibernate-core/issues/2067#issuecomment-474217299) `Derived2` class.  
>Proxy is mapped as interface `IDerived2`. But  generated proxy should be based on `Base` and implement both base interfaces `IDerived1` and `IDerived2`. Are you sure it's handled in you latest changes?

When an entity mapping does not map its proxy as an interface, the generated proxy inherits the entity class and implements all the entity class interfaces. So it is "both" in such case, if you want to name it that way.
When an entity mapping does map its proxy as an interface, the proxy only implements the said interface (and the said interface inherited interfaces, of course). That is what this feature is meant for.

So to me, your comment looks like some misunderstanding on how "non-interface" proxies are implemented. They do already implements their base classes interfaces, if their base classes have interfaces.

Maybe some more comment hiding should be done to reduce the noise.

**Comment by bahusoid** [comment]
@fredericDelaporte Have you looked at my [example](https://github.com/nhibernate/nhibernate-core/issues/2067#issuecomment-474217299)? `Derived2` is  an "interface proxy" in there. 
I described expected hierarchy and asked to provide correct. As it turns out my expected hierarchy is wrong for interface mapping.

**Comment by fredericDelaporte** [comment]
Your example setup was not clear to me.

If your `Derived2` entity maps its proxy as `IDerived2`, the proxy should be `ProxyClass: IDerived2, INHibernateProxy`. Otherwise it should be `ProxyClass: Derived2, IDerived1, IDerived2`.
