### ISSUE TITLE
Support subclass mapping with EntityName based base class mapping

### ISSUE THREAD

**Issue by bahusoid** [nhibernate/nhibernate-core#2071]
There is currently no way to specify entityName for subclass base entity so subclass mapping can't find base mapping:
```C#
mapper.Class<EntityBase>(
	rc =>
	{
		rc.EntityName("EntityName");
		rc.Id(x => x.Id);
		rc.Property(x => x.Name);
	});

			
mapper.UnionSubclass<SubEntity>(
	rc =>
	{
		rc.Property(x => x.AnotherName);
	});
	
	
public class EntityBase
{
	public virtual Guid Id {get;set;}
	public virtual string Name {get;set;}
}

public class SubEntity : EntityBase
{
	public virtual string AnotherName {get;set;}
}
```

**Comment by hazzik** [comment]
Does it work in xml? If so, what's the syntax?

**Comment by bahusoid** [comment]
No. I didn't mention that it's Mapping By Code specific. It's not supported at all.

**Comment by hazzik** [comment]
Actually it is supported in XML via `extends="EntityName"`

**Comment by bahusoid** [comment]
Ok. Sorry.. To be honest I know very little about xml mapping

**Comment by hazzik** [comment]
WIP: https://github.com/hazzik/nhibernate-core/tree/gh-2071
