### ISSUE TITLE
Parsing String to Long (Int64)

### ISSUE THREAD

**Issue by byCrookie** [nhibernate/nhibernate-core#2083]
While testing my query I noticed that it is not possible to parse strings to Int64 directly in the query. Error message stated not to support string parsing to Int64. But String to Int32 is supported.

**Comment by fredericDelaporte** [comment]
NHibernate has many querying API. Can you tell with which ones have you seen the issue? And provide example queries.

**Comment by hazzik** [comment]
Closing as no reply.
