### ISSUE TITLE
NHibernate and optional (Maybe) values

### ISSUE THREAD

**Issue by kriewall** [nhibernate/nhibernate-core#2093]
I am trying to use NHibernate to map classes with optional values typed with a Maybe wrapper.   As described in [this article](http://kolotree.com/ddd/to-be-or-not-to-be-maybe/) I'm not able to find a way to do it.  Can you advise if and how NHibernate can support this use case?

I've put together a simple test project [here](https://1drv.ms/f/s!AsvM6Pyke4A6hj99PBapCSNskVvj) in case a starting point is helpful.

**Comment by bahusoid** [comment]
Maybe I don't get this `Maybe` values as I didn't read the article. But from the [code](https://onedrive.live.com/?authkey=%21AH08FqkJI2yRW-M&cid=3A807BA4FCE8CCCB&id=3A807BA4FCE8CCCB%21875&parId=3A807BA4FCE8CCCB%21832&o=OneUp) it seems NRE is just replaced with `InvalidOperationException`. So what's the point of replacing null check with some kind of other check? IMHO better use something like [nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types)

Regarding mapping I think your best option would be using [components](https://nhibernate.info/doc/nh/en/index.html#components-dependentobjects) for your `Maybe<T>` type with custom `IPropertyAccessor` implementation for dealing with your `MaybeValueWrapper`. 

But not sure if everything will work smoothly (for instance don't know if `<many-to-one>` is supported inside component) . You have to dig it yourself and create more specific feature request or bug. For now it looks like support question that should be asked somewhere else.

**Comment by hazzik** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
