### ISSUE TITLE
refresh  session , update only the modified mapping  file.

### ISSUE THREAD

**Issue by MrAnderson1989** [nhibernate/nhibernate-core#2098]
hi,

i am maintaining  a old project, it‘s base on nhibernate4 . 

there are too many mapping file to loaded in application_start , so, BuildSeesionFactory function will be running  for long time .

 and  the presistentClass will be modified  at runtime（so，BuildSeesionFactory again） , applicaiton will reload mapping file ,which cast lot of time .

Is there some way to refresh  session  . update only the modified mapping  file ?

Sorry for my English  , I tried my best to express it clearly.  :(

**Comment by fredericDelaporte** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
