### ISSUE TITLE
Xamarin .NET Standard 2.0.3 ConfigurationManager throws PlatformNotSupported exception in NHibernateLogger

### ISSUE THREAD

**Issue by CSmith1111** [nhibernate/nhibernate-core#2105]
i have a xamarin .net standard 2.0.3 project and try to use nhibernate with sqlite but get the error "System.PlatformNotSupportedException"

The error comes within this code from a .net standard 2.0.3 project:
```
    var cfg = new Configuration().DataBaseIntegration(db =>
      {
        db.Driver<SQLite20Driver>();
        db.Dialect<SQLiteDialect>();
        db.ConnectionString = "Data Source=test.db;Version=3;New=True";
      });
```
With just a (xunit) testproject and the nhibernate project this code works fine, but not if i want to start this code within an andorid system.

**Comment by hazzik** [comment]
You'll need to write own driver for SQLite.

**Comment by CSmith1111** [comment]
So SQLite is supported for Windows, Linux, MacOS and other .NET Standard platforms but not for Xamarin?

**Comment by hazzik** [comment]
If we're talking about System.Data.SQLite (this is what SQLiteDriver uses) then it supports only Windows, MacOS and Linux. Other platforms are not supported. The SQLite ADO.NET provider which supports Xamarin Android is Mono.Data.Sqlite, which is not supported by NHibernate by default. 

You can write own provider for it.

**Comment by CSmith1111** [comment]
i tried it like you mention it, but the error got thrown even befor nhibernate wants to load the driver.
is there something special to make your linked code work? i also tried to change the nhibernate.cfg.xml but same problem.
```       var cfg = new Configuration(); //here comes the error
      cfg.DataBaseIntegration(db =>
      {
        db.Driver<MonoSQLiteDriver>();
        db.Dialect<SQLiteDialect>();
        db.ConnectionString = "Data Source=test.db;Version=3;New=True";
      });

**Comment by bahusoid** [comment]
Try with [Mono.Data.Sqlite.Portable](https://www.nuget.org/packages/Mono.Data.Sqlite.Portable)

**Comment by CSmith1111** [comment]
> Try with [Mono.Data.Sqlite.Portable](https://www.nuget.org/packages/Mono.Data.Sqlite.Portable)

gives me 
`System.DllNotFoundException : Unable to load DLL 'sqlite3' or one of its dependencies: cant find the module. (Exception from HRESULT: 0x8007007E)` 
and 
`Warning	NU1701	Package 'Mono.Data.Sqlite.Portable 1.0.3.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
`

**Comment by hazzik** [comment]
You don't actualy need any packages. Mono.Data.Sqlite assembly is already part of Mono/Xamarin. You just need to add a reference to the project like this:

```xml
<Reference Include="Mono.Data.Sqlite" />
```

**Comment by CSmith1111** [comment]
[NHibernateSQLiteTest.zip](https://github.com/nhibernate/nhibernate-core/files/3058059/NHibernateSQLiteTest.zip)
This is my sample project, a basic cross-platform project with nhibernate and all of your hints.
I can't get it work.
Can you please take a look and say me whats the problem?

**Comment by hazzik** [comment]
What is the error?

**Comment by hazzik** [comment]
Ok, this is the `ConfigurationManager` throws `PlatformNotSupported` exception.

**Comment by CSmith1111** [comment]
yes, thats the problem in this issue.
thats why i should change to mono, but as you can see, its not that easy.

any idea who i can nhiberate to get working with mono in  this kind of project?

**Comment by jan-schubert** [comment]
Is the ConfigurationManager not usable for Android?
Does that mean it's not possible to use NHibernate for Android?

**Comment by hazzik** [comment]
This is the root cause: https://github.com/dotnet/corefx/issues/18832

**Comment by bahusoid** [comment]
You can try to use the following [binaries ](https://teamcity.jetbrains.com/viewLog.html?buildId=2157106&buildTypeId=NHibernate_NHibernateReleasePackage&tab=artifacts&branch_NHibernate=pull%2F1627#%2FNHibernate-5.2.5%2Fnuget_gallery) to make sure that `ConfigurationManager` is the only issue with Xamarin.

And add somewhere before session factory is created:
```C#
NHibernate.Cfg.Settings.ConfigurationManager = null;
```

**Comment by CSmith1111** [comment]
@bahusoid , looks good to me.
We also changed the SQLite driver to [Microsoft.Data.Sqlite.Core](https://www.nuget.org/packages/Microsoft.Data.Sqlite.Core/) coz thats what EntityFrameworkCore is using. Maybe that would be a good default sqlite driver?

**Comment by hazzik** [comment]
> Maybe that [Microsoft.Data.Sqlite.Core] would be a good default sqlite driver?

The Microsoft.Data.Sqlite.Core  misses a lot of features NHibernate depends upon (see #1638). So, we _could_ add this driver, but probably not.

**Comment by hazzik** [comment]
On version 5.3 and above to skip all configuration calls set ConfigurationProvider.Current to null:

    ConfigurationProvider.Current = null;
