### ISSUE TITLE
Statefull Session commit performance issue when nothing changed and second level cache with query cache enabled

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#2115]
Hi,
I realised a perfomance issue, we are using second level cache so we need a session and transaction by default. After data read commit occours thats fine but it tries to do something with 
> UpdateTimestampsCache

```c#
[MethodImpl(MethodImplOptions.Synchronized)]
public virtual void Invalidate(IReadOnlyCollection<string> spaces)
{
	//TODO: to handle concurrent writes correctly, the client should pass in a Lock
	long ts = _updateTimestamps.NextTimestamp();
	//TODO: if lock.getTimestamp().equals(ts)
	if (log.IsDebugEnabled())
		log.Debug("Invalidating spaces [{0}]", StringHelper.CollectionToString(spaces));
	SetSpacesTimestamp(spaces, ts);
}
```

As you can see above 

> [MethodImpl(MethodImplOptions.Synchronized)] is a problem if spaces is empty. There are other sync. methods some of them check spaces before calling sync method some not.
I think all of them need to check spaces before calling sync method for concurrency performance issue?

Below usage checks before calling sync method.

> StandartQueryCache
```c#
var upToDates = spacesToCheck.Count > 0
				? _updateTimestampsCache.AreUpToDate(spacesToCheck.ToArray(), checkedSpacesTimestamp.ToArray())
				: Array.Empty<bool>();
```

**Comment by hazzik** [comment]
Hi @gokhanabatay do you have any measured performance impacts?

**Comment by gokhanabatay** [comment]
Hi @hazzik;
.Net core 2.2, iis hosting web rest web api call
Oracle Exadata, min pool size 500, max pool size 1000, oracle resource limit session count 10000k
No text logging
%35-%50 cpu usage server

Test case 4 and 4.1 show me if I increase thread count somethings goes concurrency, there must be some other thing because when i disable second level cache, I did not see a valuable decrease of avg response time.

1. Scenario Connection open close with Redis Second Level Cache
![image](https://user-images.githubusercontent.com/9988911/55989019-00dc1900-5cae-11e9-9254-a1d7ac3f13e0.png)

2. Scenario Connection open transaction begin then commit and close  with Redis Second Level Cache
![image](https://user-images.githubusercontent.com/9988911/55989617-66300a00-5cae-11e9-931d-9d2df9e8585b.png)

3.  Scenario Connection open close with no cache
![image](https://user-images.githubusercontent.com/9988911/55989886-0b4ae280-5caf-11e9-9059-97d7030adcfa.png)

4. Scenario Connection open transaction begin then commit and close  with no cache
![image](https://user-images.githubusercontent.com/9988911/55990024-4d742400-5caf-11e9-8350-1e043122368c.png)

4.1. Scenario Connection open transaction begin then commit and close  with no cache 100 thread
![image](https://user-images.githubusercontent.com/9988911/55990652-e8213280-5cb0-11e9-96d4-1c6f14758992.png)

5. Scenario Connection open select full read (500 records) from some table and close connection without transaction
![image](https://user-images.githubusercontent.com/9988911/55990239-e440e080-5caf-11e9-9980-3e16e5dbc4c0.png)

And also is there any way to get results from second level cache one shot, I have an entity that has 400 records and it trys to get every record in list from redis second level cache. (n + 1 problem)

**Comment by gokhanabatay** [comment]
Hi @hazzik ,
I also realized that we are storing updatetimestampscache for non cache'ing entities. 
Is this really necessary in our scenario we use query cache for just Cache.ReadWrite or Cache.Readonly entities?

We need high performance to do that we need to decrease Sync. and locking for common dml/select operations.

> I think that this needs to be configurable(Store all entities updatetimestampscache or just cacheable entities) or we give us a way to implement our UpdateTimestampsCache? 

In distributed cache scenario there is a lot of cache call may be there would be a way to implement memory cache in front of second level cache?

**Comment by gokhanabatay** [comment]
@hazzik hi issue still exists when do you plan to merge and make a release.
