### ISSUE TITLE
Component property as interface is always null (mapping by code)

### ISSUE THREAD

**Issue by nfplee** [nhibernate/nhibernate-core#2121]
I have the following component defined:

```csharp
public interface IParameters {
    string Area { get; set; }
    string Controller { get; set; }
    string Action { get; set; }
}

public class Parameters : IParameters {
    public virtual string Area { get; set; }
    public virtual string Controller { get; set; }
    public virtual string Action { get; set; }
}

public class ParametersMap : ComponentMapping<Parameters> {
    public ParametersMap() {
        Property(x => x.Area);
        Property(x => x.Controller);
        Property(x => x.Action);
    }
}
```

Now if I have the following property:

```csharp
public virtual IParameters Parameters { get; set; }
```

Which is mapped like:

```csharp
Component(x => x.Parameters, m => m.Class<Parameters>());
```

Whenever I retrieve an entity for the class the property belongs to, the value for this property is always null. However if I change the property from an interface to a concrete type, like so:

```csharp
public virtual Parameters Parameters { get; set; }
```

Then it works fine.

**Comment by bahusoid** [comment]
I guess it would work if you map your component as interface
```C#
public class ParametersMap : ComponentMapping<IParameters> {
    public ParametersMap() {
        Class<Parameters>();
        Property(x => x.Area);
        Property(x => x.Controller);
        Property(x => x.Action);
    }

```
And component simply as `Component(x => x.Parameters);`

**Comment by nfplee** [comment]
Thanks, the first part works. I I had to leave the property mapping as:

```csharp
Component(x => x.Parameters, m => m.Class<Parameters>());
```

Otherwise I received the error:

> Cannot instantiate abstract class or interface: Parameters.IParameters

**Comment by bahusoid** [comment]
I'm not saying that is expected behavior. So just to confirm you've added as I suggested `Class<Parameters>();` to `ParametersMap` but it's ignored and need to be explicitly specified when property is mapped. Am I right?

**Comment by nfplee** [comment]
I changed my component mapping to:

```csharp
public class ParametersMapping : ComponentMapping<IParameters> {
    public ParametersMapping() {
        Property(x => x.Area);
        Property(x => x.Controller);
        Property(x => x.Action);
    }
}
```

However I had to leave the property mapped like:

```csharp
Component(x => x.Parameters, m => m.Class<Parameters>());
```

**Comment by nfplee** [comment]
Scratch that, I didn't see the "Class<Parameters>();" part on your original post. I've just added that and I was able to change the property mapping as you suggested. It's now working (albeit it seems a little funky). I'm not sure whether to close this as I don't know if this is the suggested behaviour.

**Comment by hazzik** [comment]
Closing as not an issue.
