### ISSUE TITLE
How to handle multiple result sets from stored procedure using NHibernate

### ISSUE THREAD

**Issue by ravi-darshankar** [nhibernate/nhibernate-core#2145]
Hi,

I am using Microsoft .Net platform and ORM as Nhibernate, is it possible to use multiple result sets using SP?

Thanks & Regards,
Ravi

**Comment by hazzik** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
