### ISSUE TITLE
SQL server is slow to query in views with query conditions.

### ISSUE THREAD

**Issue by www741147** [nhibernate/nhibernate-core#2150]
If no query conditions, the speed of query is normal in view.
But give some query conditions,it will become so slow.

And in sql management, it can be execute normally.
I don't know why,any suggestion?
It seems to be the data needs lots of time to map the entity.

NHibernate version is 5.2.5

**Comment by www741147** [comment]
mapping file:

<?xml version="1.0" encoding="utf-8"?>
<hibernate-mapping assembly="Project.Dal" namespace="Project.Dal" xmlns="urn:nhibernate-mapping-2.2">
  <class name="UVSYSUserRole" table="UV_SYS_UserRole" lazy="true" >
			<id name="KeyID">
	</id>

				<property name="UserID"    >
			<column name="UserID" sql-type="uniqueidentifier" not-null="true" />
		</property>
				<property name="UserName"    >
			<column name="UserName" sql-type="nvarchar" not-null="true" />
		</property>
				<property name="UserType"    >
			<column name="UserType" sql-type="int" not-null="true" />
		</property>
				<property name="Account"    >
			<column name="Account" sql-type="nvarchar" not-null="true" />
		</property>
				<property name="RoleID"    >
			<column name="RoleID" sql-type="uniqueidentifier" not-null="true" />
		</property>
				<property name="RoleName"    >
			<column name="RoleName" sql-type="nvarchar" not-null="true" />
		</property>
				<property name="RoleType"    >
			<column name="RoleType" sql-type="int" not-null="true" />
		</property>
				<property name="AppRoleRight"    >
			<column name="AppRoleRight" sql-type="nvarchar" not-null="false" />
		</property>
			</class>
</hibernate-mapping>

**Comment by www741147** [comment]
entity file:
namespace CH.Dal
{
    /// <summary>
    /// UV_SYS_ManageUnit_Culturalrelic
    /// </summary>
    [DataContract]
    public class  UVSYSManageUnitCulturalrelic{
        /// <summary>
        /// 主键
        /// </summary>
        [Display(Name="主键")]
        [DataMember]
        public virtual Int32	KeyID{get;set;}
        /// <summary>
        /// 管理单元ID
        /// </summary>
        [Display(Name="管理单元ID")]
        [DataMember]
        public virtual Nullable<Guid>	ManageUnitID{get;set;}
        /// <summary>
        /// 文物ID
        /// </summary>
        [Required(ErrorMessageResourceName = "IsRequired", ErrorMessageResourceType = typeof(Project.Common.Resources.MessageCode))]
        [Display(Name="文物ID")]
        [DataMember]
        public virtual Guid	FK_CulturalRelicID{get;set;}
    }
}

**Comment by gliljas** [comment]
NHibernate doesn't know whether it's a view or a table, and has no impact on the query performance.

**Comment by www741147** [comment]
Can be xml configuration is not appropriate?

I have a query with a result of 10000+ Guid. And it will be treated as a subquery.

If the subquery executed ToList(), then pass into the query.
It will tell me that I have too many parameters, the maxium is 2100.

**Comment by www741147** [comment]
I found adding OPTION (RECOMPILE) after generate statement executing normally.

And how to let nhibernate build OPTION (RECOMPILE)?

e.g:exec sp_executesql N'select ...'
=> exec sp_executesql N'select ... OPTION (RECOMPILE)'

**Comment by gliljas** [comment]
https://stackoverflow.com/questions/32778399/nhibernate-linq-add-query-hints

Closing, since this is a topic for the nhusers Google group or SO.
