### ISSUE TITLE
Insert not working with my own Dialect implementation

### ISSUE THREAD

**Issue by Robertofon** [nhibernate/nhibernate-core#2152]
I have found+improved a dialect/driver for ADS DBMS. Works fine so far however if it comes to inserting new records, NHibernate will not even try to issue an insert statement to the ADO.Net driver. What could this possibly be?
Is there somewhere a read-only flag that I overlooked?
Or a not noted (so I wont notice it's absence) capability "Insert" of the DBMS?

**Comment by fredericDelaporte** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).

You should likely provide more information in the post you may write on these groups, at least a link to the driver you have found.
