### ISSUE TITLE
SAP HANA and .NET Core

### ISSUE THREAD

**Issue by MMMMDCCXI** [nhibernate/nhibernate-core#2154]
Since version 5.2 NHibernate supports HANA as database system.
Is there a way to run it under .NET Core ?

SAP provides with the HANA Client Version 2.4 (HANA SPS04) a .NET Core driver.

**Comment by adrien-constant** [comment]
It's very useful @MMMMDCCXI thank you
Shouldn't it be part of nhibernate source code ? If running on .NET Core, using the .NET Core HANA driver by default. It would make sense.

**Comment by fredericDelaporte** [comment]
It could be better to publish a new Nuget package just for the driver, which could use explicit dependencies instead of relying on reflection. See #626.
