### ISSUE TITLE
New Fetch() method in QueryOver returns IQueryOver<> instead of QueryOver<>

### ISSUE THREAD

**Issue by jrauber** [nhibernate/nhibernate-core#2177]
In 

> Full control of entities fetching in Criteria (#1599)

 the new introduced method
 
`Fetch(SelectMode mode, Expression<Func<TSubType, object>> path)`

in `Criterion/QueryOver.cs` returns the `IQueryOvery<>` interface instead of the previously returned `QueryOver<>`. As a result, queries that are not already linked to the session cannot be transformed by calling `query.GetExecutableQueryOver(session)` because the interface does not provide the `GetExecutableQueryOver(session)` method.

**Comment by bahusoid** [comment]
Actually there is already extension method returning `QueryOver`. But it's hidden by interface implementation. So
as a workaround you can tell compiler to use extension by specifying param name explicitly:
```C#
queryOver.Fetch(SelectMode.Fetch, associationPaths: x => x.Child1).GetExecutableQueryOver()
```
