### ISSUE TITLE
SetSession(ISession session) is not invoked on an ISessionFactory-scoped interceptors

### ISSUE THREAD

**Issue by YevhenLukomskyi** [nhibernate/nhibernate-core#2202]
`OpenSession()` doesn't invoke `SetSession(ISession session)` on an ISessionFactory-scoped interceptors. It works when an interceptor is registered on a session level,
It is reproducible in NHibernate 5.2.5

**Comment by fredericDelaporte** [comment]
There is a reason for this: a session factory can be used in multi-threaded context, it has to be thread safe.
So a session factory interceptor cannot have the session, it will cause it to be not thread safe.
