### ISSUE TITLE
Reuse of named query from ISession ignores new parameter values

### ISSUE THREAD

**Issue by zabeda** [nhibernate/nhibernate-core#2204]
Ran into an odd issue, but did figure out a temporary work around. We have a named query that calls a stored procedure. It works fine with the first call and returns the results as expected. If the named query is used again in the same session, the same result from the first execution is returned even though the parameters have changed.  

We are using version 5.2.5.  During testing we used SQL Server 2008, 2012 and 2019.

We were able to get this work by switching to use a stateless session.  After the change, the query would execute each time and return the expected results for the given inputs.  I am not very familiar with the underlying codebase for NHibernate, but have started looking to see if I can track down the cause.  If I find anything, I will make sure to post here.  Open to suggestions on where to look also.

```
// sample of usage
var result1 = pbdsQuery.RetrieveSummary(acctId, startDate, endDate);

// run again with different date range
var result2 = pbdsQuery.RetrieveSummary(acctId, startOfYear, endDate);

/// From Query Class
public PaymentBreakDownSummary RetrieveSummary(string acctId, DateTime startDate, DateTime endDate)
{
   // Changing the ISession to an IStatelessSession prevents the issue from occurring and
   // the query is re-executed with the new parameters.
    var query = m_session.GetNamedQuery(QUERY_NAME);
            
    query.SetAnsiString("pAcctid", acctId);
    query.SetDateTime("pStartDate", startDate);
    query.SetDateTime("pEndDate", endDate);

    return query.UniqueResult<PaymentBreakDownSummary>();
}
```
sql-query element from the hbm.xml file:
```
  <sql-query name="PaymentBreakDownSummaryQuery">
    <return class="PaymentBreakDownSummary, PRJ.DAL">
      <return-property column="AcctId" name="AcctId" />
      <return-property column="StartDate" name="StartDate" />
      <return-property column="EndDate" name="EndDate" />
      <return-property column="TotalPayments" name="TotalPayments" />
      <return-property column="TotalFinanceCharges" name="TotalFinanceCharges" />
      <return-property column="TotalFees" name="TotalFees" />
    </return>
        exec [acm].[sp_PaymentBreakdown] :pAcctid, :pStartDate, :pEndDate
  </sql-query>

```

Thanks,
zbd

**Comment by bahusoid** [comment]
We've had something similar with LINQ queries in #1363

**Comment by fredericDelaporte** [comment]
I think the behavior is expected indeed, once you understand the session semantic.
It looks to me you are loading in both case a `PaymentBreakDownSummary` class with the same id, `acctId`. If `acctId` is declared as the id of `PaymentBreakDownSummary`, then from the session point of view, both query are returning the same entity, thus the behavior you have seen.

Without your mappings, name query code, ..., I am just guessing, so it is always better to provide a complete repro. It does not need to be your exact code, it even should not. It should just be a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

But if you can confirm that is your trouble, you can then just close this issue. (And then bottom line is : do not declare as an id something that is not unique for different entities.)

**Comment by zabeda** [comment]
@fredericDelaporte, I just looked and AcctId is mapped as the id.  So, your explanation fits this situation.  My apologies for not providing the mapping or a reproducible example with my initial submission. I will keep that in mind for the future, if it ever comes up. 

Thank you for helping to clear this up and your work on the project.

**Comment by zabeda** [comment]
In case others happen to make the same mistake, I am posting the changes that were made to correct the problems in our code.  

1.  We needed the query to run every time it was called and the PaymentBreakDownSummary class was only used to store the query results, so we deleted the hbm.xml class mapping but kept the class.  The return element from the sql-query mapping was also removed.    
```
  <sql-query name="PaymentBreakDownSummaryQuery">
        exec [acm].[sp_PaymentBreakdown] :pAcctid, :pStartDate, :pEndDate
  </sql-query>
```
2. With the mappings removed, we changed the query to use SetResultTransformer, which converts the query output into the summary class for us.
```
var query = m_session.GetNamedQuery(QUERY_NAME);

query.SetAnsiString("pAcctid", acctId);
query.SetDateTime("pStartDate", startDate);
query.SetDateTime("pEndDate", endDate);

query.SetResultTransformer(
    NHibernate.Transform.Transformers.AliasToBean<PaymentBreakDownSummary>());

return query.UniqueResult<PaymentBreakDownSummary>();
```

After making these changes, the process worked as expected with the query executing each time. Hope this helps.
