### ISSUE TITLE
SelectMany Linq extension does not work correctly - subsequent FetchMany fails

### ISSUE THREAD

**Issue by v-kabanov** [nhibernate/nhibernate-core#2244]
Looks like parent entity remains in resolution context after going to child collection with SelectMany:

`            Assert.DoesNotThrow(() => parentQuery.SelectMany(x => x.Children)
                .FetchMany(x => x.GrandChildren)
                .ToFuture());`

FetchMany() tries to resolve 'GrandChildren' property on the parent entity and fails.
Here's the failing test: https://github.com/v-kabanov/Nh526QueryBug/blob/master/MyTest.cs

**Comment by no149** [comment]
Why do you need to use SelectMany in that example? 
You could use FetchMany() instead and then ThenFetchMany() to get the GrandChildren.

**Comment by v-kabanov** [comment]
SelectMany is useful whenever you need to get a query for child collection members having a query for parent entities - it is the simplest and most concise way, producing simple and easy to read SQL. Also, it would help encapsulating query building in respective repository classes/helpers and avoid duplicating code.

One of the things I use it for is eager loading via futures. FetchMany would read and transfer parent entity rows which is redundant.

There are certainly ways to work around the issue, notably using subqueries via 'Contains' which I currently use instead of 'SelectMany'.

**Comment by v-kabanov** [comment]
Another example - incorrect query is generated for
```
HashSet<ProductDefinition> SelectedProductDefinitions { get; }
...
query.Where(x => (SelectedProductDefinitions.Contains(x.ProductionRequest.ProductDefinition)
	 && SelectedProductDefinitions.Select(y => y.MaterialDefinition).Contains(x.MaterialDefinition))
	 || (SelectedProductDefinitions.Contains(x.ParentMaterial.ProductionRequest.ProductDefinition)
	 && SelectedProductDefinitions.Select(y => y.MaterialDefinition).Contains(x.ParentMaterial.MaterialDefinition)));
```
`.Select(y => y.MaterialDefinition)` is ignored and IDs of product definitions are inserted into the list of material definitions, i.e. SQL contains query to the effect of `... where MaterialDefinitionId in (ProductDefinitionId1, ProductDefinitionId2, ...)`. IDs of both entities are integers and no error or warning is raised.

The issue affects 'Select' as well as 'SelectMany' and not only at compile time. It is a severe one warranting immediate downgrade if a recent version is free of it.

**Comment by bahusoid** [comment]
> Another example - incorrect query is generated

It looks like completely different issue.  You should report it as new one. 
Also it's better move all in-code calculations out of  query. It will make query parsing more robust and reliable. I mean:
```C#
var materialDefinitions =  SelectedProductDefinitions.Select(y => y.MaterialDefinition);
//and in query use 
materialDefinitions.Contains(x.MaterialDefinition)
```

> It is a severe one warranting immediate downgrade if a recent version is free of it.

I don't get it. Is it working on some older version?

**Comment by v-kabanov** [comment]
I suspect underlying issue behind 'FetchMany' and 'Select' is the same.
Was hoping it was a recent regression, but unfortunately all 5.x versions are effected and downgrading to v4 is not a good option.
I added sample unit test: https://github.com/v-kabanov/Nh526QueryBug/blob/68498cf1f440db8694474f1b55a5efa31be2ae41/MyTest.cs#L207
Will try to move it into NH repository, it does not require any database schema to exist, unless I misunderstand NhLinqExpression.

**Comment by bahusoid** [comment]
Did my suggestion fixes your second issue? Did I get it right that  `SelectedProductDefinitions` is not a mapped entity property?

**Comment by bahusoid** [comment]
Regarding unit test. Don't need to add `NhLinqExpression`  or any other internal stuff here. Just make it test that required entity is retrieved from query.

> Will try to move it into NH repository
Other option to use this [template](https://github.com/nhibernate/nhibernate-core-testcase) for preparing test case.

**Comment by v-kabanov** [comment]
> Did my suggestion fixes your second issue? Did I get it right that `SelectedProductDefinitions` is not a mapped entity property?

I was not asking for a workaround - it was not a problem. SelectedProductDefinitions was not a mapped property. Do you mean that if it were mapped there would be no issue?

Speaking of unit tests what's wrong with using NhLinqExpression, that's a public class and those are unit, not integration tests? Especially if it helps find the exact issue. Integration test might even succeed in this case if IDs happen to match by coincidence.

**Comment by bahusoid** [comment]
>That's a public class and those are unit, not integration tests

We use integration tests mostly. We might change `session.Query` processing to not use `NhLinqExpression` or `ASTQueryTranslatorFactory` or some other dependency that you explicitly create in your test. So we might break `session.Query` processing for your case but your test wouldn't catch it.

**Comment by bahusoid** [comment]
> Do you mean that if it were mapped there would be no issue?

I mean it's completely different processing. So most likely different issues

**Comment by v-kabanov** [comment]
> > Do you mean that if it were mapped there would be no issue?
> 
> I mean it's completely different processing. So most likely different issues

Ok, thanks, that might explain why I have not noticed the issue in numerous complex queries in the project yet. They would be a real PITA to review, retest and rewrite.

**Comment by v-kabanov** [comment]
New issue #2276 created for the latter test case with collection parameter.

**Comment by resc** [comment]
I've encountered something similar.
The workaround seems to be to use unique lamba parameter names.
Calling function:
```
var ids = q.ApplySort(req).ApplyPaging(req).Select(x => x.Id).ToFuture().ToList();
var ocrs = session.FetchOcrWithChildren(s => s.Query<Db.Ocr>().Where(x => ids.Contains(x.Id))).ToList();
```
Extension method which fails if `containers.FetchMany(c1 => c1.Values).ToFuture();` is replaced with `containers.FetchMany(x => x.Values).ToFuture();`
     
```
        public static IList<Ocr> FetchOcrWithChildren(this ISession session, Func<ISession, IQueryable<Ocr>> ocrQuery)
        { 
            var ocrs = ocrQuery(session);

            // ==== timestamps =====
            ocrs.FetchMany(o1 => o1.MessageTimestamps).ToFuture();

            // ==== properties =====
            ocrs.FetchMany(o2 => o2.Properties).ToFuture();

            // ==== vehicle =====
            var vehicle = ocrs.Select(o3 => o3.Vehicle);
            vehicle.FetchMany(v1 => v1.Values).ToFuture();

            // ==== containers =====
            var containers = ocrs.SelectMany(o4 => o4.Containers);
            containers.FetchMany(c1 => c1.Values).ToFuture();
            containers.FetchMany(c2 => c2.Properties).ToFuture();
            ocrs.FetchMany(o5 => o5.Containers).ToFuture();

            // ==== trailers =====
            var trailers = ocrs.SelectMany(o6 => o6.Trailers);
            trailers.FetchMany(t1 => t1.Values).ToFuture();
            trailers.FetchMany(t2 => t2.Properties).ToFuture();
            ocrs.FetchMany(o7 => o7.Trailers).ToFuture();

            return ocrs
                .Fetch(o8 => o8.Lane)
                .Fetch(o9 => o9.Vehicle).ToFuture().ToList();
        }
```
stack trace:
```
NHibernate.QueryException: could not resolve property: Values of: Data.Entities.Ocr [.FetchMany[Data.Entities.Container, Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null,Data.Entities.ContainerValue, Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null](.SelectMany[Data.Entities.Ocr, Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null,Data.Entities.Container, Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null](.Where[Data.Entities.Ocr, Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null](NHibernate.Linq.NhQueryable`1[Data.Entities.Ocr], Quote((x, ) => (p1.Contains(x.Id, ))), ), Quote((o4, ) => (o4.Containers)), ), Quote((x, ) => (x.Values)), )]
    at NHibernate.Persister.Entity.AbstractPropertyMapping.ToType(String propertyName)
   at NHibernate.Persister.Entity.AbstractEntityPersister.ToType(String propertyName)
   at NHibernate.Hql.Ast.ANTLR.Tree.FromElementType.GetPropertyType(String propertyName, String propertyPath)
   at NHibernate.Hql.Ast.ANTLR.Tree.DotNode.GetDataType()
   at NHibernate.Hql.Ast.ANTLR.Tree.DotNode.PrepareLhs()
   at NHibernate.Hql.Ast.ANTLR.Tree.DotNode.Resolve(Boolean generateJoin, Boolean implicitJoin, String classAlias, IASTNode parent)
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.CreateFromJoinElement(IASTNode path, IASTNode alias, Int32 joinType, IASTNode fetchNode, IASTNode propertyFetch, IASTNode with)
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.joinElement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromElement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromElementList()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.fromClause()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.unionedQuery()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.query()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.selectStatement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.statement()
   at NHibernate.Hql.Ast.ANTLR.HqlSqlTranslator.Translate()
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.Analyze(String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.DoCompile(IDictionary`2 replacements, Boolean shallow, String collectionRole)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IASTNode ast, String queryIdentifier, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.GetPreparedQuery(Expression expression, NhLinqExpression& nhExpression)
   at NHibernate.Multi.LinqBatchItem.GetForQuery[TResult](IQueryable query, Expression ex)
   at NHibernate.Multi.LinqBatchItem.Create[T](IQueryable`1 query)
   at NHibernate.Multi.QueryBatchExtensions.For[TResult](IQueryable`1 query)
   at NHibernate.Multi.QueryBatchExtensions.AddAsFuture[TResult](IQueryBatch batch, IQueryable`1 query)
   at NHibernate.Linq.LinqExtensionMethods.ToFuture[TSource](IQueryable`1 source)
```

**Comment by ramarivera** [comment]
Hi @resc and @maca88. I understand this issue is closed, but I would appreciate some guidance as to where the issue is so I can maybe write a PR.
Basically, my case is exactly the same as the one described by resc on his comment (https://github.com/nhibernate/nhibernate-core/issues/2244#issuecomment-569649882) but instead of having a FetchMany after my SelectMany, I have a Where, which should be applying some condition on the "child entities" fetched with SelectMany, but instead it's being applied on the Parent entities. And just as resc, if I change the lambda parameter name, the issue goes away.

Could you point me to which part of the source code I should take a look at (didn't see any ProcessWhere after a quick look on the ResultOperatorProcessors Folder)?

**Comment by resc** [comment]
Hi Ramiro,

From the updates on my issue I understand there should have been added
regression tests somewhere for this issue, maybe you can start  there, and
add a failing one for your case?

That's all the hints I can give you I'm afraid.
 I'm not familiar with the codebase of NHibernate.

Regards
Remco

Op vr 24 jul. 2020 06:54 schreef Ramiro Rivera <notifications@github.com>:

**Comment by maca88** [comment]
@ramarivera the issue should be fixed by #2323. Did you update NHiberate to `5.3.0` to see if the issue is still present?

> Could you point me to which part of the source code I should take a look at

`ProcessFetch`: https://github.com/nhibernate/nhibernate-core/pull/2323/files#diff-982c11f80016d47b4e478d607cc2c8d5R18

**Comment by ramarivera** [comment]
Thanks @resc !
I haven't had the time to update yet to 5.3.0 @maca88 , but I was wondering specifically about the SelectMany/Where combination as I mentioned in my comment. I am not using Fetch nor FetchMany, yet I still have a similar issue where the Where method tries to apply the lambda to the Parent entities instead of the Children entities retrieved with SelectMany.

I will take a look if this still happens with 5.3.0 as you suggested, and if it does I'll create a new issue, cause this one is already closed since it was about a bug with FetchMany, sounds good?

**Comment by maca88** [comment]
> I will take a look if this still happens with 5.3.0 as you suggested, and if it does I'll create a new issue, cause this one is already closed since it was about a bug with FetchMany, sounds good?

Yes.
