### ISSUE TITLE
The timeout period elapsed prior to obtaining a connection from the pool

### ISSUE THREAD

**Issue by ravidhole** [nhibernate/nhibernate-core#2256]
We are using below NHibernate version with Fluent NHibernate configuration 
NHibernate version: 3.3.2.4000 
NHibernateProfiler: 4.0.4049 

We are mostly getting below issues whenever we are processing huge data
1. Deadlock
2. Sql not available
3. The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

Tried to search for connection pooling option but could not find the option in configuration.  
Is there way so that we can set connection pool size more than 100? 
Could you please provide needful information.

**Comment by hazzik** [comment]
Please consult to the underlying ADO.NET connection provider documentation.

**Comment by ravidhole** [comment]
How we can increase the connection pool size in fluent nhibernate configuration? do we have to mentioned this in connection string only pooling=true and max pool size?

**Comment by ravidhole** [comment]
could not see any documentation related to this topic? hence raised the issue

**Comment by ravidhole** [comment]
Hi team,
How we can increase the connection pool size using Fluent In Nhibernate
configuration?

**Comment by hazzik** [comment]
It really depends on the ADO.NET Provider implementation. For SQL Server these are [`Max Pool Size` and `Min Pool Size`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.8) properties on connection string.

**Comment by ravidhole** [comment]
It means that Nhibernate is using those properties if we mentioned in Sql connection string. 
Pooling=true; 
Max Pool Size=25;
Please confirm.

**Comment by hazzik** [comment]
NHibernate does not have a notion of the connection pooling at all. All pooling is done by the ADO.NET Provider. So, yes, you can say that NHibernate uses whatever options provided in the connection string.
