### ISSUE TITLE
NHibernate.StaleObjectStateException: Row was updated or deleted by another transaction

### ISSUE THREAD

**Issue by sipirakesh** [nhibernate/nhibernate-core#2258]
below method not able to handle concurrency and throwing exception  (NHibernate.StaleObjectStateException: Row was updated or deleted by another transaction)

In hibernate xml i am using `<version name="DBVersion" column="DBVersion" type="Int64" generated="never" unsaved-value="0"/>`
```C#
        public void Save(Object o)
        {
            try
            {
                // Check to make sure a session has been started, if not open a new session
                if (_session == null)
                    _session = GetSession();

                // Connect to the DB if necessary
                ReconnectDBConnection();
                // Start a transaction
                BeginTransaction();
                // save
                _session.SaveOrUpdate(o);
                // commit
                CommitTransaction();
            }
            catch (NHibernate.StaleStateException e)
            {
                string msg = "DB Stale data error.  Reason: " + e.ToString();
            //show error message
                throw new ExceptionDatabaseStaleData(msg, e);
            }
```

**Comment by sipirakesh** [comment]
I am using optimistic-lock="true" in Nhibernate

**Comment by hazzik** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
