### ISSUE TITLE
SessionFactoryImpl swallows/ignores errors from SchemaExport

### ISSUE THREAD

**Issue by erizzo** [nhibernate/nhibernate-core#2259]
When using the "hbm2ddl.auto" property in a Configuration and then calling Configuration.BuildSessionFactory(), SessionFactoryImpl creates and invokes a SchemaExport. Problem is, any errors/exceptions that come from that SchemaExport execution are ignored by SessionFactoryImpl. There should be a way for them to be exposed to calling code so the application can decide what to do.
In fact it seems very _unlikely_ to me that any application that's using auto-update would ever want such errors to be ignored.

Perhaps a property on Configuration to at least fail fast if the SchemaExport has anything in its Exceptions property. I can think of more flexible/extensible options, but the ability to make schema update errors a fatal situation would be helpful.

**Comment by erizzo** [comment]
Code in question is https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Impl/SessionFactoryImpl.cs#L355

Where it creates a new SchemaExport instance, calls Execute() on it, but never checks for exceptions.

**Comment by fredericDelaporte** [comment]
On principle I would say this is a bug. But maybe some application having some failing auto-update which they do not need would be broken by switching to throwing.
So I think, for having it in 5.x release, this changes need to be done as a new configuration option thus "New Feature" typing), not enabled by default, likely with a `// 6.0 TODO : enable this option by default` since we allow breaking changes in a major release.

**Comment by no149** [comment]
Can I take this up or is the OP going to handle it himself?

**Comment by no149** [comment]
@fredericDelaporte 
So the SchemaUpdate class needs to be edited to have a property called e.g HasError that is a function of the Exceptions property.
Also, the Settings and the SettingsFactory classes need to be modified to include and work with the new 'ThrowOnSchemaExportError' property.
The HasError property will then only be checked [here](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Impl/SessionFactoryImpl.cs#L355) if the ThrowOnSchemaExportError property of the Settings object is true.

Is that the correct procedure?

**Comment by fredericDelaporte** [comment]
> So the SchemaUpdate class needs to be edited to have a property called e.g HasError that is a function of the Exceptions property.

I do not see the need for an additional property. Checking `SchemaUpdate.Exceptions.Count` should be good enough.

> Also, the Settings and the SettingsFactory classes need to be modified to include and work with the new 'ThrowOnSchemaExportError' property.

Usually yes, though some cases do not need it. You will see while coding whether it is needed or not. (I have not checked, bit it seems very likely you will have to.)
In any case, a matching .cfg configuration property should be added, declared in `Cfg.Environment` class like [here](https://github.com/nhibernate/nhibernate-core/blob/d1ef4edec5a86fe2b1fc3c8daf8b42cbf8bc06ed/src/NHibernate/Cfg/Environment.cs#L195) and in [nhibernate-configuration.xsd](https://github.com/nhibernate/nhibernate-core/blob/d1ef4edec5a86fe2b1fc3c8daf8b42cbf8bc06ed/src/NHibernate/nhibernate-configuration.xsd#L126), and used like [here](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Cfg/SettingsFactory.cs#L150).
But to be complete, other configuration API (Loquacious) should also be adjusted to handle that new setting. (Loquacious has two variants, one fluent and the other not; do not update its interfaces: modifying an interface is always is a breaking change, and we have obsoleted them to cease being hindered by having to avoid breaking changes.)

**Comment by no149** [comment]
I thought of adding the HasError property as an encapsulation of the
underlying error state. But if you don't deem it as necessary, then so be
it. :-)
I'll start working on it within the next week or so.

‫‪Frédéric Delaporte‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۶
نوامبر ۲۰۱۹ ساعت ۲۳:۵۳ نوشت:‬
