### ISSUE TITLE
Mock IQueryable that calls ToListAsync

### ISSUE THREAD

**Issue by nfplee** [nhibernate/nhibernate-core#2260]
Could you add a way to Mock an IQueryable that calls ToListAsync? For example if I run the following:

```
var session = new Mock<ISession>();
var collection = new List<Entity>().AsQueryable();
session.Setup(s => s.Query<Entity>()).Returns(collection);
var result = session.Object.Query<Entity>().ToListAsync();
```

This gives the error:

> System.NotSupportedException : Source Provider must be a INhQueryProvider

**Comment by fredericDelaporte** [comment]
Maybe the easiest way would be to support a "linq-to-object" source provider into our current [`LinqExtensionMethods`](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Linq/LinqExtensionMethods.cs).
By example, for the `ToListAsync` case, it would just yield something like a `Task.FromResult(queryable.Tolist())` when the source is not a `INhQueryProvider`. And other methods would likewise call their linq-to-object counterpart.

For still throwing on dev mistakes, it should not be enabled by default, but maybe enabled through some "system level property". (As extension methods are static, there is no way to bind this behavior to a configuration instance.)

**Comment by nfplee** [comment]
That sounds like the way to go. I've changed my code to the following for now:

```
var query = _session.Query<Entity>();
                
if (!(query.Provider is INhQueryProvider))
    return query.ToList();

return await query.Fetch(n => n.Parent).ToListAsync();
```

I was going to define my own extension method but using Fetch also threw an exception aswell.

**Comment by nfplee** [comment]
Just a quick note to say WithOptions also throws the exception:

> System.NotSupportedException : The query.Provider does not support setting options. Please implement IQueryProviderWithOptions.

I guess this is the case for any of the extension methods in the NHibernate.Linq namespace.

**Comment by no149** [comment]
@fredericDelaporte I'm willing to contribute. What do you suggest to do for the mock mode?
A static property on the LinqExtensionMethods class or a parameter for all the methods in the class?

Or maybe a more generic approach to enable mocking mode on a higher level?

**Comment by fredericDelaporte** [comment]
I was thinking about a static property, but likely on [`Environment`](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Cfg/Environment.cs) although I am not settled on this.
The [`LinkExtensionsMethods`](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Linq/LinqExtensionMethods.cs) would then check that property before throwing any `NotSupportingException`, and if needed, default to the sync counterpart of the called method. (Or just yield the queryable for cases like fetches, set options, ...)

I will most likely be against adding a parameter to all methods: it would be too intrusive for the regular use case. Is there any need for a granular control of this "throw/ignore the trouble" option anyway?

> Or maybe a more generic approach to enable mocking mode on a higher level?

What do you have in mind?

**Comment by hazzik** [comment]
I don't understand what are you trying to achieve, @nfplee? It seems like very useless activity to try to mock IQueryable which will ultimately lead to the latent and hidden bugs. Linq is a leaky abstraction. All providers and databases have some subtle differences. It means that you have to test queries on the SAME provider which you will use in production.

**Comment by hazzik** [comment]
Does this work for you?
```csharp
var entities = new List<Entity> {new Entity()};

var queryableProviderMock = new Mock<IQueryProvider>();
queryableProviderMock.As<INhQueryProvider>()
                     .Setup(x => x.ExecuteAsync<IEnumerable<Entity>>(It.IsAny<Expression>(), It.IsAny<CancellationToken>()))
                     .ReturnsAsync(entities);

var queryableMock = new Mock<IQueryable<Entity>>();
queryableMock.Setup(x => x.Provider).Returns(queryableProviderMock.Object);

var session = new Mock<ISession>();
session.Setup(s => s.Query<Entity>()).Returns(queryableMock.Object);

var result = await session.Object.Query<Entity>().ToListAsync();
Assert.That(result.Count, Is.EqualTo(1));
```

**Comment by nfplee** [comment]
@hazzik thanks I didn't think to mock the query provider. However that worked fine for a simple query but when I added an OrderBy it threw the following exception:

> Message:
> 	System.ArgumentNullException : Value cannot be null. (Parameter 'arg0')
> Stack Trace: 
>     Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
>     EagerFetchingExtensionMethods.CreateFluentFetchRequest[TOriginating,TRelated](MethodInfo currentFetchMethod, IQueryable`1 query, LambdaExpression relatedObjectSelector)
>     EagerFetchingExtensionMethods.Fetch[TOriginating,TRelated](IQueryable`1 query, Expression`1 relatedObjectSelector)
> 

Adding a Fetch threw a similar exception:

> Message:
> 	System.ArgumentNullException : Value cannot be null. (Parameter 'arg0')
> Stack Trace: 
>     Expression.Call(Expression instance, MethodInfo method, Expression arg0, Expression arg1)
>     Queryable.OrderBy[TSource,TKey](IQueryable`1 source, Expression`1 keySelector)

Finally WithOptions thew the exception:

> Message:
> 	System.NotSupportedException : The query.Provider does not support setting options. Please implement IQueryProviderWithOptions.
> Stack Trace: 
>     LinqExtensionMethods.WithOptions[T](IQueryable`1 query, Action`1 setOptions)

I'm not sure if there's something internal which will stop this from working. I'll try a few things to see if I get any joy, i'll reply here if I do. Mocking is quite new to me as I only realized recently all my "unit" tests were actually integration tests.

**Comment by bahusoid** [comment]
I'm also not much into mocking but I've seen test in our codebase where we mock underlying `IQuery.List` instead: 
https://github.com/nhibernate/nhibernate-core/blob/ac39173567b31bcfad475ca32687c9faf0d37f87/src/NHibernate.Test/Linq/ByMethod/WithOptionsTests.cs#L51-L83

**Comment by nfplee** [comment]
It doesn't look like you can mock the static extension methods so I have resorted to creating my own extension methods which call the original ones if the query provider is an INhQueryProvider. I guess an internal change will need to be made to enable this.

**Comment by no149** [comment]
> I don't understand what are you trying to achieve, @nfplee? It seems like very useless activity to try to mock IQueryable which will ultimately lead to the latent and hidden bugs. Linq is a leaky abstraction. All providers and databases have some subtle differences. It means that you have to test queries on the SAME provider which you will use in production.

@fredericDelaporte 
With regards to this comment, do you think it is rational to add such a feature?
In my opinion, it can be useful in certain scenarios where you only need to test the functionality of e.g the business layer without going through the hassle of setting up the data access layer and the data entry.

**Comment by fredericDelaporte** [comment]
Actually, I do not really know. I am not convinced by "true" unit testing, I mainly use integration tests. 

Most of NHibernate tests are integration tests, by the way. The main drawback from my viewpoint is their execution time, which in some cases is a bit excessive in regard to what the test is actually meant for. But only a few tests uses mocking, alleviating this drawback. In fact, it seems good enough for us that way.

So, I do not have a thorough experience in mocking. I am not able of telling if we really should make these extensions more mocking friendly, or if that is on the mocker side that something else should be done.

**Comment by nfplee** [comment]
My personal need is that I'd like to inject an ISession into a service and test the service without actually testing NHibernate as I know what the session will return. This is faster and allows me to test just the particular unit of code I'm interested in.

See the following for a similar issue for Entity Framework:

https://stackoverflow.com/questions/41324783/unit-testing-tolistasync-using-an-in-memory

I can't get a solution for NHibernate working because of the use of extension methods.

**Comment by hazzik** [comment]
I believe this is a wrong solution for a particular problem.
