### ISSUE TITLE
session.Replicate() doesn't perform idendity insert

### ISSUE THREAD

**Issue by AxxlForce** [nhibernate/nhibernate-core#2261]
When I'm using session.Replicate it does not insert the identifier of the entities but instead generates new ones which is in contradiction to the documentation and breaks my application. The DB I want to replicate to is Postgres.

NHibernate Version is 4.0.0.4000

**Comment by fredericDelaporte** [comment]
The `identity` case is not supported, and the xml documentation should be updated to reflect this.

Inserting into an `identity` column is a maintenance task that most ORMs will likely never carry out.

**Comment by hazzik** [comment]
https://hibernate.atlassian.net/browse/HHH-2716

**Comment by hazzik** [comment]
Duplicate of #861
