### ISSUE TITLE
How to use TransactionScope

### ISSUE THREAD

**Issue by satishviswanathan** [nhibernate/nhibernate-core#2269]
I'm trying to use TransactionScope With Nhibernate. Is there any example with configuration settings to get it working. 

Framework: .Net core 3.0

Sample code 
**************
Fluently.Configure()
                .Database(
                    OracleManagedDataClientConfiguration.Oracle10.ConnectionString(connectionString))
                .Mappings(cfg =>
                {
                    cfg.FluentMappings.AddFromAssemblyOf<NHibernateSessionSource>();
                }).BuildConfiguration();

using(var tx = new TransactionScope(TransactionScopeOption.Required))
{
    // update model
   _session.Flush();
  tx.Complete();
}

I'm getting no errors but the record doesn't get committed. I'm pretty new to NHibernate and any help is highly appreciated !!

**Comment by fredericDelaporte** [comment]
You have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).

But better check before hand the documentation, see [here](https://nhibernate.info/doc/index.html), especially the [transaction chapter](https://nhibernate.info/doc/nhibernate-reference/transactions.html) and its [section about scopes](https://nhibernate.info/doc/nhibernate-reference/transactions.html#transactions-scopes).
