### ISSUE TITLE
IQueryOver<T> is lacking some options

### ISSUE THREAD

**Issue by smarts** [nhibernate/nhibernate-core#2270]
Compared to criteria, QueryOver is lacking methods for setting the timeout, comments and fetch size. They are available through the underlying criteria, but a direct mean for setting them would be better.

Original Title: Documentation does not detail how to set timeout on IQueryOver<T>
Original description: Title should be self explanatory. If [this](https://gist.github.com/wullemsb/4966132) is still relevant, please include it in the documentation of "**QueryOver Queries**".

**Comment by fredericDelaporte** [comment]
The documentation is contributed from nhibernate-core, see the [`doc`](https://github.com/nhibernate/nhibernate-core/tree/master/doc).

But on this case, I would say the `IQueryOver` should be extended a bit to directly expose this kind of methods, instead of having to reach for the underlying criteria. So I would rather evolve the API (probably through extension methods at first, to avoid a breaking change) rather than documenting reaching the underlying criteria.

**Comment by smarts** [comment]
@fredericDelaporte i'm a bit confused about your first sentence. Was that for informational purposes so that I could contribute a merge request? At first it made me think that I had opened this issue in a different repository than the one you referenced

**Comment by bahusoid** [comment]
> IQueryOver<TRoot> already exposes most options, which just forward to the underlying criteria. Is there any reason for not having SetTimeout among them, other than having forgotten it, 

Looks like forgotten thing to me. But I don't think we should add it to interface - extension method  should suffice

**Comment by fredericDelaporte** [comment]
My first sentence is there just for explaining why I have moved the issue here.

**Comment by hazzik** [comment]
>  But I don't think we should add it to interface - extension method should suffice

I wish there were default methods on interface. But unfortunately they are only in the .NET Core 3.0

@maca88 since you are a Roslyn expert here. How hard would it be to poly-fill the default interface methods to everything below .NET Core 3? Eg using the same pattern as we already do here?

**Comment by smarts** [comment]
Thank @fredericDelaporte. I totally missed the *"… transferred this issue …"* text

**Comment by maca88** [comment]
> How hard would it be to poly-fill the default interface methods to everything below .NET Core 3?

Relatively easy, all that has to be done is to copy the interface method to a static class, with minor method definition modifications and optionally wrap the interface method in a directive (e.g. NETCORE3). This can be done as a Roslyn analyzer that would run on each build avoid having to manually run a tool (similar how hql grammar code is generated) or as a separate tool. The extension method can be generated in the same file as the interface or in a different file, depends what we prefer.
