### ISSUE TITLE
Can't use joined-subclass with the same key column name

### ISSUE THREAD

**Issue by Kostrzak** [nhibernate/nhibernate-core#2272]
After upgrading our Nhibernate version to 5.2 it looks like it is no longer possible to use joined-subclass mapping with keys mapped to the same column name(on different tables). Here is the example mapping that was working in previous versions: 

```xml
<class name="System" table="SYSTEMS" polymorphism="explicit">
  <id name="Id" column="SYSTEM_ID">
    <generator class="trigger-identity" />
  </id>
  <property name="Type" column="SYSTEM_TYPE" type="AnsiString" />
... 
  <joined-subclass name="Application" table="APPLICATIONS">
    <key column="SYSTEM_ID" on-delete="cascade"></key>
``` 

Error we are getting:

> Unable to build the insert statement for class Application: a failure occured when adding the Id of the class
>
> ArgumentException: The column 'SYSTEM_ID' has already been added in this SQL builder

 

We have solved similar errors for mappings were we had 2 properties mapped to 1 column by setting update="false" insert="false" but unfortunately this is not possible for key column. Changing column name on the database also can't be done.

 

Is it an issue/bug in the newest Nhibernate or is there a workaround that we can use?

**Comment by fredericDelaporte** [comment]
It looks like a regression, it has to be looked into.
It was already "reported" in #2268 but with too few information, this was turned down.

**Comment by fredericDelaporte** [comment]
Well, there is still not enough information. We have many mappings like this in the NHibernate tests, with the key using the same name on joined table than the id name: no trouble.

Can you please provide a complete example demonstrating the issue, or even better PR a test case?

**Comment by mattzink** [comment]
We are seeing this as well, after upgrading from NH 5.1.6 to 5.2.6.

In case it's helpful, Here is our sanitized entity and mapping classes:

```csharp
class FooView
{        
    public virtual Guid Id { get; protected set; }    
    public virtual string CompositeId { get; set; }
    public virtual string Value { get; set; }
    public virtual Other Other { get; set; }
    public virtual Bar Bar { get; set; }
}

class FooViewMapping : ClassMapping<FooView>
{
    public FooViewMapping()
    {
        // NHibernate schema validator doesn't support views
        SchemaAction(NHibernate.Mapping.ByCode.SchemaAction.None);
        Mutable(false);

        Id(x => x.CompositeId, map => map.Column("composite_id"));
        Property(x => x.Id, map => map.Column("bar_id"));
        Property(x => x.Value);
        ManyToOne(x => x.Other);
        ManyToOne(x => x.Bar);
    }
}
```

**Comment by bahusoid** [comment]
> We are seeing this as well, after upgrading from NH 5.1.6 to 5.2.6.

Same exception different issue. Your issue #2001.
Solution for you is mentioned here:
> We have solved similar errors for mappings were we had 2 properties mapped to 1 column by setting update="false" insert="false"

Also see https://github.com/nhibernate/nhibernate-core/issues/2001#issuecomment-460079630

**Comment by mattzink** [comment]
@bahusoid Thanks, that worked, but shouldn't `Mutable(false)` have this effect for the entire class?

**Comment by bahusoid** [comment]
AFAIK mutable objects are insertable but not updatable. So you still need to set insert to false

**Comment by bahusoid** [comment]
@Kostrzak We seems to have similar mapping in tests [here](https://github.com/nhibernate/nhibernate-core/blob/99d48f56198f8457c31528277077795b72ef2f79/src/NHibernate.Test/NHSpecificTest/NH2951/Mappings.hbm.xml#L4-L8). And everything seems to work..

**Comment by Kostrzak** [comment]
It turned out we had another mistake on the same mapping file so the joined-subclass wasn't the real problem. I am closing the issue.
