### ISSUE TITLE
Coalesce Error: Not to be used directly - use inside QueryOver expression

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [nhibernate/nhibernate-core#2273]
Could someone please look if it's a bug?
NHibernate 5.2.6 (net.core)
Dialect: `NHibernate.Dialect.MsSql2008Dialect`
Driver: `NHibernate.Driver.SqlClientDriver,NHibernate`
Db: `MSSQL 14.0.2027.2`
The following query throws an exception:
```
queryOver
    .Select(new[]
    {
        Projections.Property(() => root.Id).WithAlias(() => vm.Id),
        Projections.Property(() => root.FullName).Coalesce(Projections.Property(() => root.UserName)).WithAlias(() => vm.Name),
    });
```
The exception is:
```
System.InvalidOperationException: Not to be used directly - use inside QueryOver expression
   at NHibernate.Criterion.ProjectionsExtensions.Coalesce[T](T objectProperty, T replaceValueIfIsNull)
```

**Comment by bahusoid** [comment]
No. Error clearly says that `Coalesce` is expected to be used only inside select **expression**:
`.Select( () => root.FullName.Coalesce(root.UserName))`

It won't work with projections.

Though it seems you can use `SelectList` for your needs . Something like:
```C#
queryOver
    .SelectList(l => 
        l.Select(() => root.Id).WithAlias(() => vm.Id)
         .Select(() => root.FullName.Coalesce(root.UserName)).WithAlias(() => vm.Name));
```

**Comment by bahusoid** [comment]
Hm...  Actually my suggestion won't work in 5.2 due to #2246.

So as a workaround you can adjust your existing code to
```C#
new SqlFunctionProjection("coalesce", returnType, projection1, projection2);
```

Or simply select both properties and do coalescing logic in code.
