### ISSUE TITLE
nhibernate.5.2.6.nupkg has assembly version number 5.2.0.0

### ISSUE THREAD

**Issue by budajeff** [nhibernate/nhibernate-core#2277]
Hello,

In nhibernate.5.2.6.nupkg the File Version attribute of the NHibernate.dll file is 5.2.6.0 but the .Net Assembly attributes (as revealed by dotPeek) are 5.2.0.0.

Is that by design, or is that an oversight? I was expecting the version numbers to match.

Thanks

**Comment by hazzik** [comment]
As intended thanks.
