### ISSUE TITLE
how to handle session management in an asp.net mvc 4 application

### ISSUE THREAD

**Issue by dagda1** [nhibernate/nhibernate-core#2282]
I am returning to nhibernate after many years away and I am upgrading a codebase to nhibernate 5.2.6.

What are the best practices for session management in an ASP.NET MVC app.

I used to use castle facilities but these are all out of date.

Should I create an httpmodule to handle this?

I tried asking this on stackoverflow and the question was instantly closed.

**Comment by fredericDelaporte** [comment]
The Nhibernate [user group](https://groups.google.com/forum/#!forum/nhusers) should be then the place to go.
