### ISSUE TITLE
cache issue-.net core 3.0-Could not load type 'System.Web.Caching.CacheItemPriority' 

### ISSUE THREAD

**Issue by nambir** [nhibernate/nhibernate-core#2290]
I was using nhibernate for Cache in old .net framework.

Now we are rewriting to .net core 3.0.

We are having a runtime issue for nhibernate cache.

**Inner Exception**
Could not load type 'System.Web.Caching.CacheItemPriority' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.":"System.Web.Caching.CacheItemPriority

**Exception**:
{"An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.\r\n\r\n

![nhibernate cache issue](https://user-images.githubusercontent.com/16057911/71064207-8ea0ca00-2194-11ea-8237-7162d906ee8a.jpg)

**Comment by bahusoid** [comment]
Wrong place.  `SysCacheProvider` is not a part of nhibernate project (maybe it's an issue for https://github.com/nhibernate/NHibernate-Caches but check it for yourself)

Maybe all you need to do  -  update it to recent version
