### ISSUE TITLE
Missing Row Count in Debug Log for Future queries

### ISSUE THREAD

**Issue by Danielle9897** [nhibernate/nhibernate-core#2296]
Using this (simplified) code (running with Dotnet Core):
```
public void Execute(ISessionFactory factory)
{
        using(var session = factory.OpenSession())
        using(var tx = session.BeginTransaction())
        {
            // Total row number is not written to log
             var future = session.CreateQuery("select Id As Id from Post")
     		                 .SetResultTransformer(Transformers.AliasToBean<PostId>())
		                 .Future<PostId>();
	      future.ToList(); 

               // This is ok - total row number is written to log   
               // session.CreateCriteria<Blog>().List<Blog>();    

               tx.Commit();
        }
}

public class PostId
{
     public int Id { get; set; }
}
```

1. With **NHibernate 5.2.6**, The total 'row count' log message is **Not** written to the log
    I only receive the following: 
   ` "result row: "` 
   (from **_NHibernate.Loader.Loader:_**) 
    with No row count information! 

2. With the previous **Nhibernate 5.1.3**, the total was written and we had (for example):   
  `"result set row: 1"` 
    (from _**NHibernate.Impl.MultiQueryImpl**_)

    AND we also got:

    `"done processing result set (10 rows)"` 
    (from _**NHibernate.Impl.MultiQueryImpl**_)

  
3. I see that  _MultiQueryImpl_ is obsolete
https://github.com/nhibernate/nhibernate-core/blob/4e54de2f82fda24b04f6f432facdb5a96ef625a2/src/NHibernate/Impl/MultiQueryImpl.cs#L22

4. **BUT**, for example, when the following code snippet is run (with **NHibernate 5.2.6**):
` session.CreateCriteria<Blog>().List<Blog>();`
we do get the expected msg in the log from Loader.cs
`"done processing result set (5 rows)"`
 (from **_NHibernate.Loader.Loader:_**)

5. So, can you please provide this missing functionality?

**Comment by fredericDelaporte** [comment]
Future are using a new batcher instead of MultiQueryImpl, so this could be a regression.
