### ISSUE TITLE
How to eager load deeply nested entities efficiently

### ISSUE THREAD

**Issue by nuclear1989** [nhibernate/nhibernate-core#2297]
Hello,

I'm trying to go through some optimizations with our nhibernate code and having a hard time finding information on deeply nested domain models.  Most examples that show eager loading are performing eager loading at the Root entity.  Below is the example object graph i'm wanting to eager load in memory.  Is the below query the correct way to do this?  Also, Is it even possible to "Not" have performance issues with a deeply nested object graph?  

```
                      var cart = _session.QueryOver<Cart>().Where(x => x.Id == command.CartId)
                .Fetch(x => x.LineItems).Eager
                .Fetch(x => x.LineItems.First().LineItemChoices).Eager
                .Fetch(x => x.LineItems.First().Configuration).Eager
                .Fetch(x => x.LineItems.First().Configuration.ConfigurationChoices).Eager
                .Fetch(x => x.LineItems.First().Configuration.ConfigurationChoices.First().OptionVersion).Eager
                .Fetch(x => x.LineItems.First().Configuration.ConfigurationChoices.First().ProductOptionVersion).Eager
                .SingleOrDefault<Cart>();
```

On a side not, Is it even possible to utilize Futures here to reduce the affects of a Cartesian product with everything being nested so deep?

**Comment by bahusoid** [comment]
Check https://github.com/nhibernate/nhibernate-core/pull/1599.  Part about `SelectMode.ChildFetch` contains deep fetch example.

Also you should check https://github.com/maca88/NHibernate.Extensions `Include` which is simpler to use (but you can't skip root objects from select)

Anyway such kind of questions should be asked on stackoverflow.

**Comment by fredericDelaporte** [comment]
On stackoverflow, or on [NH user group](https://nhibernate.info/groups.html). By the way this [question](https://stackoverflow.com/q/36069780/1178314) is quite similar to yours. But the answer (of mine) is about getting good performances without using eager loading.
