### ISSUE TITLE
Creating a proxy instance failed

### ISSUE THREAD

**Issue by dnagasuresh** [nhibernate/nhibernate-core#2301]
We are using the latest NHibernate 5.2.6 in our .Net application. While calling the ICretia.List method to loading the data by criteria, we are receiving the error "Creating a proxy instance failed". The attached file has the full stack trace. Please help me to fix the issue. 

[Error Stack Trace.txt](https://github.com/nhibernate/nhibernate-core/files/4021789/Error.Stack.Trace.txt)

Inner Exception: Declaration referenced in a method implementation cannot be a final method.  Type: 'MaterialsProxy'.  Assembly: 'MaterialsProxyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by fredericDelaporte** [comment]
Please make sure your application has proxy validation enabled ([`use_proxy_validator`](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional) not set or set to `true`), and if yes, please provide a full reproducible example. For a proxy failure, that means at least mapped class(es) and mappings, assuming you have checked that just `Load` ing an entity is enough to trigger the trouble.

**Comment by dnagasuresh** [comment]
> Please make sure your application has proxy validation enabled ([`use_proxy_validator`](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional) not set or set to `true`), and if yes, please provide a full reproducible example. For a proxy failure, that means at least mapped class(es) and mappings, stripped down to their bare minimal needed to reproduce the trouble, assuming you have checked that just `Load` ing an entity is enough to trigger the trouble.

Thank you so much for your reply.

We will provide you the sample application to reproduce the issue. Meanwhile, I want to share with you one thing is, if we have many-to-one relation in an HBM file, then only we are having the above-mentioned issue. If we remove the many-to-one relation from the HBM, we are not receiving the error. Please see the attached HBM file where we have man-to-one relation. 

Note: Earlier we used to have the NHibernate 3.0.0.1001 in our solution reference for 10 years and there are no issues with the same HBM files. Now we have migrated to 5.2.6 and having the issue with the existing HBM files. I think we are missing some additional properties or any other configurations. Please let us know to fix the many-to-one relation issue in the new NHibernate Thank you.

**Comment by fredericDelaporte** [comment]
That is not the hbm which is the root of such trouble usually, but the classes declaration. The proxy builder has changed a lot in recent NHibernate versions, and does no more accept buggy cases, contrary to the previous one.
You should see what is wrong with your classes by making sure proxy validation is enabled. If you do not want to fix your classes, you can switch back to the old and obsolete proxy generator, which will be dropped in NH 6. Set [`proxyfactory.factory_class`](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-optional) to `NHibernate.Bytecode.DefaultProxyFactoryFactory` for switching back to the old proxy factory.

**Comment by dnagasuresh** [comment]
> obsolete

I have added the below line in the NHibernate configuration and the issue has fixed. Thank you so much for your help.

      <property name="proxyfactory.factory_class">NHibernate.Bytecode.DefaultProxyFactoryFactory, NHibernate</property>

Could you please help to fix the issue without having the above line? That means, how can I make my classes to support the Proxy? Please help me. Thank you.

**Comment by fredericDelaporte** [comment]
No:

- Here it is the issue tracker, meant for bug reports / feature requests. For support, please post on StackOverflow or NhUser, see [groups](https://nhibernate.info/groups.html).
- Anyway the bare minimal elements required for helping you are not provided, some advice seems not followed. Before posting to StackOverflow  or groups, I suggest you to re-read my answers here, and include in the post you would do on StackOverflow or groups the missing pieces of information. (Have you checked proxy validation was enabled? And provide in that new post you would do some code! Without some classes, along their mapping, allowing to reproduce the trouble, no one is likely to be able to help you.)
