### ISSUE TITLE
Add missing overloads to ISession.Get methods

### ISSUE THREAD

**Issue by idiotsky** [nhibernate/nhibernate-core#2313]
`ISession.Get` methods have no overloads taking both an `entityName` and a `lockMode`, which, as a result, forces to lock in a separated query when getting an entity by entity name.

In high concurrency environments, it may cause issues.

Generic `Get<T>` methods also lack overloads with an `entityName` argument, which are required when the class is not the entity name.

**Comment by fredericDelaporte** [comment]
Async methods being generated from sync ones by our development process, it is better to refer to the sync version when asking for changes which are not async specific. So I have edited the request.

I have also reworded it as a feature request.
