### ISSUE TITLE
RowCount not working with grouped results

### ISSUE THREAD

**Issue by fairking** [nhibernate/nhibernate-core#2314]
I am struggeling with getting rowcount when columns are grouped.
What I have found is when `RowCount()` is aplied it removes `group by` from the query. I don't understand why do we do that when there is an easy way to acheave that just by `select count(*) from (ACTUAL QUERY WITHOUT ORDER BY)`.
Is there any **EASY** way to do the rowcount in NH or rowcount is just broken or not supported with grouped columns?

Bellow is my example:
```
public async Task<PaginatedVm<DepartmentVm>> GetDepartments(DepartmentQueryVm query)
{
    Department root = null;
    StaffMember staffMember = null;
    DepartmentVm vm = null;

    var queryOver = Db.QueryOver(() => root)
        .JoinEntityAlias(() => staffMember, () => staffMember.Department.Id == root.Id, NHibernate.SqlCommand.JoinType.LeftOuterJoin)
        .Select(WithBaseGroupColumns(root, vm, new[]
        {
            Projections.GroupProperty(Projections.Property(() => root.Name)).WithAlias(() => vm.Name),
            Projections.GroupProperty(Projections.Property(() => root.Description)).WithAlias(() => vm.Description),
            Projections.Count(Projections.Property(() => staffMember.Id)).WithAlias(() => vm.MemberCount)
        }))
        .Where(Restrictions.Eq(Projections.Property(() => root.IsDeleted), false));

    var rowCount = await queryOver.RowCountAsync();

    var result = rowCount > 0
        ? await queryOver.TransformUsing(new AliasToBeanResultTransformer(typeof(DepartmentVm)))
            .Skip((query.Page - 1) * query.PageSize).Take(query.PageSize).ListAsync<DepartmentVm>()
        : new List<DepartmentVm>();

    return new PaginatedVm<DepartmentVm>(result, rowCount, query.Page, query.PageSize);
}
```

I appreciate for any help guys.

**Comment by hazzik** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

From your post it is not clear what is "not working" as there is no error or invalid SQL mentioned. 

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).

**Comment by fairking** [comment]
The problem is the following line `var rowCount = await queryOver.RowCountAsync();` executes the sql bellow:
```
SELECT
        count(*) as y0_
    FROM
        dbo.core_staff_groups this_
    left outer join
        dbo.core_staff staffmembe1_
            on  (
                staffmembe1_.department_id = this_.id
            )
    WHERE
        this_.discriminator='Department'
        AND this_.is_deleted = @p0;
```

As you can see there is no `GROUP BY` in the query, as a result the count is not what is expected.

**Comment by fredericDelaporte** [comment]
Asking the row count from a grouped query causes the group by to be discarded. Maybe NHibernate should instead raise an error. But the fact is, counting rows from a group by is not something directly supported by SQL, thus the discarding of the group by.

With SQL, when willing to count in a separated query the rows that a group by will yield, we have either to use a `count(distinct ..)` on something having the same distinct cardinality than the group by, or to use a subquery.

**Comment by fairking** [comment]
It is not a query problem. I use SQL kata as a replacement to QueryOver and it just makes query wrapper without actual query modifications (only order by gets removed). Eg. 'Select count(*) from ({actual query without order by}) as q' and everything is working fine. It is a QueryOver issue

**Comment by fredericDelaporte** [comment]
Different querying API have different semantics. Have you tried explicitly using a subquery with QueryOver?
What you tell about SQL kata means it "automagically" wrap the query in a subquery to be able to count from it. It seems that is not a feature of QueryOver to do such a thing.
