### ISSUE TITLE
Add SetFlushMode for QueryOver and Linq

### ISSUE THREAD

**Issue by dplaskon** [nhibernate/nhibernate-core#2315]
I think it would be as simple as adding a new extension method in QueryOverExtensions to support this.

**Comment by fredericDelaporte** [comment]
I thought I had handled missing methods in #2275, but it seems this one is still missing. Any other?

**Comment by dplaskon** [comment]
From what I could see, this was the only one.

**Comment by dplaskon** [comment]
It looks like NhQueryableOptions could benefit from this too, it looks like it's not currently possible to specify the flushmode of a linq query.
