### ISSUE TITLE
Save object with object id error

### ISSUE THREAD

**Issue by OpsOwns** [nhibernate/nhibernate-core#2326]
When i am trying save object i ve got an error but object is added to database.

```csharp
   public class UserMap : ClassMap<User>
    {
        public UserMap()
        {
            Id(x => x.Id).CustomType<NHibernate.Type.Int32Type>()
    .GeneratedBy.Custom<global::NHibernate.Id.IdentityGenerator>();

            Map(d => d.Name);
        }
    }
   public class User
    {
        public virtual UserID Id { get; set; }
        public virtual string Name { get; set; }
    }
    public class UserID
    {
        public virtual int Id { get; set; }

    }
```
Error Message :
NHibernate.PropertyAccessException: 'The type System.Int32 can not be assigned to a property of type Nh.UserID'
ArgumentException: Object of type 'System.Int32' cannot be converted to type 'Nh.UserID'.

**Comment by hazzik** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

From your code sample - your mapping is incorrect and NHibernate is trying to do exactly as you told it to do.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
