### ISSUE TITLE
How to Use Linq

### ISSUE THREAD

**Issue by parabeyond008** [nhibernate/nhibernate-core#2329]
`select a.title,a.classid,sortnum from (select title,classid,(row_number() over(partition by Classid order by senddate)) as sortnum from CMS_News) a where sortnum=1`
as
`session.Query<CMS_News>().GroupBy(x => x.ClassId).Select(g => new { ClassId = g.Key, News = g.First() });`

**Comment by fredericDelaporte** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
