### ISSUE TITLE
Does NHibernate support .NET Core 3.1?

### ISSUE THREAD

**Issue by vruss** [nhibernate/nhibernate-core#2339]
The Readme only mentions 
> NHibernate is a mature, open source object-relational mapper for the .NET framework.

But release notes mention .NET Core 2.1 support, so here I'm asking if you support 3.1?
If not, do you plan on supporting .NET Core 3.1 in the future?

**Comment by fredericDelaporte** [comment]
It supports .Net Standard 2.0, so anything implementing it (which .Net Core 3.1 does) is supported.
