### ISSUE TITLE
NotSupportedException: Npgsql 3.x removed support for writing a parameter with an IEnumerable value, use .ToList()/.ToArray() instead

### ISSUE THREAD

**Issue by megafetis** [nhibernate/nhibernate-core#2343]
I am trying to save entity with discriminator column hierarchy.

**Comment by megafetis** [comment]
Nhibernate 5.2.6-5.2.7

**Comment by bahusoid** [comment]
and full exception stacktrace would also be useful

**Comment by hazzik** [comment]
Feels like external issue. Closing now. Please provide a full stack trace and a reproducible example if want this issue reopened.
