### ISSUE TITLE
Primary Keys to natural-id/unique 

### ISSUE THREAD

**Issue by israelaece** [nhibernate/nhibernate-core#2345]
When we're using `<natural-id />` with unique constraint, NHibernate is generating the same unique constraint twice. Is it necessary? Could NHibernate ignore one of them just for convenience?

    <natural-id mutable="false">
      <property name="Thumbprint"
                unique="true"
                not-null="true">
        <column name="Thumbprint"
                not-null="true"
                sql-type="varchar(100)" />
      </property>
    </natural-id>

**Comment by fredericDelaporte** [comment]
A `natural-id` automatically generates an unique constraint. There is no need to add one on the property, it is redundant (provided the natural-id is not composite). Just remove it from the property. Why do you need it there?
