### ISSUE TITLE
Using a ICompositeUserType in a projection

### ISSUE THREAD

**Issue by InlineAsm** [nhibernate/nhibernate-core#2355]
Hello,

I have created a custom Money type that consists of two columns (currencycode and amount) and implemented it as a ICompositeUserType so that NHibernate can load/save the Money from/to the database. This works great.

Now I'd like to use the Money type in a QueryOver or Linq query. I specifically want to be able to calculate a sum of columns that are of type Money. When we are aggregating we will make sure we won't add different currencycodes together. So basically the sum should just sum the amount columns.

The previous code that used decimals looked something like this:
```
var results = query
                .SelectList(list => list
                    .SelectSum(i => i.Amount)
                    .WithAlias(() => invoicesTotals.Amount)
                    .SelectSum(i => i.VatAmount)
                    .WithAlias(() => invoicesTotals.VatAmount)
                    .SelectSum(i => i.InvoiceDiscountAmount)
                    .WithAlias(() => invoicesTotals.AmountDiscount)
                    .SelectSum(i => i.TotalAmount)
                    .WithAlias(() => invoicesTotals.TotalAmount)
                 )
                .TransformUsing(Transformers.AliasToBean<InvoicesTotals>())
                .SingleOrDefault<InvoicesTotals>();
```

Is this possible at all with the custom Money type and if it is what do I need to implement to make queries like this work?

**Comment by fredericDelaporte** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
