### ISSUE TITLE
cannot remove myself from https://nhibernate.jira.com/ no matter how hard I try

### ISSUE THREAD

**Issue by jimmymain** [nhibernate/nhibernate-core#2366]
I am trying to leave https://nhibernate.jira.com/ and I cannot find any contact details for an administrator who can remove me from the nhibernate JIRA.

In desperation I am logging a ticket here in the hopes that someone can help.

Thanks

**Comment by fredericDelaporte** [comment]
Hello,
There a lot of Jim users. Can you tell your exact user name on Jira?
And have you tried contact Atlassian, the Jira owner? It seems anyway accounts are global to their system, and not specific to NHibernate. I do not have any option of deletion on account, I can just ban them from NHibernate Jira.

**Comment by jimmymain** [comment]
sorry, my email address is craig@palantir.co.za

**Comment by hazzik** [comment]
@jimmymain removed.

**Comment by hazzik** [comment]
@fredericDelaporte you go to "Administration -> Users". Click on a user. Then on ellipses menu ("...") select "Remove user"

**Comment by pvginkel** [comment]
I'd like to be removed also. My email address is pvginkel@gmail.com.

**Comment by fredericDelaporte** [comment]
Done.
