### ISSUE TITLE
Add Expression as Foreign Key

### ISSUE THREAD

**Issue by heikar** [nhibernate/nhibernate-core#2398]
Hi,

is it possible to add an expression (or constant) to a mapping (e.g. one-to-one) as foreigen key?

In my example i have multiple tables with a non-standard structure :-(
The tables are not from me and cannot be modified.

There are tables with data (table_a, table_b, table_c) and there are one table which extends the other tables with additional columns.

In the "data tables" have always one column for pk (called Id).
In the "extend table" has two columns for pk (called data_Id and index_Id).

In the data_Id column may be the id from table_a, table_b or table_c.
In the index_id column is the name of the corresponding table (a, b or c).
Between the tables is no refferential integrity, so this can be mapped.

Now i want create on-to-one mapping from the "data tables" to the "extend table". In the business objects form the "data tables" exits a property "Id" which is mapped to the table and a property "Index" which has "a, b or c" (depending on the table name) as content.

When i create the map for the tables is it possible to map the "Index property" from the "data tables" to the index_id column in the "extended table"? The problem is, that the values in the data_Id column can be twice or three times and the one-to-one is only assignable in pendency with the index_id column.

Can this task be implemented with NHibernate?

Many greetings
heikar

**Comment by fredericDelaporte** [comment]
From my viewpoint your answer is very likely in the [documentation](https://nhibernate.info/doc/nhibernate-reference/mapping.html#mapping-declaration-onetoone), something like using nested `formula` elements.

Anyway, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
