### ISSUE TITLE
Why does NHibernate not apply filtering when doing a select fetching strategy?

### ISSUE THREAD

**Issue by gerardopebu** [nhibernate/nhibernate-core#2403]
Why does NHibernate not apply filtering when doing a select fetching strategy?

Entities:

```
public class Vehicle 
	{
		public virtual Guid Id { get; set; }
		public virtual Guid TenantId { get; set; }        
		public virtual Customer OwnerCustomer { get; set; }        
	}	
```
```
public class Customer 
	{
		public virtual Guid Id { get; set; }
		public virtual Guid TenantId { get; set; }        
		public virtual string Name { get; set; }        
	}
```
	
Mapping entities (NHibernate by code):

```
public class VehicleMap : ClassMapping<Vehicle>
    {
        public VehicleMap()
        {
			this.Id(x => x.Id, conf =>
            {
                conf.Column("VehicleId");
                conf.Generator(Generators.Guid);
            });
			
	    this.Property(x => x.TenantId, conf => { conf.NotNullable(true); });
	    this.Filter("TenantFilter", map => map.Condition("TenantId = :TenantId"));
			
            this.ManyToOne(v => v.OwnerCustomer, conf =>
              {
                  conf.Column("OwnerCustomerId");
                  conf.NotNullable(true);
              });            
        }
    }
```

```
public class CustomerMap : DefaultClassMapping<Customer>
    {
        public CustomerMap()
        {
            this.Id(x => x.Id, conf =>
            {
                conf.Column("CustomerId");
                conf.Generator(Generators.Guid);
            });
			
	   this.Property(x => x.TenantId, conf => { conf.NotNullable(true); });
	   this.Filter("TenantFilter", map => map.Condition("TenantId = :TenantId"));
			
            Property(x => x.Name, conf =>
            {
                conf.Length(500);
                conf.NotNullable(true);
            });            
        }
    }
```
	
When I get vehicles, Nhibernate apply the filter "TenantFilter":
`CurrentSession.QueryOver<Vehicle>().ListAsync();`

Generate this SQl: 
```
SELECT this_.vehicleid        AS vehicleid1_27_0_, 
       this_.tenantid         AS tenantid3_27_0_, 
       this_.ownercustomerid  AS ownercustomerid10_27_0_
FROM   vehicle this_ 
WHERE  this_.tenantid = '897b37b9-8c34-419f-abc2-8cca2baed6e8'
```

But when I get the value of the vehicle's "OwnerCustomer" property, Nhibernate, via lazy loading and using select fetching strategy, generate a SQl query and does not apply the filter to the Customer:

```
SELECT customer0_.customerid     AS customerid1_5_0_, 
       customer0_.tenantid       AS tenantid3_5_0_, 
       customer0_.NAME           AS name6_5_0_
FROM   customer customer0_ 
WHERE  customer0_.customerid='ff413a55-e7e7-423a-a194-56056478b01a'
```

Because filtering is still enabled, the SQl query shold be:
```
SELECT customer0_.customerid     AS customerid1_5_0_, 
       customer0_.tenantid       AS tenantid3_5_0_, 
       customer0_.NAME           AS name6_5_0_
FROM   customer customer0_ 
WHERE  customer0_.customerid='ff413a55-e7e7-423a-a194-56056478b01a' AND customer0_.tenantid = '897b37b9-8c34-419f-abc2-8cca2baed6e8'
```

**Comment by bahusoid** [comment]
Does filtering work for entities loaded via `session.Get/session.Load`? I suspect it's not supported..

**Comment by gerardopebu** [comment]
> I we think logically how is it possible to have relationship vehicle <-> customer where they are from different tenants. It must not be possible. If they are (in your case) it means your tenant is not a tenant which NH thinks of.
> So the tenant check on the reference property is redundant.
> 
> > @bahusoid Does filtering work for entities loaded via session.Get/session.Load?
> 
> I think the Get/Load must apply the tenant filter too.

**Comment by gerardopebu** [comment]
Thanks @fairking for the answer, but my question is about _Why does NHibernate not apply filtering when doing a select fetching strategy?_. I'm not asking if it makes sense that two entities are related and have different tenants.

**Comment by fairking** [comment]
> So the tenant check on the reference property is redundant.

```
var vehicles = session.Query<Vehicle>().ToList(); // tenant filter applied
var vehicle = session.Get<Vehicle>(id); // tenant filter applied
var customer = vehicle.Customer; // tenant filter not applied
var customerVehicles = cusromer.Vehicles; // tenant filter not applied
```

References and fetching strategy work only based on the relationship and applying extra filters `map.Condition("TenantId = :TenantId")` will break the logic in those relations.

Let's say I got a new Vehicle without a Customer;
```
var newVehicle = new Vehicle();
```
And then applying some customer:
```
newVehicle.Customer = someCustomer;
```
And after that I am checking the customer next time:
```
var customer = vehicle.Customer; // Customer could be null if we apply some extra filters. 
```
So if we apply some extra filters the Customer fetch could return null. And now my mind is blowing. How is it possible that I assigned a customer to the property but it returns null. Where is it gone?
