### ISSUE TITLE
Cannot override default CastFunction

### ISSUE THREAD

**Issue by deAtog** [nhibernate/nhibernate-core#2404]
NHibernate Version: 4.0.4.4000
Versions Affected: **4.0.x,** **5.0.x**, **5.1.x**, **5.2.x**, **master**

Calling RegisterFunction("cast", ...) with anything but an instance of CastFunction results in an incorrect return type. The following lines in SessionFactoryHelperExtension explicitly check if the sql function is of type CastFunction.

[SessionFactoryHelperExtension:85](https://github.com/nhibernate/nhibernate-core/blob/14fef3f829141a398eb37a01ffabd21266d382fe/src/NHibernate/Hql/Ast/ANTLR/SessionFactoryHelperExtensions.cs#L85)
[SessionFactoryHelperExtension:115](https://github.com/nhibernate/nhibernate-core/blob/14fef3f829141a398eb37a01ffabd21266d382fe/src/NHibernate/Hql/Ast/ANTLR/SessionFactoryHelperExtensions.cs#L115)

The problem with this type check is that the implementation of CastFunction cannot be changed by implementing a derived class as none of the implemented interface methods are virtual.

Some possible solutions are to:
1. Check if the `functionName` parameter is equal to `"cast"`.
2. Make interface methods of CastFunction virtual so a derived class can override them.
3. Add an abstract base class that CastFunction is derived from and change the type checks accordingly.

See the implementation of [JetCastFunction](https://github.com/deAtog/nhcontrib/blob/master/src/NHibernate.JetDriver/src/NHibernate.JetDriver/JetCastFunction.cs) for why a Dialect would want to implement their own CastFunction.

**Comment by bahusoid** [comment]
> as none of the implemented interface methods are virtual.

It shouldn't really stop you just implement required overrides explicitly. Something like:
```C#
public class MyCast : CastFunction, ISQLFunctionExtended
{
	string ISQLFunctionExtended.Name => "xxx";
}
```

**Comment by deAtog** [comment]
The ISQLFunctionExtended interface is only available in current master branch. You cannot override the inherited methods of CastFunction which would be required by the example I provided.  It seems some functionality has also changed in the master branch that makes calling RegisterFunction for "cast" insufficient as Linq.Count() ends up using "transparentcast" in the master branch instead. For NHibernate 5.2.7 changing the check to be based on the function name corrects this issue.

**Comment by maca88** [comment]
Made a PR #2406 that adds a virtual Render method. @deAtog please check if it is enough for your needs.

**Comment by deAtog** [comment]
PR #2406 does indeed fix the issue.
