### ISSUE TITLE
LinkedHaspMap - need info

### ISSUE THREAD

**Issue by PriyaGurijala** [nhibernate/nhibernate-core#2407]
Hello,
Can I use `NHibernate.Util.LinkedHashMap` with .Net standard 4.5 ? Please help me.

**Comment by fredericDelaporte** [comment]
As [.Net Standard](https://docs.microsoft.com/fr-fr/dotnet/standard/net-standard) latest version is 2.1, I guess you ask about using `NHibernate.Util.LinkedHashMap` with .Net Framework 4.5.

- NHibernate is not meant to be an utility library. This kind of classes should have been made internal in my opinion. In other words, we do not support external uses of it.
- Just use an old enough NHibernate version. NHibernate v5.x targets .Net Framework v4.6.1, so you cannot use it with .Net framework v4.5. NHibernate v4.x are usable with .Net Framework v4.0, so it can also be used with .Net Framework v4.5.
- You have reached the issue tracker, meant for bug reports or feature requests.
  Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
