### ISSUE TITLE
Same column name in Id and in Many-To-One mapping causes error

### ISSUE THREAD

**Issue by heikar** [nhibernate/nhibernate-core#2408]
Hi,

the following mapping fails because of the id column:

```
public class ArticleMap : ClassMapping<Article>
{
public Article()
{
Id(x => x.Id, x => x.Column("Id"));
Property(x => x.Name);
Property(x => x.Description);
ManyToOne(x => x.Dimensions, map => map.Name("Id"));
}
}
```
If i change it to:
```
public class ArticleMap : ClassMapping<Article>
{
public Article()
{
Id(x => x.Id, x => x.Column("Id"));
Property(x => x.Name);
Property(x => x.Description);
ManyToOne(x => x.Dimensions, map => map.Name("ID"));
}
}
```
it works for SELECT but for UPDATE and INSERT, the behavior is strange.

The generated INSERT command is: `INSERT INTO Article (Name, Description, ID, Id) VALUES (?, ?, ?, ?)`.
The generated UPDATE command is: `UPDATE Article SET Name = ?, Description = ?, ID = ? WHERE Id = ?`.

Many greetings,
heikar

**Comment by deAtog** [comment]
I believe both issues are caused by #1875. See #2423 for more information and further discussion.

**Comment by fredericDelaporte** [comment]
This issue is answered in release notes:
https://github.com/nhibernate/nhibernate-core/blob/752fd626ca407c41e4a841997b4f9d1c6974bd0a/releasenotes.txt#L145-L149
You have to map your association as readonly.
```c#
ManyToOne(
    x => x.Dimensions,
    map =>
    {
        map.Column("Id");
        map.Insert(false);
        map.Update(false);
    });
```

**Comment by deAtog** [comment]
@fredericDelaporte I think there may still be an issue here. Changing the case of a column name shouldn't bypass the duplicate column exception and generate incorrect insert and update statements.

**Comment by fredericDelaporte** [comment]
We can not know: it depends on the database or even the database setting (SQL Server case). Database object names may be case sensitive, and NHibernate has no knowledge of whether this is the case or not.

**Comment by deAtog** [comment]
@fredericDelaporte yeah, I thought that might be the case. I think I recall running into something similar with MySql on Linux.
