### ISSUE TITLE
GenericBatchingBatcher does not apply command changes to the _currentBatch.CurrentStatement

### ISSUE THREAD

**Issue by garashm2k** [nhibernate/nhibernate-core#2412]
We used   NHibernateUtil.String.NullSafeSet(cmd, value, index, session); to change command data run-time but when it commits the transaction, the change dose not propagated to _currentBatch.CurrentStatement

we did this change refer to the following article
https://brosteins.com/2014/07/25/sql-server-database-encryption-with-nhibernate-series-part-4-of-5/

**Comment by bahusoid** [comment]
Is it https://github.com/nhibernate/nhibernate-core/issues/2278? Can you check if your issue still exists on [master](https://github.com/nhibernate/nhibernate-core#nightly-development-builds)?

**Comment by garashm2k** [comment]
I did,it is not the same .I find the problem by cloning master 5 days ago

**Comment by gtguybrush** [comment]
Hi, I too am interested in that approach but first solution is not clear: how can i use NonBatchingBatcherFactory?

in the code there are only reference to NHibernateUtil.String.NullSafeSet(cmd, value, index);
