### ISSUE TITLE
v5.2.7 : mapping formulas problem

### ISSUE THREAD

**Issue by jmroyb** [nhibernate/nhibernate-core#2415]
C# LangVersion = 8.0
Nullable = enable
SQL Server 2019

In a SqlServer table I added manually this code:

```sql
--	https://stackoverflow.com/questions/21624365/sql-server-index-on-nvarchar-field
ALTER TABLE TEMP_PDFRaw
ADD EnterpriseNameChecksum AS CHECKSUM(EnterpriseName);
GO

CREATE INDEX IX_ENCS ON TEMP_PDFRaw (EnterpriseNameChecksum);
GO
```

This creates this column:

![image](https://user-images.githubusercontent.com/4932314/84124540-a4a09080-aa3b-11ea-90e7-d5ac43d94cae.png)

And these values:

![image](https://user-images.githubusercontent.com/4932314/84125144-6d7eaf00-aa3c-11ea-8e43-07acb962adb7.png)

I'm going to implement `EnterpriseNameCS` column in .hbm.xml (I must use mapping files nor fluent configuration)

 ```xml
<property
name="EnterpriseName"
column="EnterpriseName"
length="500"
type="System.String"
not-null="true">
</property>
<property
name="EnterpriseNameCS"
type="System.Int64"
formula="(checksum([EnterpriseName]))"
not-null="false"
index="IX_CSEN">
</property>
```

These are affected properties class:

MyClass

```c#
        public virtual string EnterpriseName { get; set; } = default!;
        public virtual long EnterpriseNameCS { get; set; } = default!;
```

Mapping works without errors but `EnterpriseNameCS` column is not created in the table. Where is the error?

Thanks

**Comment by deAtog** [comment]
Formula's are read-only values that do not affect insert or update statements. Defining a formula inserts the SQL provided into the select statement to return a value for the property specified. Formula's do not generate calculated columns when generating database schema definitions.

The formula you've provided would be redundant of the calculated column of `EnterpriseNameChecksum`. You probably want to use something like:
```xml
<property name="EnterpriseNameCS" column="EnterpriseNameChecksum" generated="always" insert="false" update="false"/>
```

**Comment by fredericDelaporte** [comment]
deAtog is right, formula are not meant to generate computed columns in the database. There is no support in NHibernate for generating computed columns. So you have to create them by using your additional SQL script, then map them as suggested by deAtog.
