### ISSUE TITLE
Warning for non-serializable types handled by custom user types

### ISSUE THREAD

**Issue by JonasBRasmussen** [nhibernate/nhibernate-core#2424]
I'm using custom user types quite heavily, and constantly get the following warning:
```
the custom composite class CLASS handled by USERTYPE is not Serializable: 
```

This comes from the `CompositeCustomType` constructor:
```
if (!userType.ReturnedClass.IsSerializable)
{
    NHibernateLogger.For(typeof(CustomType)).Warn("the custom composite class '{0}' handled by '{1}' is not Serializable: ", userType.ReturnedClass, userTypeClass);
}
```

I wonder what the point is of this warning? Everything seems to work exactly the same whether or not I add the `Serializable` attribute to the class. I also dislike having to annotate my domain objects with `Serializable` for no apparent reason, other than to please NHibernate warnings.

Is this warning a remnant of olden times and can be removed (I'll be happy to make a pull request), or is it actually useful and I should go all-in on `Serializable`?

**Comment by fredericDelaporte** [comment]
This is not a remnant of old constraints. User types may be serialized by the second level cache, by example. The session itself is serializable, and serializing it will require being able to serialize the user types (especially if they are used as identifiers).
Of course, if your application does not use serialization at all, neither explicitly or through some second level cache using serialization (not all second level caches use it), this warning is moot for your use case.

**Comment by JonasBRasmussen** [comment]
Thank you for the explanation. I will probably keep annotating my user types as `Serializable`. Just in case. :)
