### ISSUE TITLE
Nhibernate 5.3, LINQ "==" operator generates OR with IS NULL, again

### ISSUE THREAD

**Issue by emejibka** [nhibernate/nhibernate-core#2441]
in #1860 some issue was fixed.
But nhibernate still generate OR IS Null in subquery with nullable properties.
```c#
session.Query<WaitingListItem>()
    .Where(x => session.Query<Event>()
        .Any(e => x.DesiredWorker == e.Worker))
    .ToList();
```

Generate

```sql
select waitinglis0_.id                       as id1_3_,
       waitinglis0_.insert_date              as insert2_3_,
       waitinglis0_.desired_start_time_hours as desired3_3_,
       waitinglis0_.desired_end_time_hours   as desired4_3_,
       waitinglis0_.cause                    as cause5_3_,
       waitinglis0_.desired_subdivision_id   as desired6_3_,
       waitinglis0_.created_by_client        as created7_3_,
       waitinglis0_.note                     as note8_3_,
       waitinglis0_.desired_speciality_id    as desired9_3_,
       waitinglis0_.desired_worker_id        as desired10_3_,
       waitinglis0_.recorded_event_id        as recorded11_3_,
       waitinglis0_.insert_worker_id         as insert12_3_
  from waiting_list_item waitinglis0_
 where exists (select event1_.id
          from event event1_
         where waitinglis0_.desired_worker_id = event1_.worker_id
            or (waitinglis0_.desired_worker_id is null)
           and (event1_.worker_id is null))
```

Demo https://github.com/emejibka/nhibernate-is-null-bug/blob/master/TestClass.cs

Nhibernate generate is null if left and rigth property is nullable, in any other case sql is correct

**Comment by fredericDelaporte** [comment]
With Linq, `null == null` resolves to `true`. We have to add these `is null` tests to account for this and respect the Linq semantic.

For me, this is a work as intended case.

**Comment by emejibka** [comment]
We use nhibernate from v.2 and this is unexpected behavior for us.
I agree than `null == null` should be resolved with `true` but that breaks query because exists subquery always return rows.

**Comment by fredericDelaporte** [comment]
This change is here since v5. Other ORMs have done the same change over the years. See this [#1860 comment](https://github.com/nhibernate/nhibernate-core/issues/1860#issuecomment-430553642).

You should adjust your query, by example:

```c#
session.Query<WaitingListItem>()
    .Where(x => session.Query<Event>()
        .Any(e => x.DesiredWorker == e.Worker && x.DesiredWorker != null))
    .ToList();
```

**Comment by emejibka** [comment]
Thanks a lot
