### ISSUE TITLE
Formula fails to produce an alias for parent table when id column names have the same name

### ISSUE THREAD

**Issue by mikemissakian** [nhibernate/nhibernate-core#2449]
Using SQL in a formula in a NHibernate property, it's failing to produce an alias for the parent entity id when both the parent entity id and the table being aliased in the formula have the same name.

This occurs with NHibernate 5.3.0 and 5.2.7, against SQL Server 2016 (using the 2012 dialect).

For example a mapping with this formula:
```xml
<property name="HasPortfolioHierarchy"
  formula="(select top(1) 1 from Hierarchy.T_PortfolioHierarchy tph where tph.HierarchyId = HierarchyId)"/>
```
produces this abbreviated query:
```sql
select hierarchy0_.HierarchyId as hierarchyid1_2_0_,
     (select top(1) 1 from Hierarchy.T_PortfolioHierarchy tph where tph.HierarchyId = HierarchyId) as formula0_0_
  from Hierarchy.T_Hierarchy hierarchy0_ 
  where hierarchy0_.HierarchyId=11
```

The parent table alias is missing from the sub-query and hence produces an incorrect result.
If I change the parent HierarchyId field to another column on the parent table NHibernate produces the correct sub-query with the parent alias appended.

Please let me know if you need any addition description or code.

-Mike

**Comment by bahusoid** [comment]
> It's failing to produce an alias for the parent entity id when both the parent entity id and the table being aliased in the formula have the same name.

I don't actually think it's related to same names... Could you try to wrap column name with ` (backtick):
```xml
<property name="HasPortfolioHierarchy"
  formula="(select top(1) 1 from Hierarchy.T_PortfolioHierarchy tph where tph.HierarchyId = `HierarchyId`)"/>
```

**Comment by bahusoid** [comment]
[hierarchyid ](https://docs.microsoft.com/en-us/sql/t-sql/data-types/hierarchyid-data-type-method-reference?view=sql-server-ver15) is detected as known SQL Server keyword and thus not aliased. Such column names should be escaped with backtick: 
```
`ColumnName`
```
