### ISSUE TITLE
Fail to cast enum as nvarchar for Linq Contains

### ISSUE THREAD

**Issue by nemenos** [nhibernate/nhibernate-core#2453]
Hello,
System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the nvarchar value 'cash' to data type int.
is still thrown when using Contains method. for example:
 `query.Where(x => filter.PaymentMethods.Contains(x.PaymentMethod));`
where payment method is mapped on db as a string (default):
fluentnhibernate -> `Map(x => x.PaymentMethod).Not.Nullable(); `

thank you

ps. this happens after upgrading from 5.2.7 to 5.3.1, No code changed. I had to rollback to previous version

**Comment by nemenos** [comment]
#2439

**Comment by maca88** [comment]
I am unable to reproduce the issue, I have tried the following query:
```C#
var filter = new
{
	Enums = new[] { EnumStoredAsString.Large }
};
var query = db.Users.Where(o => filter.Enums.Contains(o.Enum1)).ToList();
```
and it works fine. Does your `query` variable use methods like `Fetch`, `Select` or others? If so, could you provide the whole linq query?

**Comment by nemenos** [comment]
Hello,
I reduced the query as much as possible, mapping as much as possibile, removed all listeners and interceptors.
    sealed class FinancialMovementMap : ClassMap<FinancialMovement>
    {
        public FinancialMovementMap()
        {
            Table("FinancialMovements");

            Id(x => x.Id).GeneratedBy.Assigned();
            Map(x => x.PaymentMethod);
        }
    }

query is a simple Session.Query<T>.Where(...).ToList()
Only thing I could not remove is some (unused for that table) user types...
I really cannot figure out what could be the problem

**Comment by nemenos** [comment]
Here is the failing test you can add to EnumTests under Linq folder:
[Test]
public void CanQueryWithContainsOnEnumStoredAsString_Small_1()
{
	var values = new[] { EnumStoredAsString.Small, EnumStoredAsString.Medium };
	var query = db.Users.Where(x => values.Contains(x.Enum1)).ToList();
	Assert.AreEqual(1, query.Count);
}

**Comment by maca88** [comment]
Thanks, I unintentionally tested the query on mysql where the issue does not occur. Made a fix in #2459.

**Comment by nemenos** [comment]
Thank you @maca88. Do you think there will be a 5.3.2 soon?

**Comment by fredericDelaporte** [comment]
Currently I am the one doing most releases. I am having quite a busy week, so it is unlikely I would prepare it for this week. It will more probably occurs on August the ninth.

**Comment by nemenos** [comment]
Thank you @fredericDelaporte
