### ISSUE TITLE
Path expected for join

### ISSUE THREAD

**Issue by elvysmarcos** [nhibernate/nhibernate-core#2463]
After I updated to the latest version 5.3.1, all Joins made with linq where the table is mapped with xml and contains discriminator, simply stop working, this just for Join, because when I do just one ToList only in the table it works normally.

**Comment by bahusoid** [comment]
One place is still not blurred... You can remove all pictures if you want to keep a secret :)

**Comment by hazzik** [comment]
Fixed by #2464
