### ISSUE TITLE
HStore issue while upgrading FluentNHibernate from 0.2.0.1 to 2.1.2, NpgSql from 2.2.5 to 4.1.3.1, NHibernate from 4.0.3.4000 to 5.3.0

### ISSUE THREAD

**Issue by prsvijayganesh** [nhibernate/nhibernate-core#2477]
Issue
HStore values are not able to read while upgrading FluentNhibernate 0.2.0.1 to 2.1.2 and NpgSql from 2.2.5 to 4.1.3.1
Please refer the attached zip file which contains ,

step for reproducing the issue (NpgSql 2_2_5 to 4_1_3_1 issue.txt)
Script for creating DB ( SampleScriptForHstore.txt)
Zip file contains sample application for reading Hstore value using NpgSql 2.2.5 and 4.1.3.1
a) In 4.1.3.1, Getting as Dictionary'2 [String,string] instead of getting value while opening session and reading table
b) Tried to change, Model property (HStore) from string to Dictionary<string,string> and getting below exception
Additional Questions

Question :

What is the solution for reading value , what would be the impact?
what is the recommended steps to use it as string so no code changes required?
Already product is released to the market with interface method containing Hstore as string, Interface cannot be changed so all to be recreated. code change and test effort would be more.
Already released with 2.2.5 for same product binaries are used in another product that may still continue to use with 2.2.5 only, In this case how t
[Nhibernate.and.NpgSql.upgrade.issue.for.Hstore.zip](https://github.com/nhibernate/nhibernate-core/files/5067326/Nhibernate.and.NpgSql.upgrade.issue.for.Hstore.zip)
o fix the issue?
NHibernate.ADOException
HResult=0x80131600
Message=Could not cast the value in field col_1_0_ of type Dictionary2 to the Type SerializableType. Please check to make sure that the mapping is correct and that your DataProvider supports this Data Type. Source=NHibernate StackTrace: at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String name) at NHibernate.Type.NullableType.NullSafeGet(IDataReader rs, String[] names, ISessionImplementor session, Object owner) at NHibernate.Loader.Hql.QueryLoader.GetResultRow(Object[] row, IDataReader rs, ISessionImplementor session) at NHibernate.Loader.Hql.QueryLoader.GetResultColumnOrRow(Object[] row, IResultTransformer resultTransformer, IDataReader rs, ISessionImplementor session) at NHibernate.Loader.Loader.GetRowFromResultSet(IDataReader resultSet, ISessionImplementor session, QueryParameters queryParameters, LockMode[] lockModeArray, EntityKey optionalObjectKey, IList hydratedObjects, EntityKey[] keys, Boolean returnProxies, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer) at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters) at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet1 querySpaces, IType[] resultTypes)
at NHibernate.Loader.Hql.QueryLoader.List(ISessionImplementor session, QueryParameters queryParameters)
at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.List(ISessionImplementor session, QueryParameters queryParameters)
at NHibernate.Engine.Query.HQLQueryPlan.PerformList(QueryParameters queryParameters, ISessionImplementor session, IList results)
at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
at NHibernate.Impl.AbstractQueryImpl2.List()
at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
at Remotion.Linq.QueryableBase1.GetEnumerator() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at WpfApp2.MainWindow.GetAllItems() in <C:\Users\source\repos\NpgSql Issue\Sample> work with Npgsql4_1_3_1\WpfApp2\MainWindow.xaml.cs:line 128
at WpfApp2.MainWindow..ctor() in <C:\Users\source\repos\NpgSql Issue\Sample> work with Npgsql4_1_3_1\WpfApp2\MainWindow.xaml.cs:line 29
Inner Exception 1:
InvalidCastException: GetBytes() not supported for type col_1_0_

Further technical details

Nhibernate : 5.3.0
FluentNhiberate : 2.1.2
Npgsql version: 4.13.1
PostgreSQL version: 11.6
Operating system: Windows 10 x64
Hstore Version : 1.5

First tried only to update NPGSQL from 2.2.5 to 4.1.3.1 and we got the issue,
Then tried to update FluentNHibernate from 0.2.0.1 to 2.1.2 and NHibernate from 4.0.3.4000 to 5.3.0 in order to resolve the issue, but still not able to resolve.

find the code along with two projects below.
[Nhibernate.and.NpgSql.upgrade.issue.for.Hstore.zip](https://github.com/nhibernate/nhibernate-core/files/5067329/Nhibernate.and.NpgSql.upgrade.issue.for.Hstore.zip)

**Comment by maca88** [comment]
In case you want to preserve the old behavior you will have to create an `IUserType` where:
- `NullSafeGet` would need to retrieve the dictionary returned from `Ngpsql` and convert it to string
- `NullSafeSet` would need to convert the string to a dictionary and set the parameter type to `NpgsqlDbType.Hstore` (https://www.npgsql.org/doc/types/basic.html).

You can find [some examples](https://github.com/nhibernate/nhibernate-core/search?p=3&q=IUserType&unscoped_q=IUserType) of `IUserType` in the tests.

**Comment by prsvijayganesh** [comment]
Dear maca88,

Tried like below with IUserType interface, but no hope.  Could you provide alternate solution or sample?
Mapping also set like below
            Map(x => x.HStore).Column("\"HStore\"").CustomSqlType("hstore").CustomType< DictionaryStringType>();

While Reading from DB, show type as Dictionary'2 [string,string]  by  fetching correct column but not able convert the value or not able see the values during debug

public class DictionaryStringType : IUsertype
{
       public object NullSafeGet(DbDataReader rs, string[] names, ISessionImplementor session, object owner)
        {
            //returns as "Dictionary'2[string,string] but assingning to string

            string uriString = (string)NHibernateUtil.String.NullSafeGet(rs, names[0],session,owner);
            // uriString also assigned with value like Dictionary'2[string, string]
            //tried same by assigning to dictionary but getting runtime exception trying to convert string to dictionary'2[string,string] 
            Dictionary<string, string> dic1 = (Dictionary<string, string>)NHibernateUtil.String.NullSafeGet(rs, names[0], session, owner);

            //NpgsqlTypes.Hstore but no option available in Dbtype for Hstore
}

**Comment by maca88** [comment]
Your custom type should look something like this:
```c#
[Serializable]
public class HStoreType : AbstractStringType
{
    public HStoreType() : base(new StringSqlType())
    {
    }

    public override string Name => "HStore";

    public override object Get(DbDataReader rs, int index, ISessionImplementor session)
    {
        var value = (Dictionary<string, string>)rs[index];
        var builder = new StringBuilder();

        index = 0;
        foreach (var pair in value)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append(pair.Key);
            builder.Append(" => \"");
            builder.Append(pair.Value);
            builder.Append("\"");
            index++;
        }

        return builder.ToString();
    }

    public override void Set(DbCommand cmd, object value, int index, ISessionImplementor session)
    {
        var parameter = (NpgsqlParameter)cmd.Parameters[index];
        parameter.NpgsqlDbType = NpgsqlDbType.Hstore;
        var str = (string) value;
        var dict = new Dictionary<string, string>(
            str
                .Split(',').Select(
                    o =>
                    {
                        var pair = o.Trim().Split("=>");
                        return new KeyValuePair<string, string>(pair[0].Trim(), pair[1].Trim(' ', '"'));
                    }));

        parameter.Value = dict;
    }
}
```

Do note that I didn't tried it so it might need some small adjustments.

Closing as this is not an issue.
