### ISSUE TITLE
Join to subquery using linq

### ISSUE THREAD

**Issue by arashjfz** [nhibernate/nhibernate-core#2493]
Is it possible to have such a query in linq
```csharp
var selection = from product in session.Query<Product>()
                    join brand in
                        (from b1 in session.Query<Brand>() select new {BId = b1.BrandId, BName = b1.BrandName}) on
                        product.ProductName equals brand.BName
                    select new {ProductName = product.ProductName, BrandName = brand.BName};
```
It is a simple join to a subquery
It is simply possible in entity frame work

**Comment by hazzik** [comment]
Hello, you have reached the issue tracker, meant for bug reports or feature requests.

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) for support requests (or see [Groups](https://nhibernate.info/groups.html)).
