### ISSUE TITLE
ApplyFilter does not work on join statements in LINQ

### ISSUE THREAD

**Issue by esabah** [nhibernate/nhibernate-core#2549]
Hi 
We upgraded NH from 5.2.7 to 5.3.3.
After upgrade we had an issue that ApplyFilter  does not work with joins.
Same join statement working fine with version 5.2.7.

You can find testcase implementation below link.
https://github.com/esabah/NHibernateBugTest/blob/master/NHibernateBugTest/TxnDefTest.cs

TxnDefMember entity has a custom filter which applies filter on mbrId field.

`         ApplyFilter<MemberConditionFilter>();`

But mbrId  not included in sql query in 5.3.3 version.
`(from txndef in session.Query<TxnDef>()
join txnDefMember in session.Query<TxnDefMember>() on txndef.Guid equals txnDefMember.Id.TxnDefGuid
select txnDefMember.BucketName)`

same query returns 8 records in 5.3.3
and returns 4 records in 5.2.7

**Comment by bahusoid** [comment]
Can you check how it works with latest dev build?
https://www.myget.org/feed/nhibernate/package/nuget/NHibernate

**Comment by esabah** [comment]
I works correctly with NHibernate 5.4.0-dev.3147.

**Comment by bahusoid** [comment]
Good. Thanks for report

**Comment by gokhanabatay** [comment]
Would it be better to add Active Filters in HasMany Relations by default? Why do we force adding filters with ApplyFilter <T>?
