### ISSUE TITLE
One-to-one second level cache issue

### ISSUE THREAD

**Issue by deAtog** [nhibernate/nhibernate-core#2552]
When assembling an object with one-to-one relationships, a second level cache miss occurs while trying to assemble the related object. The OneToOneType has the following code:
```c#
public override object Assemble(object cached, ISessionImplementor session, object owner)
{
	//this should be a call to resolve(), not resolveIdentifier(), 
	//'cos it might be a property-ref, and we did not cache the
	//referenced value
	return ResolveIdentifier(session.GetContextEntityIdentifier(owner), session, owner);
}
```
I'm not sure why the implementation of this function is ignoring the value of `cached`, but feel this should be changed to:
```c#
public override object Assemble(object cached, ISessionImplementor session, object owner)
{
	return ResolveIdentifier(cached, session, owner);
}
```
or:
```c#
public override object Assemble(object cached, ISessionImplementor session, object owner)
{
	if (cached != null) {
		return ResolveIdentifier(session.GetContextEntityIdentifier(owner), session, owner);
	}

	return null;
}
```

Currently when `cached` is null, the code presumes that the Id of the one-to-one object is the same as the ID of the owning object. This causes a cache miss and a subsequent query to verify that no related object exists. I'm not sure why the original code does not simply use the `cached` Id here..

Hibernate ORM has this same issue, so coordinating a fix in both would benefit all.

**Comment by bahusoid** [comment]
As a workaround I believe you can use `many-to-one`  to simulate `one-to-one` behavior with
`column="YourColumn" insert="false" update="false"`
`not-found="ignore"` - for not constrained one-to-one (`constrained="false"`);
`unique="true"` - to create foreign key unique constraint;
For instance
```xml
<class name="Person">
    <id name="Id" generator="identity" />
    <one-to-one name="Address"/>
</class>
```

Can be replaced with:
```xml
<class name="Person">
    <id name="Id" generator="identity" />
    <many-to-one name="Address" 
		column="Id" insert="false" update="false"
		not-found="ignore"/>
</class>
```

**Comment by bahusoid** [comment]
>I'm not sure why the implementation of this function is ignoring the value of cached,

Because `Disassemble` always returns null:
https://github.com/nhibernate/nhibernate-core/blob/44f3406c2008214242e2afe8cb04574c5e05917a/src/NHibernate/Type/OneToOneType.cs#L136-L138

> the code presumes that the Id of the one-to-one object is the same as the ID of the owning object.

Actually I'm not sure I understand your scenario. I don't get how `Assemble` can be called when ID is not the same as owning object. Are you saying about `property-ref` mapping? In this case `Assemble` is not even called because ID of one-to-one is not known.
And even `many-to-one` mapping with `property-ref` won't help you. In `property-ref` case the following code is executed:
https://github.com/nhibernate/nhibernate-core/blob/95d78af3ba9443300219fc1b711c3c3db5b83401/src/NHibernate/Type/EntityType.cs#L411
which executes query like the following to load one-to-one entity.:
```sql
select * from OneToOne where NotIdProperty = OwnerId
```

So please clarify your scenario.

**Comment by bahusoid** [comment]
>  I don't get how Assemble can be called when ID is not the same as owning object

Ok I got it ) It's called when owner is retrieved from cache. So yes for `property-ref` case it at least makes sense to return null right away in `Assemble`

**Comment by deAtog** [comment]
My current mapping looks similar to this:

```xml
<class name="Person">
    <id name="Id" column="person_id" generator="identity" />
    <one-to-one name="Address" class="Address" fetch="join" />
    <!-- Additional properties here -->
</class>

<class name="Address">
    <id name="Id" column="person_id">
        <generator class="foreign">
            <param name="property">Person</param>
        </generator>
    </id>
    <!-- Additional properties here -->
</class>
```

Using the above mapping, when fetching a Person with an empty cache, a single query is used to obtain the Person and the associated Address and the objects are cached appropriately. When the Person does not have an Address, the Person is cached with the id of the Address being null. When attempting to fetch the same person again, the Person retrieved from the cache and it attempts to assemble the associated Address using the cached Id of the Address which is null. When a person has an address, the cached id of the Address is non-null.

Given that `Disassemble` always returns null currently, additional changes may be needed to make this work correctly in all situations. I don't understand the code well enough to suggest a proper fix, but it seems likely that `Disassemble` probably shouldn't always return null and that changes to `Assemble` are needed as well.
