### ISSUE TITLE
Missing breaking change documentation (TryGetCollectionParameter)

### ISSUE THREAD

**Issue by fubar-coder** [nhibernate/nhibernate-core#2578]
I have a custom implementation which is based on `BaseHqlGeneratorForMethod`. Previously, a collection parameter was automatically detected as collection, but now I have to override `TryGetCollectionParameter`.

This breaking change isn't documented in the 5.3.0 release notes.

**Comment by fredericDelaporte** [comment]
Thanks for the report.
It will likely be fixed (documented) as part of 5.3.4 release task.
This possible breaking change comes from #2365.

**Comment by fredericDelaporte** [comment]
By the way, there is not many methods which may meaningfully support parameter lists. Just to be sure we have not overlooked something, may you confirm you need to override it only for specific method generator cases, like `.Contains` methods?

**Comment by fubar-coder** [comment]
Yes, I only had to override it for a method taking an array of GUIDs that were the last of four parameters.
