### ISSUE TITLE
Add method AsNoTracking to prevent query results to be stored in first level cache

### ISSUE THREAD

**Issue by rjperes** [nhibernate/nhibernate-core#2591]
The idea is to have a method like EF Core's AsNoTracking (https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.asnotracking?view=efcore-3.1). When applied to an IQueryable<T>, it will prevent the results of the query to be stored in the first level cache of the originating session, by replacing it with an IStatelessSession.
Merge request included here: https://github.com/nhibernate/nhibernate-core/pull/2592.

**Comment by hazzik** [comment]
The consensus seems that this functionality should be implemented in some "contrib" or "extensions" project.
