### ISSUE TITLE
Invalid SQL update for read-only versioned entity with owned collection

### ISSUE THREAD

**Issue by LordJZ** [nhibernate/nhibernate-core#2596]
Restarting #2340 -- I am not sure why that one was closed.

AFAIU NHibernate tries to update the version of the entity per documentation:
> https://nhibernate.info/doc/nhibernate-reference/readonly.html
>  NHibernate updates the version if the entity has a collection with changes that dirties the entity; 

But generates invalid SQL:
```SQL
UPDATE [Redemption] SET  WHERE Id = @p0 AND Version = @p1
```

**Comment by fredericDelaporte** [comment]
It has been closed as an unsupported case, as explained in its comments.

**Comment by LordJZ** [comment]
So throw an appropriate exception? Generating invalid SQL is not a good way to indicate a known unsupported scenario.

**Comment by fredericDelaporte** [comment]
You may rewrite this issue to ask for this, and then reopen it, if you wish.
