### ISSUE TITLE
Q: `LoadAsync` Interceptor.OnLoad() is not called

### ISSUE THREAD

**Issue by shatl** [nhibernate/nhibernate-core#2602]
Hello guys,
I implemented interceptor `OnLoad` and it works with `GetAsync` but not called if entity is loaded using `LoadAsync`. 
Is this by design?

**Comment by bahusoid** [comment]
`session.LoadAsync` call doesn't trigger actual entity loading it just returns proxy (if lazy loading is supported). So yes not calling `OnLoad` (which is about actual entity loading from DB) here is by design. Or are you saying it's not called even when lazy entity is actually initialized?
