### ISSUE TITLE
Regression bug with enums used as parameter for string column

### ISSUE THREAD

**Issue by csharper2010** [nhibernate/nhibernate-core#2621]
It used to be possible to provide an enum as a parameter for HQL queries where a criterion using that parameter matches on a string column.

I know that there are different options to have an enum directly in the property and map it to a string column on the database but sometimes there just might be the convention to use an enum for defining the possible values of a string column.

I would generally argue that enums should be treated like strings when mapped on string columns.

**Comment by hazzik** [comment]
This looks like an user error. I'll be willing to accept a less invasive changes.

**Comment by fredericDelaporte** [comment]
> It used to be possible to provide an enum as a parameter for HQL queries where a criterion using that parameter matches on a string column.

Your wording implies it was previously possible but is no more. Have you more information on this? In which version this would have cease working, in which version was it working?
I would like to clarify from which version a regression would have occurred on this subject?
