### ISSUE TITLE
Bool representation breaking change between 5.2 and 5.3

### ISSUE THREAD

**Issue by MidasLamb** [nhibernate/nhibernate-core#2635]
I recently updated from 5.2 to 5.3 and my application started crashing depending on whether you continued of existing files or started fresh.

The reason being that I had a SQL query that accesses a single record and a single column, that ended with `.UniqueResult<bool>`. With old files created with NHibernate 5.2 the result from the preceding code is a `object { bool }` but with fresh files from NHibernate 5.3 it became a `object { long }`.

Seeing that users can either continue off their existing files or that new users create fresh files, I now have to take this underlying (breaking) change into account that it can be either a `long` or a `bool`.

It seems that the SQLite columns for fresh files are now `integers`, while for the old one they are `boolean`, but I did not find any mention of this in the changelog.

The fact that this particular one breaks is only a small part of my concern that this could influence all the code that somewhere have an underlying bool.

I did not find this change in the changelog or any migration guidelines, so I'm not sure how I should handle this.

Note: I make use of class mappings that contains some booleans (one of which i'm using in the query above).

**Comment by deAtog** [comment]
For native SQL queries created using ISession.CreateSQLQuery you **must** specify the type of the values returned by using the AddScalar method. Xml based SQL queries, should specify <return-scalar> for each column returned. If you do not specify the type, NHibernate will attempt to guess the type based on the value returned from the database and SQLite does not have a [boolean column type](https://sqlite.org/datatype3.html#boolean_datatype). The type specified when calling UniqueResult is only used to perform a direct cast of the returned value which will result in an InvalidCastException.

**Comment by MidasLamb** [comment]
@deAtog thank you for the clarification, but IMO this is still a breaking change between 5.2 and 5.3. 

Although SQLite does not have a separate storage type for booleans, it still allows columns to be defined as boolean (resulting in a numeric column affinity, but still a boolean column type). It seems that this is the case for Databases created with 5.2, but with 5.3 this seems to have changed.

My major concern is that this could have an impact on other parts of the application, but if I understand correctly, internally NHibernate does not care for the underlying type and I'm just seeing the effect of this change between 5.2 and 5.3 because I go immediately to `.UniqueResult<bool>` without first using the `AddScalar` method?

**Comment by fredericDelaporte** [comment]
deAtog is right, there is no such thing as a boolean type in SQLite. See https://www.sqlite.org/datatype3.html.

Prior to 5.3, NHibernate SQLiteDialect was mapping .Net types to non existing types names, which was causing bugs especially when casting were involved. This has been fixed with #2346. This has [a possible breaking change note](https://github.com/nhibernate/nhibernate-core/blob/33f90d3742f1a2d5a2aa2368edbaf667663fae1a/releasenotes.txt#L141) in release notes.

You can find a detailed explanation of why the change was required [here](https://github.com/nhibernate/nhibernate-core/issues/2507#issuecomment-685088240).

**Comment by MidasLamb** [comment]
@fredericDelaporte, thank you for pointing me to the changelog entry for this and providing additional information!

I will go through all the information and see if it allows me to fix the problem I'm seeing tomorrow. If it does I'll close this issue, but I'd like to keep it open until I'm sure I can resolve it.

Nevertheless, again, thank you for the information!

**Comment by MidasLamb** [comment]
We've recreated all the tables in an update scenario and now we no longer have to take into account two possible types when extracting.
