### ISSUE TITLE
Marking entity immutable with ClassMap.ReadOnly() still causes SqlInsertBuilder to try and build insert statement

### ISSUE THREAD

**Issue by pixelnix** [nhibernate/nhibernate-core#2654]
Seems like a bug. Reproducibility is easy, just create an entity and its ClassMap; in the constructor call ReadOnly(); then introduce some trivial mapping issue, like duplicate mapping a column between a Map() and a References(). I get a MappingException saying the insert statement couldn't be built bc the column was given twice to the SQL builder.

Fluent NHibernate 3.1.0, NHibernate 5.3.5.

**Comment by hazzik** [comment]
moved to nhibernate-core.

**Comment by bahusoid** [comment]
Immutable entities are insertable. That's afaik by design:
```
an immutable object (unchangeable object) is an object whose state cannot be modified after it is created
```
ReadOnly is just bad naming on fluent-nhibernate side.

**Comment by oskarb** [comment]
"read-only" or "immutable" - regardless of the term, it affects instances of the class. It is not meant to say that the table as such is read-only.

**Comment by oskarb** [comment]
Maybe the `dynamic-insert` flag can help if you don't intend to perform any insertions.
