### ISSUE TITLE
Stale data returned after calling IQueryable<T>.Update()

### ISSUE THREAD

**Issue by CSharpBender** [nhibernate/nhibernate-core#2663]
I was doing some tests on my [Unit of Work](https://github.com/CSharpBender/NHUnit) implementation and I've noticed that after calling IQueryable<T>.Update() I'm getting stale data although Level 2 cache is disabled and the query has executed.

Steps to reproduce:
- get a list of items from the database
- update them without loading into memory using `IQueryable<T>.Update()`
- reload the data from the database : stale data although the query executed
- clear the session and reload the data: correct data loaded

Example:
```csharp
public class Product
    {
        public Product(){}
        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
        public virtual decimal Price { get; set; }
        public virtual DateTime RowVersion { get; set; }
    }
public class ProductMap : ClassMap<Product>
    {
        public ProductMap()
        {
            Id(o => o.Id).GeneratedBy.SeqHiLo("Seq_Product", "10").Column("Id");
            Map(x => x.Name).Length(64).Not.Nullable();
            Map(p => p.Price).CustomSqlType("decimal").Precision(10).Scale(4);
            Version(o => o.RowVersion).CustomSqlType("timestamp");       
        }
    }
public void TestMethod(ISession session)
    {
            var productsBefore = session.Query<Product>().OrderBy(p => p.Id).ToList();
            session.Query<Product>().Update(p => new { Price = p.Price + 5 });
            session.Flush();
            var productsAfter = session.Query<Product>().OrderBy(p => p.Id).ToList();
            for (int i = 0; i < productsBefore.Count; i++)
            {
                //returns true
                Console.WriteLine(productsBefore[i].Price == productsAfter[i].Price);
            }
            session.Clear();
            productsAfter = session.Query<Product>().OrderBy(p => p.Id).ToList();
            for (int i = 0; i < productsBefore.Count; i++)
            {
               //returns false
                Console.WriteLine(productsBefore[i].Price == productsAfter[i].Price);
            }
    }
```

Executed queries:
```
NHibernate: 
    select
        product0_.Id as id1_9_,
        product0_.RowVersion as rowversion2_9_,
        product0_.Name as name3_9_,
        product0_.Price as price4_9_ 
    from
        "Product" product0_ 
    order by
        product0_.Id asc
NHibernate: 
    update
        "Product" 
    set
        Price=Price+:p0;
    :p0 = 5 [Type: Decimal (0:0:0)]
NHibernate: 
    select
        product0_.Id as id1_9_,
        product0_.RowVersion as rowversion2_9_,
        product0_.Name as name3_9_,
        product0_.Price as price4_9_ 
    from
        "Product" product0_ 
    order by
        product0_.Id asc
NHibernate: 
    select
        product0_.Id as id1_9_,
        product0_.RowVersion as rowversion2_9_,
        product0_.Name as name3_9_,
        product0_.Price as price4_9_ 
    from
        "Product" product0_ 
    order by
        product0_.Id asc
```

**Comment by bahusoid** [comment]
> I'm getting stale data although Level 2 cache is disabled and the query has executed.

Nope. You are getting your data from session (known also as 1-st level cache). It's by design behavior that query returns entities that already present in session

P.S. `session.Flush` calling is not required in provided example.

**Comment by CSharpBender** [comment]
> > I'm getting stale data although Level 2 cache is disabled and the query has executed.
> 
> Nope. You are getting your data from session (known also as 1-st level cache). It's by design behavior that query returns entities that already present in session
> 
> P.S. `session.Flush` calling is not required in provided example.

Then why is the query executed if the data is loaded from 1-st level cache?
It should just return the data from the session without hitting the database.

**Comment by bahusoid** [comment]
> Then why is the query executed if the data is loaded from 1-st level cache

Because only entities are cached in session. NHibernate doesn't know which entities will query return. It processes query results and returns entities already present in session.

**Comment by CSharpBender** [comment]
I was expecting NHibernate to work differently when using versioned entities.
Is there a way to overcome this behaviour besides removing those entities from the session cache?
