### ISSUE TITLE
FutureEnumerable - GetEnumerableAsync - missing configureawait

### ISSUE THREAD

**Issue by LeMaciek** [nhibernate/nhibernate-core#2677]
Ehhhh, synchronization contexts... missing configureawait(false) in https://github.com/nhibernate/nhibernate-core/blob/d6e054f2bbfda43fccf82d54b7cda4e5aecbab5d/src/NHibernate/Multi/QueryBatchExtensions.cs#L581

**Comment by fredericDelaporte** [comment]
Fixed by #2678
