### ISSUE TITLE
IEnhancedUserType from string to bool fails in some circumstances

### ISSUE THREAD

**Issue by pasqualedante** [nhibernate/nhibernate-core#2704]
I have a custom mapping type that transform a string (N or S) from database to a bool on the entity side.
This custom mapping type works fine in NH 5.2.x. After the migration to NH 5.3.x the custom mapping type works well except in one scenario: when the query check the inverse value of one variable, as show under:

```
var no = false;
Assert.IsTrue(_database.GetSession().Query<Entity1>().Where(x => x.IsChiusa == !no).Any());
```

I attach here a unit test to show the issue in action.

Thanks,
Pasquale.

[issue_in_action.zip](https://github.com/nhibernate/nhibernate-core/files/6150580/issue_in_action.zip)

**Comment by fredericDelaporte** [comment]
Fixed by #2705.
