### ISSUE TITLE
The session.Load(obj, id) overload can't handle proxies

### ISSUE THREAD

**Issue by cremor** [nhibernate/nhibernate-core#2727]
If you pass a proxy to the `ISession.Load(object obj, object id)` overload the following exception is thrown:

```
NHibernate.MappingException: No persister for: XyzProxy // or XyzProxyForFieldInterceptor
   at NHibernate.Impl.SessionFactoryImpl.GetEntityPersister(String entityName)
   at NHibernate.Impl.SessionImpl.GetEntityPersister(String entityName, Object obj)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.Load(Object obj, Object id)
```

Both "normal" lazy load proxies and proxies for lazy properties are affected.

I took a quick look a the code and it seems like the problem is that `SessionImpl.GetEntityPersister()` uses [`SessionImpl.GuessEntityName()`](https://github.com/nhibernate/nhibernate-core/blob/d2599c615237fe7b8ee1a14c152374f7351562d3/src/NHibernate/Impl/SessionImpl.cs#L993-L1005) which can't handle the case that the passed entity is a proxy. It will just return "XyzProxy" or "XyzProxyForFieldInterceptor" in that case.
I think `SessionImpl.GetEntityPersister()` should use [`SessionImpl.BestGuessEntityName()`](https://github.com/nhibernate/nhibernate-core/blob/d2599c615237fe7b8ee1a14c152374f7351562d3/src/NHibernate/Impl/SessionImpl.cs#L958-L991) instead. That method seems to support proxies.

But even if this is fixed the next problem might be at
https://github.com/nhibernate/nhibernate-core/blob/d2599c615237fe7b8ee1a14c152374f7351562d3/src/NHibernate/Event/Default/DefaultLoadEventListener.cs#L37
This would again set "XyzProxy" or "XyzProxyForFieldInterceptor" to `EntityClassName`.

It seems like `ISession.Refresh()` has a similar problem, but with that I could only reproduce it if the passed entity is not contained in the session and if it has lazy properties. Since I don't use `Refresh()` in my application I didn't look at this further.

**Comment by bahusoid** [comment]
It looks like missing test case scenario for https://github.com/nhibernate/nhibernate-core/pull/2418

> But even if this is fixed the next problem might be at

Yeah.. It should be ` @event.EntityClassName = persister.EntityName;`
