### ISSUE TITLE
implicit conversion in Take (fetch rows)

### ISSUE THREAD

**Issue by veenvlietm** [nhibernate/nhibernate-core#2746]
I've found an implicit conversion in the MSSQL query plan when using NH Take(int). SQL is expecting a long/bigint.
It's in the TOP operator, not in cardinality estimation.
NH 5.3.5, MSSQL 2017

```
var query = Session.QueryOver<Foo>().Where()
.SelectList(list => 
    SelectGroup(f => f.Bar()).SelectGroup(f => f.Bar2()).Transform()
      .Take(maxRowInt).List(); // maxRowInt should be maxRowLong.
```

more info in this thread: https://dba.stackexchange.com/questions/184302/implicit-conversion-in-fetch

**Comment by fredericDelaporte** [comment]
There is no `Take` method taking a `long`, and this a SQL-Server specific issue. NHibernate-to-linq provider is database agnostic, it cannot do any optimization specifically targeted to SQL-Server.

(Moreover I highly doubt this would optimize anything at all even for SQL-Server. This implicit conversion case occurs in a clause which is evaluated once per run, and where such conversion does not matter for query optimization.)

**Comment by veenvlietm** [comment]
You're right about the impact. And we don't actually need a `Take(long)` yet ;).
I'll guess I have to filter out these cases of my monitoring of implicit-conversion-queryplans then.
