### ISSUE TITLE
Investigate why TeamCity Oracle builds so slow

### ISSUE THREAD

**Issue by bahusoid** [nhibernate/nhibernate-core#2854]
Oracle teamcity tests take [40 minutes ](https://teamcity.jetbrains.com/viewLog.html?buildId=3540988&buildTypeId=bt1099) to finish. Doesn't look right -  if I remember correctly it was about [20 minutes](https://github.com/nhibernate/nhibernate-core/pull/1517#pullrequestreview-87775763) some months/years back. I wonder if #1511 is a culprit (as first Oracle related change for TeamCity committed after #1517)

**Comment by hazzik** [comment]
It was 20 minutes before we added async tests. Then it became around ~35 minutes.

**Comment by bahusoid** [comment]
> before we added async tests

I don't think it's true...  See here https://github.com/nhibernate/nhibernate-core/pull/1517#pullrequestreview-87775763 
This PR includes async tests and Oracle build took 21 minutes (async tests were added in 5.0, this PR for 5.1. Also see [Async ](https://github.com/nhibernate/nhibernate-core/tree/690e96f20f237960fa5bcc3d37ed7905484af675/src/NHibernate.Test) folder is already present)

**Comment by hazzik** [comment]
Probably was not enough resources on the build server. Now build takes ~26 minutes

**Comment by bahusoid** [comment]
> Probably was not enough resources on the build server. Now build takes ~26 minutes

Yet it took 20 minutes with old configuration sometime ago (async tests included).
