### ISSUE TITLE
GuidCombGenerator does not generate IDs sequential in SQL Server 2017 / Azure SQL Database

### ISSUE THREAD

**Issue by skurik** [nhibernate/nhibernate-core#2869]
It seems like `GuidCombGenerator` doesn't do what it's supposed to on the SQL Server, or at least on Azure SQL Database (I would expect the same would apply for an on-prem SQL Server).

As a simple demonstration, run this:

```sql
CREATE TABLE [test].[GuidTest](
    id uniqueidentifier NOT NULL,
    ordering int NOT NULL,
    CONSTRAINT [PK_GuidTest] PRIMARY KEY CLUSTERED
    (
      id ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

insert into [test].[GuidTest] (id, ordering) values ('2b2dd4d3-cff0-4184-898a-ad6b00d876e1', 0), ('1612e176-9946-4556-b2a8-ad6b00d876e1', 1), ('01c6470f-719a-4424-92fc-ad6b00d876e1', 2), ('c2d82375-73cf-4d78-826e-ad6b00d876e1', 3), ('44f7f082-6059-484c-b80d-ad6b00d876e1', 4), ('a270b8ae-7451-4a42-b3d5-ad6b00d876e1', 5)
```

The values are generated by `GuidCombGenerator` (feel free to generate your own).

Then the following should return the rows ordered also by the `ordering` column:

```sql
select * from [test].[GuidTest] order by id asc
```

But it does not:

| id | ordering |
| -- | -------- |
| C2D82375-73CF-4D78-826E-AD6B00D876E1 | 3 |
| 2B2DD4D3-CFF0-4184-898A-AD6B00D876E1 | 0 |
| 01C6470F-719A-4424-92FC-AD6B00D876E1 | 2 |
| 1612E176-9946-4556-B2A8-AD6B00D876E1 | 1 |
| A270B8AE-7451-4A42-B3D5-AD6B00D876E1 | 5 |
| 44F7F082-6059-484C-B80D-AD6B00D876E1 | 4 |

The Azure SQL Database has a compatibility level 140 (SQL Server 2017).

**Comment by gliljas** [comment]
The timestamp portion is identical in all five rows, making ordering completely random. This happens when GuidCombGenerator is invoked in fast succession.
