### ISSUE TITLE
Bug: PersistentGenericSet allows for duplicates

### ISSUE THREAD

**Issue by fairking** [nhibernate/nhibernate-core#2905]
NH v.5.3.8

The following example allows to add duplicates to the set `Reports`:
``` c#
public class CoreObjectType : BaseEntity, IHaveName
{
        protected CoreObjectType()
        {
        }

        public virtual ISet<Report> Reports { get; protected set; }
}
```
The debugger shows that the `Reports` type is `PersistentGenericSet`. Based on the [MSDN documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iset-1?view=net-5.0) `ISet` is a collection of unique elements. So the `PersistentGenericSet` does not implement the interface's functionality.

Withing that bug I have to validate the collection for duplicates each time before adding a new element. Which is annoying. Could you please fix it if possible. Thanks.

**Comment by fairking** [comment]
The following workaround is not working eather:
```
        public virtual void SetReports(Report defaultReport, IEnumerable<Report> reports)
        {
            DefaultReport = defaultReport;

            Reports.Clear();

            if (defaultReport != null)
                Reports.Add(defaultReport);

            if (reports != null)
                reports.ForEach(x => { if (!Reports.Contains(x)) Reports.Add(x); });
        }

```
So looks like the method Contains is not working eather.

The immediate Window shows that two elements are equal:
```
defaultReport == reports.ToList()[0]
true
```

And here is my example where I add the same instance two times:
![image](https://user-images.githubusercontent.com/13495631/132007741-384b456e-1b28-44e3-b560-e31764b3a60e.png)

**Comment by bahusoid** [comment]
> The immediate Window shows that two elements are equal:

What about `defaultReport.Equals(reports.ToList()[0])` and `defaultReport.GetHashCode() == reports.ToList()[0].GetHashCode`

**Comment by fairking** [comment]
`defaultReport.Equals(reports.ToList()[0])` returns false;
`defaultReport.GetHashCode() == reports.ToList()[0].GetHashCode()` returns true;

**Comment by fairking** [comment]
Looks like I have found something interesting. I have a `Equals` override on my base entity.
``` c#
        public override bool Equals(object obj)
        {
            // https://stackoverflow.com/questions/5002670/lazy-loaded-nhibernate-properties-in-equals-and-gethashcode

            if (obj == null)
                return false;

            if (ReferenceEquals(obj, this))
                return true;

            var otherType = NHibernateProxyHelper.GetClassWithoutInitializingProxy(obj);
            var thisType = NHibernateProxyHelper.GetClassWithoutInitializingProxy(this);
            if (!otherType.Equals(thisType))
                return false;

            var other = obj as BaseEntity;
            if (other == null)
                return false;

            // At least one of the objects is new (Id is empty)
            if (string.IsNullOrEmpty(Id) || string.IsNullOrEmpty(other.Id))
                return false;
            else
                return other.Id.Equals(Id) && other.Version.Equals(Version);
        }
```

The objects `otherType` and `thisType` are not equal. 
`otherType` is `Report`;
`thisType` is `ReportProxyForFieldInterceptor`;
`obj` is `ReportProxy`;
`this` is `ReportProxyForFieldInterceptor`;

The Line 61 returns `false`:
![image](https://user-images.githubusercontent.com/13495631/132023211-fa3549bc-7ef6-4525-8379-ee67bf577754.png)


What do you think about that guys?

**Comment by fairking** [comment]
Ok, I fixed the bug from my side. Please find the edited `Equals` method for the BaseEntity:
``` c#
        public override bool Equals(object obj)
        {
            // https://stackoverflow.com/questions/5002670/lazy-loaded-nhibernate-properties-in-equals-and-gethashcode

            if (obj == null)
                return false;

            if (ReferenceEquals(obj, this))
                return true;

            var otherType = NHibernateProxyHelper.GetClassWithoutInitializingProxy(obj);
            var thisType = !typeof(IFieldInterceptorAccessor).IsAssignableFrom(this.GetType())
                ? NHibernateProxyHelper.GetClassWithoutInitializingProxy(this)
                : this.GetType().BaseType;
            if (!otherType.Equals(thisType))
                return false;

            var other = obj as BaseEntity;
            if (other == null)
                return false;

            // At least one of the objects is new (Id is empty)
            if (string.IsNullOrEmpty(Id) || string.IsNullOrEmpty(other.Id))
                return false;
            else
                return other.Id.Equals(Id) && other.Version.Equals(Version);
        }
```
Please feel free to close the ticket if you think everything is ok from your side. Thanks.

**Comment by fredericDelaporte** [comment]
When overriding `Equals`, if any kind of proxification is enabled, or if there is some inheritance mapped, comparing types is a bug, on the user code side.
If no inheritance is used (not your case), the code should just try-cast to the expected type. Otherwise you should check for `obj` type being assignable to `this` type or conversely. If one of them is true, then compare identity, otherwise yield false.

Your proposed fix for your equal method is not enough because there are other kind of proxies, and because inheritance can complicate things too. If a base class is mapped (mapped inheritance) and loaded as a proxy, your `Equal` code would not be able to correctly compare it to the same unproxied entity.

**Comment by fairking** [comment]
Very appreciate your response. So you think the `if (!this.GetType().IsAssignableFrom(obj.GetType())) return false;` would be the right solution? I think every project using NH has the same dilemma with `Equals`. I cannot see the reason to not to override it. Maybe we can build the optimal solution so everyone can use it.

**Comment by fairking** [comment]
My proposition:
``` c#
public override bool Equals(object obj)
{
    // https://stackoverflow.com/questions/5002670/lazy-loaded-nhibernate-properties-in-equals-and-gethashcode

    if (obj == null)
        return false;

    if (ReferenceEquals(obj, this))
        return true;

    // We are compairing types because there could be duplicate identifiers across different types.
    var otherType = NHibernateProxyHelper.GetClassWithoutInitializingProxy(obj);
    var thisType = NHibernateProxyHelper.GetClassWithoutInitializingProxy(this);
    if (!thisType.IsAssignableFrom(otherType))
        return false;

    // Cast to base type
    var other = obj as BaseEntity
        ?? throw new ArgumentNullException(nameof(obj), $"Something went wrong. The type check has not been passed properly for the '{obj.GetType().FullName}'.");

    // At least one of the objects is new (Id is empty)
    if (string.IsNullOrEmpty(Id) || string.IsNullOrEmpty(other.Id))
        return false;
    else
        return other.Id.Equals(Id);
}
```

**Comment by fredericDelaporte** [comment]
This topic of defining a base class with a "generic" `Equals` and `GetHashCode` implementation is indeed well known, but as far as I know, it is mainly to be found in the book "NHibernate Cookbook", recipe "Setting up a base entity class".

Your code is not actually enough, because they are different kinds of proxies: in some corner cases we may have two different kinds of proxies for two instances of the same entity. In such case, the assignable test will yield false, causing again the trouble you report.

The Nhibernate Cookbook has a kind of workaround for this, which I deem incorrect, as explained in this [question and answers](https://stackoverflow.com/q/5686604/1178314). But I also provide alternative solutions.
