### ISSUE TITLE
NHibernate Jira account

### ISSUE THREAD

**Issue by sebersole** [nhibernate/nhibernate-core#2918]
I'm the lead of Hibernate and am currently listed as the contact for the NHibernate Jira account back when we all had a relationship.  

Atlassian reached out to me about this site and I told them I am not nor want to be involved with it.  They need the email of the person who should be listed as the contact.  No idea what they will do if no one steps up.  Contact Atlassian directly or PM me and I'll reply to them

**Comment by fredericDelaporte** [comment]
Any volunteer?

**Comment by hazzik** [comment]
@sebersole please refer them to me hazzik @gmail.com

**Comment by sebersole** [comment]
Done

**Comment by hazzik** [comment]
Thanks
