### ISSUE TITLE
Nhibernate performance test

### ISSUE THREAD

**Issue by Bondixi** [nhibernate/nhibernate-core#2962]
Hello!
On our project, there were difficulties with getting a large number of records from the table.
With a sample of 1,000,000 records, nhibernate has a rather low performance compared to other orm (Entiy Framework and Dapper).
Attached to the message is a project that we used to compare performance.
Also, according to the results of the study, it became clear to us that in the Stateful mode, the samples are slightly faster than in the Stateless. And approximately the same amount of memory is allocated. We expected Stateless to be more efficient.
Please advise what could be the reason for this behavior of the system and which configuration is the most optimal?

Oracle Database 19c - Version 19.3.0.0.0

Our results:
Method | Mean | Error | StdDev | Min | Max | Median | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 | Allocated
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Dapper | 34.40 s | 4.769 s | 1.239 s | 33.53 s | 36.47 s | 33.83 s | 1.00 | 0.00 | 107000.0000 | 31000.0000 | 4000.0000 | 643 MB
EFCoreWithTracking | 33.26 s | 4.600 s | 1.195 s | 32.34 s | 35.24 s | 32.96 s | 0.97 | 0.02 | 186000.0000 | 51000.0000 | 3000.0000 | 1,252 MB
EFCoreWithNoTracking | 32.06 s | 3.801 s | 0.987 s | 30.93 s | 32.99 s | 32.36 s | 0.93 | 0.04 | 86000.0000 | 31000.0000 | 4000.0000 | 506 MB
NHibernateStateless_Default | 64.45 s | 3.581 s | 0.930 s | 63.48 s | 65.68 s | 64.42 s | 1.88 | 0.06 | 234000.0000 | 76000.0000 | 7000.0000 | 1,504 MB
NHibernateStateful_Default | 65.67 s | 7.211 s | 1.873 s | 63.83 s | 68.12 s | 65.57 s | 1.91 | 0.08 | 234000.0000 | 76000.0000 | 7000.0000 | 1,504 MB
NHibernateStateless_Optimized | 44.42 s | 24.683 s | 6.410 s | 39.27 s | 55.20 s | 42.98 s | 1.29 | 0.20 | 234000.0000 | 76000.0000 | 7000.0000 | 1,504 MB
NHibernateStateful_Optimized | 39.89 s | 11.240 s | 2.919 s | 37.84 s | 44.98 s | 38.99 s | 1.16 | 0.04 | 234000.0000 | 76000.0000 | 7000.0000 | 1,504 MB

Steps to reproduce:
1. Run the script \OrmBenchmark\Sql\CreateAndEnfill.sql to create and fill the test table.
2. Check orm settings if necessary.
3. Specify the DB connection string in Constants.CONNECTION_STRING
4. Run the application in release mode (this is required for BenchmarkDotNet to work).

[OrmBenchmark.zip](https://github.com/nhibernate/nhibernate-core/files/7761781/OrmBenchmark.zip)

**Comment by NikitaEgorov** [comment]
MSSQL 15.0.2080.9 (MicrosoftDataSqlClientDriver)

|                        Method |    Mean |    Error |   StdDev |  Median |     Min |      Max | Ratio | RatioSD |       Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|------------------------------ |--------:|---------:|---------:|--------:|--------:|---------:|------:|--------:|------------:|-----------:|----------:|----------:|
|                        Dapper | 1.996 s | 0.9780 s | 0.2540 s | 1.892 s | 1.848 s |  2.447 s |  1.00 |    0.00 |  57000.0000 | 21000.0000 | 3000.0000 |    458 MB |
|            EFCoreWithTracking | 5.508 s | 9.8642 s | 2.5617 s | 4.226 s | 4.059 s | 10.017 s |  2.80 |    1.40 | 143000.0000 | 53000.0000 | 6000.0000 |  1,251 MB |
|          EFCoreWithNoTracking | 2.025 s | 1.1963 s | 0.3107 s | 1.917 s | 1.818 s |  2.573 s |  1.01 |    0.04 |  65000.0000 | 24000.0000 | 4000.0000 |    504 MB |
|   NHibernateStateless_Default | 8.507 s | 7.9593 s | 2.0670 s | 7.267 s | 7.251 s | 12.023 s |  4.29 |    1.08 | 142000.0000 | 49000.0000 | 6000.0000 |  1,319 MB |
|    NHibernateStateful_Default | 7.618 s | 2.5391 s | 0.6594 s | 7.361 s | 7.266 s |  8.795 s |  3.83 |    0.14 | 142000.0000 | 49000.0000 | 6000.0000 |  1,319 MB |
| NHibernateStateless_Optimized | 8.389 s | 8.0553 s | 2.0919 s | 7.465 s | 7.425 s | 12.131 s |  4.16 |    0.45 | 142000.0000 | 49000.0000 | 6000.0000 |  1,319 MB |
|  NHibernateStateful_Optimized | 8.850 s | 8.4280 s | 2.1887 s | 7.596 s | 7.459 s | 12.579 s |  4.48 |    1.22 | 142000.0000 | 49000.0000 | 6000.0000 |  1,319 MB |

**Comment by hazzik** [comment]
@Bondixi @NikitaEgorov what do you expect us to do with this information?

**Comment by Bondixi** [comment]
Help us with the optimal system setup. Or will we not be able to achieve a better result?

**Comment by gliljas** [comment]
The results are interesting and worth investigating, especially regarding stateful vs stateless, although the sample size is quite far above what is actually worth considering.

**Comment by mxmissile** [comment]
This data is irrelevant and like comparing apples and oranges IMO. If I had to pull 1,000,000 records from a db, I wouldn't touch any ORM.

**Comment by oskarb** [comment]
If I am loading large amounts of records through NHibernate, e.g. for API response or dumping into a bulk report, I find that having NHibernate project it directly to a simple DTO (i.e. a class not part of the mapping configuration) using a select clause can give a huge performance increase, at least compared to regular stateful session.

The sample size is much larger than the use case NHibernate is designed for though - most real-world use-cases load much fewer objects.

All this would be much more interesting if there were some profiling data and not just numbers. If it's possible to identify particular hotspots that could be optimized with relative ease, I doubt anyone would object to it.

**Comment by hazzik** [comment]
To vague and not actionable, unfortunately. It would be much better if some concrete recommendations were presented. Like memory or performance profiling results and actions from them.

**Comment by hazzik** [comment]
> Also, according to the results of the study, it became clear to us that in the Stateful mode, the samples are slightly faster than in the Stateless. And approximately the same amount of memory is allocated. We expected Stateless to be more efficient.

Because someone down the lane decided that it would be a good idea for "Stateless" session to do some additional operations it did not do before: like resolve graphs of entities, doing basic lazy-loading, lazy-loaded properties, etc. So, in fact "Stateless" session is just a session that throws out the persister's state after it finishes the operation.
