### ISSUE TITLE
Apply for prefix reservation on NuGet

### ISSUE THREAD

**Issue by fredericDelaporte** [nhibernate/nhibernate-core#2969]
See [prefix reservation odcumentation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation), we should apply for the NHibernate prefix reservation on NuGet with the NHibernate organization as an owner of the prefix.

But we should before that decide whether we let the prefix be public, allowing other package owners to publish with the NHibernate prefix, but without the visual hint of prefix ownership, or not, which would prevent new NuGet package names with the NHibernate prefix to be published outside of the NHibernate organization. (Already published packages can still be updated without owning the prefix.)

**Comment by bahusoid** [comment]
>  whether we let the prefix be public, allowing other package owners to publish with the NHibernate prefix, but without the visual hint of prefix ownership

See no reasons to forbid using this prefix. Custom libraries for NHibernate should be allowed to have NHibernate prefix.

**Comment by hazzik** [comment]
While we were deciding on the option, it just became the only option.

**Comment by hazzik** [comment]
I've applied. Got confirmation. They'll promised to come back to me in 3 days.

**Comment by hazzik** [comment]
Reserved

**Comment by fredericDelaporte** [comment]
According to the [prefix documentation](https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-on-nugetorg), the default behavior is to reject push from people outside of the organization having reserved the prefix. So @hazzik if they were not letting you choose to be public or not, it means our reservation is not public and forbid newcomers to publish a package with the NHibernate prefix.

Still the same [documentation](https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#advanced-prefix-reservation-scenarios) does write about public registration, to be asked at the time of reserving. So either it has came back or the documentation is outdated.

I cannot find more information about what kind of prefix reservation do we have on the NuGet site. Maybe we need to ask account@nuget.org about this.

**Comment by dennis-gr** [comment]
Anyone? @hazzik @fredericDelaporte
