### ISSUE TITLE
References with CompositeId not working properly in version 5.3 or above

### ISSUE THREAD

**Issue by thomazoro** [nhibernate/nhibernate-core#3003]
Last week I try to update my NHibernate library from 5.2.0 to 5.3.10.

When i was testing my APIs, I realize that when accessing more than one time the entity property, without editing the value the composite primary key was changed, just by accessing via debugger twice without moving to the next line;

I got: 
1st call: P0: 69; P1: 1
2nd call: P0: 1; P1: 1

Correct 1st call:
![image](https://user-images.githubusercontent.com/40188570/150847063-44a3b084-1943-439a-a925-d0f51b57fa07.png)

2nd call and then
![image](https://user-images.githubusercontent.com/40188570/150847167-3d6d7b76-da09-450a-8899-444216a255a4.png)

My config is something like this:

`

    public class FooRef1
    {
        public virtual int Id { get; protected set; }
        public virtual string Description { get; protected set; }
    }
    public class FooRef2
    {
        public virtual int Id { get; protected set; }
        public virtual string Description { get; protected set; }
    }
    public class Foo
    {
        public virtual FooRef1 Ref1 { get; protected set; }
        public virtual FooRef2 Ref2 { get; protected set; }

        public override int GetHashCode()
        {
            unchecked
            {
                int hash = 13;
                hash = (hash * 7) + (Ref1.Id.GetHashCode());
                hash = (hash * 7) + (Ref2.Id.GetHashCode());
                return hash;
            }
        }

        public override bool Equals(object obj)
        {
            return obj is Foo foo &&
                Ref1.Id == foo.Ref1.Id &&
                Ref2.Id == foo.Ref2.Id;
        }
    }

    public class Bar
    {
        public virtual int Id { get; protected set; }
        public virtual Foo Foo { get; protected set; }
    }

    public class FooRef1Map : ClassMap<FooRef1>
    {
        public FooRef1Map()
        {
            Schema("Schema");
            Table("FOO_REF_1");
            Id(x => x.Id).Column("REF_1_ID");
            Map(x => x.Description).Column("REF_1_DESC");
            ReadOnly();
        }
    }
    public class FooRef2Map : ClassMap<FooRef2>
    {
        public FooRef2Map()
        {
            Schema("Schema");
            Table("FOO_REF_2");
            Id(x => x.Id).Column("REF_2_ID");
            Map(x => x.Description).Column("REF_2_DESC");
            ReadOnly();
        }
    }
    public class FooMap : ClassMap<Foo>
    {
        public FooMap()
        {
            Schema("Schema");
            Table("FOO");
            CompositeId()
                .KeyReference(x => x.Ref1, "REF_1_ID")
                .KeyReference(x => x.Ref2, "REF_2_ID");
            ReadOnly();
        }
    }
    public class BarMap : ClassMap<Bar>
    {
        public BarMap()
        {
            Schema("Schema");
            Table("BAR");
            Id(x => x.Id).Column("BAR_ID");
            References(x => x.Foo).Columns("REF_1_ID", "REF_2_ID");
            ReadOnly();
        }
    }
`

And in my service when I access Foo in Bar more than 1 time this occurs.

**Comment by bahusoid** [comment]
Need a test case. It's not really clear what you mean by 1-st and 2-nd call. And what's going on inside your calls. Can you double check by code and not via debugger that values are incorrect inside your entity. Something like:
```C#
if(bar.Foo.Ref1 != expectedValue)
   throw new ApplicationException("Invalid value detected");
```

**Comment by thomazoro** [comment]
I checked that, I got an error inside my service and confirm the error via console.

One case is:
```
var bar = session.Query<Bar>().Where(p => p.Id == 1).SingleOrDefault();
//First call
var x = 0;
if (bar.Foo.Ref2.Id == 1)
{
    x = 1;
}
if (bar.Foo.Ref2.Id == 1)
{
    x = 2;
}
//the final valor of x is 1
```
And this only occurs on NHibernate version >=5.3

**Comment by thomazoro** [comment]
Sorry I forgot to add in the example, but all of my properties have virtual

**Comment by bahusoid** [comment]
> Sorry I forgot 

The main problem with such examples something is always forgotten. I tried to reproduce it and everything is working as expected https://github.com/bahusoid/nhibernate-core/tree/gh3003

So it looks like some external issue in your code unless you provide a fully reproducible example.

**Comment by hazzik** [comment]
Seems like debugger interferes with proxy factory.
