### ISSUE TITLE
LINQ select/distinct with multiple columns doesn't work

### ISSUE THREAD

**Issue by nfplee** [nhibernate/nhibernate-core#3023]
I have the following structure:

Products
- Id
- Name

Fields
- Id
- Name

ProductFieldValues
- ProductId
- FieldId
- Value

Where the `FieldValues` are mapped as a collection against the `Product` entity like so:

```
Bag(x => x.FieldValues, m => {
    m.Key(k => k.Column("ProductId"));
    m.Inverse(true);
    m.Cascade(Cascade.All | Cascade.DeleteOrphans);
}, m => m.OneToMany());
```

If I try the following query:

```
var fieldValues = await _dataContext.Repository<Product>().All()
    .SelectMany(p => p.FieldValues)
    .Select(fv => new { fv.Value })
    .Distinct()
    .ToListAsync();
```

It correctly produces:

> select distinct fieldvalue1_.Value as col_0_0_ from [dbo].Products product0_ inner join [dbo].ProductFieldValues fieldvalue1_ on product0_.Id=fieldvalue1_.ProductId

However if I try selecting multiple columns like so:

```
var fieldValues = await _dataContext.Repository<Product>().All()
    .SelectMany(p => p.FieldValues)
    .Select(fv => new { fv.Field.Id, fv.Value })
    .Distinct()
    .ToListAsync();
```

This produces:

> select distinct fieldvalue1_.ProductId as col_0_0_, fieldvalue1_.FieldId as col_0_1_, fieldvalue1_.Value as col_1_0_, fieldvalue1_.ProductId as productid1_59_, fieldvalue1_.FieldId as fieldid2_59_, fieldvalue1_.Value as value3_59_ from [dbo].Products product0_ inner join [dbo].ProductFieldValues fieldvalue1_ on product0_.Id=fieldvalue1_.ProductId

Notice this has two problems:

1. It duplicates the columns it selects
2. It selects the product id

The second issue is the bigger problem as it means I now get duplicates.

**Comment by bahusoid** [comment]
Is it reproducible with NHibernate 5.3.11?

**Comment by nfplee** [comment]
> Is it reproducible with NHibernate 5.3.11?

I'm currently using 5.3.10.

**Comment by nfplee** [comment]
Please ignore this my bad. I was using a composite id for my `ProductFieldValue` and my query should've been:

```
var fieldValues = await _dataContext.Repository<Product>().All()
    .SelectMany(p => p.FieldValues)
    .Select(fv => new { fv.Id.Field.Id, fv.Value })
    .Distinct()
    .ToListAsync();
```

**Comment by jorgearana** [comment]
Hi, it is possible to disable this bad method? for me its a better solution morelinq distictby. 

I have more than 10,000 records in a table that records the status of some cases. Each update creates a record with the same case but different status and the date.

With linq I first have to download the 10000 records and when it's already an ienumerable list I can just use distinctby.

With morelinq, the discinctby is done before making the list, so I only have to download about 100 records.

Anyway, what I want to do is use morelinq and delete the lina method
