### ISSUE TITLE
NHibernate Dev package

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#3039]
Hi,
Latest "Set which entities classes should never be cached, even indirectly" commit does not published to NHibernate.dev package. could you please trigger necessary jobs to deploy dev nuget?

https://www.myget.org/feed/nhibernate/package/nuget/NHibernate

NHibernate Version="5.4.0-dev.3725"

Fluent NHibernate Mapping

```c#
Cache.CustomUsage("never");
```

```c#
NHibernate.Cfg.Configuration:(XmlDocument)(3,12): XML validation error: The 'usage' attribute is invalid - The value 'never' is invalid according to its datatype 'String' - The Enumeration constraint failed.
NHibernate.MappingException: (XmlDocument)(3,12): XML validation error: The 'usage' attribute is invalid - The value 'never' is invalid according to its datatype 'String' - The Enumeration constraint failed.
 ---> System.Xml.Schema.XmlSchemaValidationException: The 'usage' attribute is invalid - The value 'never' is invalid according to its datatype 'String' - The Enumeration constraint failed.
 ---> System.Xml.Schema.XmlSchemaException: The Enumeration constraint failed.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
```

**Comment by bahusoid** [comment]
5.4.0-dev.3745 should be published

Interesting why it's not been triggered automatically...

**Comment by bahusoid** [comment]
> why it's not been triggered automatically.

It's been triggered: https://teamcity.jetbrains.com/viewLog.html?buildId=3816898&buildTypeId=NHibernate_NHibernatePublishNuGet&tab=buildLog&branch_NHibernate=pull%2F2879

Seems artifact resolution is a bit buggy. It tries to use binaries from latest release build from all branches (so tried to publish 5.3 build in this case)
