### ISSUE TITLE
ISession.Persist vs ISession.Save

### ISSUE THREAD

**Issue by fabiomaulo** [nhibernate/nhibernate-core#3040]
IIRC, the main difference between ISession.Persist and ISession.SaveOrUpdate was about the `id` behavior; using `Persist` the `id` of all objects in the graph were immediately available because the `Persist` transforms a transient object into a persistent one, even if you don't have it, in the DB, until you commit the transaction.
The current documentation of `ISession.Persist` is 
```
Make a transient instance persistent. This operation cascades to associated instances if the association is mapped with cascade="persist". 
The semantics of this method are defined by JSR-220.
```
I saw a _Possible breaking change_ in the version 5.3.0 release notes but now I can't understand which is the true and/or which is the alternative to have all objet-graph with its ID assigned.

Because of the above, I don't know how to qualify this issue:
- Documentation issue
- question
- Regression bug

Thanks in advance.

**Comment by fredericDelaporte** [comment]
#1754 gives the rational behind the change, which can actually be seen as a fix for a 2.0 regression. `Persist` is not meant to guarantee ids are available. For that, either use `Save` for a single entity, or `Flush` the session. (Or manually walk the entity graph for saving each of them, or setup cascade on save, ...)

**Comment by fabiomaulo** [comment]
Hibernate:
One more thing which differentiates persist and save method in Hibernate is that it is their behavior on the _**outside** of transaction boundaries._ persist() method guarantees that it will not execute an INSERT statement **if it is called outside of transaction boundaries**. save() method does not guarantee the same, it returns an identifier, and if an INSERT has to be executed to get the identifier (like "identity" generator), this INSERT happens immediately, no matter if you are inside or outside of a transaction.

Now https://docs.jboss.org/hibernate/core/3.6/reference/en-US/html/objectstate.html#objectstate-makingpersistent
_persist() makes a transient instance persistent. However, it does not guarantee that the identifier value will be assigned to the persistent instance immediately, the assignment might happen at flush time. persist() also guarantees that it will not execute an INSERT statement **if it is called outside of transaction boundaries**. This is useful in long-running conversations with an extended Session/persistence context._

My comment:
The _if it is called outside of transaction boundaries_ makes the difference, no matter which is the Flush mode.

**Comment by fabiomaulo** [comment]
Comment and solution posted at #1754

**Comment by hazzik** [comment]
I'm not sure why you're ignoring this part of the quote:

> However, it does not guarantee that the identifier value will be assigned to the persistent instance immediately, the assignment might happen at flush time.

Here is nothing about the transaction boundaries.

**Comment by fabiomaulo** [comment]
Comment, solution and considerations posted at #1754
Thanks.
