### ISSUE TITLE
LINQ query dynamic component by interface hangs the application

### ISSUE THREAD

**Issue by nfplee** [nhibernate/nhibernate-core#3150]
I have the following query which executes fine:

```
var posts = await session.Query<BlogPost>()
    .Where(p => p.Attributes["Field1"] != null)
   .ToListAsync();
```

However if I change it to use an interface instead then the query hangs.

```
var posts = await session.Query<IBlogPost>()
    .Where(p => p.Attributes["Field1"] != null)
    .ToListAsync();
```

Please see the attached application which helps demonstrate this. This problem only happens when filtering against an attribute.

[ConsoleApp1.zip](https://github.com/nhibernate/nhibernate-core/files/9483340/ConsoleApp1.zip)

**Comment by bahusoid** [comment]
Infinite loop
https://github.com/nhibernate/nhibernate-core/blob/6c702172b255b5007c026df57472235ceac47728/src/NHibernate/Linq/Visitors/VisitorUtil.cs#L27-L50

Introduced in  https://github.com/nhibernate/nhibernate-core/pull/237 (4.0.0.Alpha2)

**Comment by bahusoid** [comment]
It's not a regression. It didn't stuck before #237 but failed in some other way - dynamic components on unmapped interface never worked.

**Comment by nfplee** [comment]
@bahusoid do you have a suggestion for a temporary fix?

**Comment by bahusoid** [comment]
> do you have a suggestion for a temporary fix?

Map it as interface (`ClassMapping<IBlogPost>`)

**Comment by nfplee** [comment]
Thanks @bahusoid, I tried switched my class mapping from `BlogPost` to `IBlogPost` but this now makes the first query hang and the second query throws the exception "NHibernate.InstantiationException: 'Cannot instantiate abstract class or interface: '".

If I try mapping both `BlogPost` and `IBlogPost` then the first query now works again but the second query throws the same exception above.

**Comment by bahusoid** [comment]
>the second query throws the exception "NHibernate.InstantiationException: 'Cannot instantiate abstract class or interface: '".

You have to specify concrete class in mapping too via `Class<BlogPost>();`.

**Comment by nfplee** [comment]
I already tried looking into this as this is what I do for my components. However the `Class` method is not available in the `ClassMapping` class. Looking into the code for the `Class` method against the `ComponentMapping` I tried adding:

```
CustomizersHolder.AddCustomizer(typeof(IBlogPost), m => m.Class(typeof(BlogPost)));
```

But this had no effect.

**Comment by bahusoid** [comment]
>  this is what I do for my components. However the Class method is not available in the ClassMapping class. Lo

Indeed. It seems I thought of component mapping myself. You can try to specify `EntityName(typeof(IBlogPost).FullName)` in your class mapping - but it should(?) make work only direct queries on interface. It will stuck for class.

**Comment by nfplee** [comment]
Thanks @bahusoid that worked. Please note this doesn't fix the original issue, it just flips it so now when querying a dynamic component against the `BlogPost` class it hangs. This works better for me as my dynamic component is an attributes collection which allows me to dynamically add properties to my entities where I can't modify the concrete type, therefore I'm more likely to query the attributes against the `IBlogPost` abstraction.

**Comment by nfplee** [comment]
I've decided that the fix of using `EntityName(typeof(IBlogPost).FullName)` in the mapping is actually the correct way to go as now I don't need to add conventions for my abstractions.

I debated closing out this issue but I'll leave it open as it would be better to throw an exception than get stuck an infinite loop.
