### ISSUE TITLE
LINQ .FetchMany() + .Take() does not work as expected (and should throw?)

### ISSUE THREAD

**Issue by razzmatazz** [nhibernate/nhibernate-core#3159]
We got bit by this so often in production, so I figured I would post an issue.

Consider we have:
```csharp
class DBChild
{
}

class DBObject
{
ICollection<DBChild> Chilldren { get; set; }
}
```

Then we have code that queries records on db:
```csharp
var query = db.Query<DBObject>().FetchMany(o => o.Children).Take(10).ToList();
```

This unexpectedly may return less than 10 DBObject's if any of them contain more than 1 `.Children`.

Basically, we often have a `IQueryable<DBObject>` that we use `.FetchMany()` on and then apply a `.Take()`. It appears like in case of `.FetchMany()` NHibernate produces a SQL join (i.e. N x M) but *usually* the user usually expects the parameter of `.Take()` to be applied on Ns (DBObject, in this case).

Often we add `.FetchMany()` to apply optimizations to performance of the system but it then introduces a bug, unexpectedly (and silently at that!).

Would it make sense that IQueryable with .FetchMany() + .Take() would rather throw than produce unexpected results?

I tried searching for a duplicate issue, but could not find any that corresponds to this.

**Comment by razzmatazz** [comment]
Oh, looks to be a duplicate of https://github.com/nhibernate/nhibernate-core/issues/1281; closing this one.

**Comment by hazzik** [comment]
Yes it is

**Comment by hazzik** [comment]
Duplicate of https://github.com/nhibernate/nhibernate-core/issues/1281
