### ISSUE TITLE
Wrong name value for L2 read-only cache warning on mutable

### ISSUE THREAD

**Issue by spasecookee** [nhibernate/nhibernate-core#3210]
The way SessionFactoryImpl.GetCacheConcurrencyStrategy() is currently written, if a warning is logged, "read-only cache configured for mutable: {0}", the value provided to the log message is the readonly variable "name" which is always set to the value of the SessionFactoryName setting. This value is not very useful when trying to track down the source of the problem. 

Instead something like the model.ClassName or model.Type.Name should be included in the logging message, depending on the caller. Alternatively, the log.warn should be moved outside GetCacheConcurrencyStrategy() and logged by the callers.

**Comment by bahusoid** [comment]
Fixed by #3268
