### ISSUE TITLE
Creating a proxy instance failed (ctor() is inaccessible)

### ISSUE THREAD

**Issue by vmato** [nhibernate/nhibernate-core#3221]
Under mono 6.8.0.105 received following error:

```
System.AggregateException: One or more errors occurred. (Creating a proxy instance failed) ---> NHibernate.HibernateException: Creating a proxy instance failed ---> System.MethodAccessException: Method `Model..ctor()' is inaccessible from method `ModelProxy..ctor(NHibernate.Proxy.ILazyInitializer,NHibernate.Proxy.NHibernateProxyFactoryInfo)'
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_throw_method_access(intptr,intptr)
```

Why constructor may be inaccessible? How to make it available?
Changing model class from internal to public didn't change the situation

**Comment by bahusoid** [comment]
Does it have public default constructor (without parameters)?

**Comment by vmato** [comment]
We've added empty constructor like 
`public Model() { }`
and it worked. 

Looks like automatic default constructor was not generated or suitable.
Under windows automatic constructors always worked
