### ISSUE TITLE
NHibernate 5.2.0 on .NET Core  memory leak ？？

### ISSUE THREAD

**Issue by chengang-hub** [nhibernate/nhibernate-core#3228]
Nhibernet consumes 500M memory when initializing：
configuration.BuildSessionFactory() : 300M
![image](https://user-images.githubusercontent.com/108459883/216223434-7620db05-7a56-4cce-bc98-4daa15b73b81.png)

this is  current_session_context_class:
![image](https://user-images.githubusercontent.com/108459883/216223582-b83b48f0-035f-4415-8258-d0f91c7a117f.png)

MappingByCode:   80M
![image](https://user-images.githubusercontent.com/108459883/216223706-205c561e-c902-45a2-a650-efea223114fc.png)

Startup: 0~550M 
![b4261413fa4ef983dff3c14ac25cc96e](https://user-images.githubusercontent.com/108459883/216224074-a18f5632-7df9-446d-a37d-f58d8a36aa96.png)

After a day, the system occupies 5G memory
![image](https://user-images.githubusercontent.com/108459883/216224565-2b21a0e8-e284-4cbd-b5dd-bb0e68707fe1.png)

 Is it my usage wrong？ thanks！！！

**Comment by chengang-hub** [comment]
this is NHSessionFac
![image](https://user-images.githubusercontent.com/108459883/216225715-8be373d9-b058-4133-94c0-de1b3311232d.png)


this is SearchBase：
![image](https://user-images.githubusercontent.com/108459883/216225561-d7ae483a-2307-4d38-a740-5b6643cffef6.png)

**Comment by hazzik** [comment]
Hi @chengang-hub unfortunately we would not be able to help as the memory consumption is dependent on a specific use case. And we do not have your exact mappings and code base. It would be best if you can identify what holds the memory.

Also, 5.2.0 is way too old and we do not have plans to provide support for it.

**Comment by bahusoid** [comment]
At a very quick glance at `SearchBase`.  New session is opened and not disposed when `License.IsQueryOnly == true`. That might be the source of your leak.

**Comment by hazzik** [comment]
Probably an user error as per @bahusoid. Please open a new issue with precise reproduction steps.
