### ISSUE TITLE
IsDirty performance hit from 5.3.16 to 5.4.2

### ISSUE THREAD

**Issue by trivalik** [nhibernate/nhibernate-core#3307]
I faced a longer IsDirty run after upgrading.

NHibernate 3.3.1:

![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/a963b1ca-7aff-4dda-bfcb-0e417e290c37)

NHibernate 5.4.2:

![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/45536834-e16b-45a1-a61f-165816860d80)

The first question is, was there a bug in old implementation that now lead to this cascade?
Since the result of IsDirty is true in both cases, I can imagine that there is optimization potential.

The test case of IsDirty is there that we have a table which stores for every element a parent element (not lazy load). The children are as HasMany relation. We remove just near all elements, and this lead to this bad result.

**Comment by hazzik** [comment]
@trivalik can you share full screenshot for 3.3.1 and also expand all trees for `CascadeToOne`?

**Comment by trivalik** [comment]
For 3.3.1 is through there was none, it was:

![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/774705a6-6fad-4d7b-8528-a3f60be3968e)


For 5.4.2 ( I can imagine that CascadeAfterSafe the problem is like in https://github.com/nhibernate/nhibernate-core/issues/1413):
![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/ea181e50-6e24-4bb6-948d-f2fdb12f32d3)

**Comment by bahusoid** [comment]
You said you have the same performance issue with 5.3. Did you check with 5.2? Can you share how profiling looks for 5.3

**Comment by trivalik** [comment]
Wow. I wasn't aware that 5.3.16 has also 7ms. 

![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/ec0914f2-a12d-42eb-8e5a-99d4a90d6b7e)

**Comment by bahusoid** [comment]
> I wasn't aware that 5.3.16 has also 7ms.

Then it's likely #2752 to blame

**Comment by trivalik** [comment]
I can confirm that the over 1 second run for `IsDirty` starts with the changes in commit 89a79d29d2d1b41f81ea12714b2bb07045fc95d8.

**Comment by hazzik** [comment]
@trivalik if in that commit you change Persist to PersistOnFlush - does it change anything? 

Also do you have any test case to reproduce this?

**Comment by trivalik** [comment]
The change to:

```
protected override CascadingAction CascadingAction => CascadingAction.PersistOnFlush;
```

requires more time than just `CascadingAction.Persist`.

Right now I have only my private test case but no general for your test suite.

**Comment by hazzik** [comment]
> I ended up the following, but not sure if this is actually the repro

@trivalik, I'm not sure either.

Can you please test if changing this code: https://github.com/nhibernate/nhibernate-core/blob/90d50c03475628d10336cbad368f071375056fef/src/NHibernate/Event/Default/AbstractFlushingEventListener.cs#L187-L202

And moving `Anything` out of the `foreach` loop fixes anything? Like this:

```csharp
protected virtual void PrepareEntityFlushes(IEventSource session)
{
	log.Debug("processing flush-time cascades");

	ICollection list = IdentityMap.ConcurrentEntries(session.PersistenceContext.EntityEntries);
	var context = Anything; // <<<< HERE
	//safe from concurrent modification because of how entryList() is implemented on IdentityMap
	foreach (DictionaryEntry me in list)
	{
		EntityEntry entry = (EntityEntry) me.Value;
		Status status = entry.Status;
		if (status == Status.Loaded || status == Status.Saving || status == Status.ReadOnly)
		{
			CascadeOnFlush(session, entry.Persister, me.Key, context /* <<<< HERE */);
		}
	}
}
```

**Comment by bahusoid** [comment]
Or inside `DefaultDirtyCheckEventListener`
```C#
private object _map = IdentityMap.Instantiate(10);
protected override object Anything => _map;
```

**Comment by hazzik** [comment]
@bahusoid my understanding is that `DefaultDirtyCheckEventListener` is shared, so that should not be done. My suggestion is consistent with how it is done in hibernate:

https://github.com/hibernate/hibernate-orm/blob/156fd51e5c81dc3b5f7fec10bba191468530463e/hibernate-core/src/main/java/org/hibernate/event/internal/AbstractFlushingEventListener.java#L134C1-L147

```java
	private void prepareEntityFlushes(EventSource session, PersistenceContext persistenceContext) throws HibernateException {

		LOG.debug( "Processing flush-time cascades" );

		final PersistContext context = getContext();
		//safe from concurrent modification because of how concurrentEntries() is implemented on IdentityMap
		for ( Map.Entry<Object,EntityEntry> me : persistenceContext.reentrantSafeEntityEntries() ) {
//		for ( Map.Entry me : IdentityMap.concurrentEntries( persistenceContext.getEntityEntries() ) ) {
			final EntityEntry entry = me.getValue();
			if ( flushable( entry ) ) {
				cascadeOnFlush( session, entry.getPersister(), me.getKey(), context );
			}
		}
	}
```

**Comment by trivalik** [comment]
Moving out the Anything, out of the foreach loop lead to no `SaveOrUpdate` call. And solved it for my private test case and for the test case I change in NHibernate.

**Comment by hazzik** [comment]
@trivalik great. Can you submit a PR?

**Comment by hazzik** [comment]
> loop lead to no SaveOrUpdate call.

I cannot get the SaveOrUpdate call with your code.

**Comment by trivalik** [comment]
You are right. I will double check, not sure how long this requires.

**Comment by trivalik** [comment]
You are right the unit test does not create a call of `FireSaveOrUpdate`. But I verified now with 5.4.x branch (before only with the old commit when error comes in), that the calls for `CascadeOn` is increased. Do **not** look on the ms because this profiling was to calculate the exact call count, not the times.

Here for the 5.4.x branch:

![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/1cbbabb0-9290-43d1-b05e-890ef8af621d)

Here with the Anything fix:

![image](https://github.com/nhibernate/nhibernate-core/assets/3148279/6aa5f414-aae0-4dff-8029-9ab255a2c057)
