### ISSUE TITLE
NamedQuery igonres <query-param type="AnsiString"> and any other

### ISSUE THREAD

**Issue by deryaza** [nhibernate/nhibernate-core#3311]
If you write a named query with a parameter like:

```xml
<sql-query name="x">
<query-param name="queryString" type="AnsiString" />
select * from something s where s.some_string_field = :queryString
</sql-query>
```
It will guess a type at this [location](
https://github.com/nhibernate/nhibernate-core/blob/90d50c03475628d10336cbad368f071375056fef/src/NHibernate/Impl/AbstractQueryImpl.cs#LL256C1-L257C1) and ignore parameter description written in ```.hbm.xml``` file.

**Comment by bahusoid** [comment]
Yeah `query-param` elements seems completely ignored.
