### ISSUE TITLE
PostgreSQL: Can not save default char 

### ISSUE THREAD

**Issue by ValResnick** [nhibernate/nhibernate-core#3339]
Hi,

it is not possible to save an enitity with PostgreSQL when a **char** property has the default value. 
The exception is "Npgsql.PostgresException : 22021: invalid byte sequence for encoding "UTF8": 0x00"
It is reproducable with a simple modification of the existing test **NHibernate.Test.TypesTest.CharClassFixture**

```
[Test]
public void ReadWrite()
{
   var basic = new CharClass{Id=1, NormalChar = default(char)};

   using (var s = OpenSession())
   {
      s.Save(basic);
      s.Flush(); // Throws Exception here
   }

  ... 
```

Some Version information:
- NHibernate 5.4.X Branch
- npqSQL 6.0.6
- PostgresSQL 15

**Comment by bahusoid** [comment]
Looks like external issue.  PostgresSQL `char` type doesn't allow to store invalid utf-8 characters. If you want to use some other type for your char property - change the mapping.
