### ISSUE TITLE
GenerateSchemaCreationScript creates many identical dialect instances

### ISSUE THREAD

**Issue by AlexanderKot** [nhibernate/nhibernate-core#3397]
Hello
During generation script for DB creation Nhib 5.4.4 creates dialect instances many times.

![image](https://github.com/nhibernate/nhibernate-core/assets/1678749/d7d43b61-04d8-4e4d-afdc-c4bd7928089d)

It looses passed dialect instance in GetDialectTypeName calling GetSqlTypeCode

GetSqlTypeCode do not take dialect as param....

It creates slowdown and memory traffic.

**Comment by bahusoid** [comment]
Looks related to #1950

**Comment by hazzik** [comment]
It is likely a regression from #703

**Comment by fredericDelaporte** [comment]
Fixed by #3399.

**Comment by AlexanderKot** [comment]
Thank you everybody
Profiling of the same method call on Nhib 5.4.5 - problem solved.
It is taken on ~3 time more powerful PC, so it cannot be directly compared. 

![image](https://github.com/nhibernate/nhibernate-core/assets/1678749/46430b1a-a049-4a1d-becd-5a60bcc5274f)
