### ISSUE TITLE
Fetch Join with many-to-one property results on N + 1 SELECT PROBLEM

### ISSUE THREAD

**Issue by rodrigo-web-developer** [nhibernate/nhibernate-core#3422]
When I'm mapping a many-to-one property with fetch="join" and lazy="false", the Session.Query&lt;T&gt;().ToList() results in a N + 1 select problem.

I saw many issues related with the problem, but it's all closed:

- https://github.com/nhibernate/nhibernate-core/issues/1226
- https://github.com/nhibernate/nhibernate-core/issues/714

I'm using repository pattern to query over database with interface abstractions, I have a generic method Query&lt;T&gt;() which returns IQueryable&lt;T&gt;, making it easy to use and Mock.

For the NHibernate implementation I just return ISession.Query&lt;T&gt;().

Because of session control, we need to use Eager loading approach, so all entities and relationships are loaded on query. Any mapping file has a lazy="false" attribute. I create an example in the following git repository: https://github.com/rodrigo-web-developer/many-to-one-problem.

```cs
    public class Product
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }

        public Category Category { get; set; }
    }
    public class Category
    {
        public long Id { get; set; }
        public string Description { get; set; }
    }
```

Basically I created 2 entites (Product and Category), Product has a property of type Category. 

When I try to query PRODUCTS (with `lazy="false"` and `fetch="join"`) using ISession.Query&lt;Product&gt;().ToList(), the output is the following image:

![image](https://github.com/nhibernate/nhibernate-core/assets/32915160/30dcef09-04eb-425b-a12f-49dc2d049fe2)

When I force the session.Query&lt;Product&gt;().Fetch(x => x.Category).ToList() the output is the following: 

![image](https://github.com/nhibernate/nhibernate-core/assets/32915160/9443399e-5e5f-423d-8d06-12c28a0fd169)

There is a way to create the same behavior without explicitly calling .Fetch()? I have 1 generic method for all queries of all entities, so I cant change all the query callings.

If not, there is a way via mapping to make the many-to-one query creates a batching query? Like &lt;bag&gt; with batch-size.

**Comment by bahusoid** [comment]
> mapping a many-to-one property with fetch="join" and lazy="false", the Session.Query<T>().ToList() results in a N + 1

Looks like duplicate of  https://github.com/nhibernate/nhibernate-core/issues/2716

>  make the many-to-one query creates a batching query? Like <bag> with batch-size.

`batch-size` can be specified in entity mapping. Something like `<class name="Category" batch-size="100" >`. Not sure if it works with `lazy="false"` mapping.

**Comment by rodrigo-web-developer** [comment]
> `batch-size` can be specified in entity mapping. Something like `<class name="Category" batch-size="100" >`. Not sure if it works with `lazy="false"` mapping.

Thanks for your answer, it works to use batch-size inside class tag, which generate less SELECTs. So I see that is not possible to create default join behavior on many-to-one relationships.

I think I can use batch-size over all mappings files which will reduce the queries on bigger schemas.

I will close this issue, thanks
