### ISSUE TITLE
Linq DML not working as expected after Migration to .NET 6

### ISSUE THREAD

**Issue by cjay99** [nhibernate/nhibernate-core#3433]
Good Morning/Evening/Afternoon,

we've encountered an issue during our migration from .NET Framework 4.6.2 to .NET 6 (also updated NHibernate from 5.2.5 to 5.4.6), specifically concerning Linq DML Queries. We rely on Linq DML for bulk operations such as updates, deletes, and inserts. We also maintain several automated integration tests that use an SQLite in-memory database to ensure the functionality works as expected.

Upon migrating, we noticed that some of these integration tests started failing. The tests that are failing are specifically those that invoke methods via the Linq DML interface. The issue appears to be that data isn't being persisted when we use Linq DML.

I've created a sample project to reproduce the problem. This project also uses an in-memory SQLite database, just like our integration tests: [TestNHibernateCore.zip](https://github.com/nhibernate/nhibernate-core/files/12817812/TestNHibernateCore.zip)

_Thank you in advance!_

**Comment by bahusoid** [comment]
> // This behaviour does not exist using NHibernate with .NET Framework 4.8

I didn't really looked in to code because test seems invalid. - it fails for me the same for .NET 4.8.

> we've encountered an issue during our migration from .NET Framework 4.6.2 to .NET 6 (also updated NHibernate from 5.2.5 to 5.4.6), 

Also I downgraded your test project to your working case:
```C#
<PackageReference Include="FluentNHibernate" Version="2.1.2" />
<PackageReference Include="NHibernate" Version="5.2.5" />
```

 and it still fails the same.

**Comment by cjay99** [comment]
Hi,

the project should demonstrate the behaviour using .NET 6 with the latest NHibernate version.

Could you clarify what seems invalid with the demonstration project?

I will look into the sample tomorrow and I will also provide a sample targeting .NET 4.8.

Thank you.

**Comment by bahusoid** [comment]
I've already explained what seems invalid. Test project behavior contradicts to issue description.

> we've encountered an issue during our migration from .NET Framework 4.6.2 to .NET 6 (also updated NHibernate from 5.2.5 to 5.4.6),

Your test project behaves the same for both combinations 
1) .NET 4.6.2 with NHibernate 5.2.5 
2) .NET 6 with NHibernate 5.4

**Comment by cjay99** [comment]
I've done some more research on this topic and found out that the issue only exists using SQLite - in our case, during the integration test. I'll close this issue as the description of this issue does not apply to the behaviour.
