### ISSUE TITLE
SetTimeout not working for simple query on none of QueryOver nor Query

### ISSUE THREAD

**Issue by omidsojoody** [nhibernate/nhibernate-core#3449]
It seems that setting timeout using SetTimeout() method on  QueryOver , Query  or ICritera is not working as expected.

ex:
(session.QueryOver<Message>.SetTimeout(1).List()
or
session.CreateCriteria<Message>().SetTimeout(timeout).List();
or 
var queryResult = session.Query<Message>().WithOptions(option => option.SetTimeout(timeout)).ToList();

I've tried to set timeout on both RootCriteria and UnderlyingCriteria too bot none of them works for me.
did I've done something wrong? or maybe it works on special condition? timeout value has any threshold?

I'm using .NetFramework 4.8 with NHibernate 5.4.6

**Comment by fredericDelaporte** [comment]
This can be database vendor specific. With which database, driver and dialect do you see the trouble? Have you some code available to demonstrate it?

We already have some timeout tests checking the timeout is properly set on the DbCommand.
For example:
https://github.com/nhibernate/nhibernate-core/blob/7a86566437b8bcad019213f83f9b63c02af559a3/src/NHibernate.Test/Linq/QueryTimeoutTests.cs#L15-L21
So, if the issue is in NHibernate, not in the stack your are using, we would need code demonstrating it.

**Comment by omidsojoody** [comment]
I hope that could explain your test case requirements.
 cfg = Fluently.Configure()
.ExposeConfiguration(x => x.SetInterceptor(new NHibernateInterceptor()))
.ExposeConfiguration(x => x.Properties.Add(global::NHibernate.Cfg.Environment.BatchSize, "100"))
.ExposeConfiguration(x => x.Properties.Add(global::NHibernate.Cfg.Environment.MaxFetchDepth, "1"))
.ExposeConfiguration(x => x.Properties.Add(global::NHibernate.Cfg.Environment.FormatSql, "true"))
.ExposeConfiguration(x => x.Properties.Add(global::NHibernate.Cfg.Environment.Isolation, "ReadCommitted"))
.ExposeConfiguration(x => x.Properties.Add(global::NHibernate.Cfg.Environment.SqlExceptionConverter, typeof(StorageExceptionConverter).AssemblyQualifiedName))
.Mappings(x => { x.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()); })
.Database(MsSqlConfiguration.MsSql2012.ConnectionString(config.GetConnectionString()).Dialect<MsSql2012Dialect>())
.CurrentSessionContext("thread_static")
.BuildConfiguration();

and then any simple query with . SetTimeout(1) calls

**Comment by fredericDelaporte** [comment]
That is a timeout in seconds. A simple query will run under one second in most cases. Please see [here](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md#creating-a-test-case-to-verify-the-issue) to provide a test case allowing to reproduce the issue.

**Comment by omidsojoody** [comment]
Sorry i should have explained that before. I have big data on my message table and the generated query by nhibernate for simple get all records takes around 15 second to be completed. (i've seen that using sql profiler) and it will return the result around 18-20 second and ignoring specified 1 second timeout.
This is just used for testing scenario. otherwise i know its useless to get all records this way without paginating and ....
query:
session.Query<Message>().WithOptions(option => option.SetTimeout(timeout)).ToList();

**Comment by omidsojoody** [comment]
yap I'm sure as described before I used SQL Profile to analyze the generated SQL command and its duration. beside the created command will take more than 1 second even in SQL Management studio itself.

**Comment by omidsojoody** [comment]
I think I've found the reason behind this problem. SQL Server will use specified timeout for fetching first result in whole result set (in this case select * from messages) and therefore data reader (behind the scenes in Nihbernate) can get this data without facing timeout problem. because its first result will return before 1 second in my case while the fetching whole result could take around 20 second to be completed.

**Comment by oskarb** [comment]
Great you found what is happening. That is what I was suggesting but in
retrospect I could have worded it differently. :)
