### ISSUE TITLE
The sql type of the CultureInfoType is too short

### ISSUE THREAD

**Issue by zgabi** [nhibernate/nhibernate-core#3473]
The current generated SQL type for the `CultureInfo` object is string(5):
https://github.com/nhibernate/nhibernate-core/blob/07c367fb859086970737c35f24fe66c089a034e2/src/NHibernate/Type/CultureInfoType.cs#L21

But some culture names are much longer. The longest culture names are 11 characters:
en-US-POSIX
mni-Beng-IN
sat-Olck-IN
shi-Latn-MA
shi-Tfng-MA
tzm-Arab-MA
tzm-Tfng-MA
vai-Latn-LR
vai-Vaii-LR

They are very specific, but in our usecase  we use cultures with length of 10 characters. So this is a real problem for us.
Now we get the following exception:
NHibernate.Exceptions.GenericADOException: 'could not execute batch command.[SQL: SQL not available]'
SqlException: String or binary data would be truncated in table ...

**Comment by fredericDelaporte** [comment]
Fixed by #3481. The mapping of properties of this type will accept the `length` setting, allowing to use another length than the default `5` if needed.

**Comment by zgabi** [comment]
Thank you.
But I have a question. How can i use it in an `ICompositeUserType`?
Since it needs an `IType[]`.

Currently I'm using:
`    public override IType[] PropertyTypes { get; } = { NHibernateUtil.String, NHibernateUtil.CultureInfo };

But the constuctor of the CultureInfoType is internal, so I can not specify the length in the user type like the following:
`    public override IType[] PropertyTypes { get; } = { NHibernateUtil.String, new NHibernate.Type.CultureInfoType(xxx) };
``
