### ISSUE TITLE
collection [CollectionKey[]] not located in load context

### ISSUE THREAD

**Issue by Vzzbux** [nhibernate/nhibernate-core#3498]
https://github.com/nhibernate/nhibernate-core/blob/0c3c705cf46a43e459e539e612c3677bae64ef57/src/NHibernate/Engine/Loading/LoadContexts.cs#L242

I was trying to debug an issue and I noticed these messages in the debug log file. Unless I've misunderstood something it looks like the "located" / "not located" strings are the wrong way around for the null check?

**Comment by fredericDelaporte** [comment]
Actually, thanks.
