### ISSUE TITLE
Loss of precision on decimal mapping - NHibernate 5

### ISSUE THREAD

**Issue by walteralmeida** [nhibernate/nhibernate-core#3512]
I am using NHibernate 5 and seem to have a precision loss on decimal.

I have the following mapping : 
```xml
<property name="Target80">
     <column name="`Target80`" sql-type="decimal (25, 23)" not-null="true" />
</property>
```
for a column defined in SQL SERVER as Decimal(25,23)

When I save data to the database, it only saves with precision 10

Saving the value "0.9987425544115787544545" result in "0.99874255440000000000000" in the database

**Comment by hazzik** [comment]
You should specify "precision" and "scale" attributes on the property/column, otherwise it would be treated with default .NET precision, which is 19-10.

```xml
<property name="Target80">
     <column name="`Target80`" sql-type="decimal (25, 23)" not-null="true" precision="25" scale="23" />
</property>
```

**Comment by walteralmeida** [comment]
Thank you, very helpful and solved my issue
