### ISSUE TITLE
Unable to Implement Custom Tuplizer Due to Internal Constructor in DynamicMapEntityTuplizer

### ISSUE THREAD

**Issue by Ganesh13024** [nhibernate/nhibernate-core#3602]
In the NHibernate documentation (Chapter 4.5. Tuplizers), it's mentioned that it's possible to extend NHibernate.Tuple.Entity.DynamicMapEntityTuplizer and create a custom tuplizer. However, when attempting to do so, I found that the constructor for this class is marked as internal, which prevents users from implementing a custom tuplizer if NHibernate is used as a NuGet package.

The constructor of DynamicMapEntityTuplizer should be public, allowing developers to extend this class and implement custom tuplizers as described in the documentation.

**Comment by fredericDelaporte** [comment]
See [nhusers this convertation](https://groups.google.com/g/nhusers/c/dg3OnfrvtXM/m/mhhvSvD5CAAJ) which is partly about that.

> Indeed, it is internal since 2007, and that was overlooked when this example was introduced in the documentation in 2009. Since the PocoEntityTuplizer has its constructor public, it would also be more consistent.
