### ISSUE TITLE
could not instantiate CacheProvider

### ISSUE THREAD

**Issue by mazharqayyum** [nhibernate/nhibernate-core#774]
We make use of SysCache as our second level cache provider. After upgrade to version 5.0 its throwing following exception upon Configuration.BuildSessionFactory()

> could not instantiate CacheProvider: NHibernate.Caches.SysCache.SysCacheProvider, NHibernate.Caches.SysCache

`   at NHibernate.Cfg.SettingsFactory.CreateCacheProvider(IDictionary`2 properties)
   at NHibernate.Cfg.SettingsFactory.BuildSettings(IDictionary`2 properties)
   at NHibernate.Cfg.Configuration.BuildSettings()
   at NHibernate.Cfg.Configuration.BuildSessionFactory()`

**Comment by hazzik** [comment]
Caches is not yet supported with 5.0: https://github.com/nhibernate/NHibernate-Caches/pull/5

**Comment by fredericDelaporte** [comment]
Alpha versions have been published for SysCache, SysCache2 and RtMemoryCache. Let us now if they are working for you.

**Comment by mazharqayyum** [comment]
Awesome! After updating the package to alpha I am able to run our website with SysCache enabled. I don't have profiler enabled at the moment so can't see cache hit statements logged by its working now. Last time with old package it was resulting in hard error I posted above. 

One question. I see that SysCache still needs Iesi.Collections. Aren't they abandoned/obsolete? Can you please expand on the fate of Iesi.Collections. During the upgrade from version 3 to 5 I had to replace Iesi.Collections.ISet with System.Collections.Generic.ISet and so removed the reference completely. Now its back with SysCache alpha so seems like still needed.

**Comment by fredericDelaporte** [comment]
Iesi is a dependency of NHibernate, and so comes as a dependency of caches too.
Iesi interfaces are no more used because they have been replaced by .Net Framework 4 equivalent interfaces in NHibernate 4 and Iesi 4. But some concrete Iesi implementations are still lacking in `System.Generic.Collection` (mainly ordered hashset), and so those Iesi concrete implementations are still used when needed by NHibernate.

**Comment by mazharqayyum** [comment]
Alright, thanks for the explanation. Looks like lesi collections are going to stay with version 5 too.
